- src/altinn-app-frontend/webpack.config.development.js
See https://github.com/Altinn/altinn-studio/pull/8333 for details. This code was moved to a separate repo before that PR was merged.
> chore: disable warning overlay for webpack dev server

- test/cypress/e2e/config/local.json
- test/cypress/e2e/fixtures/texts.json
- test/cypress/e2e/integration/app-frontend/feedback.js
- test/cypress/e2e/integration/app-frontend/receipt.js
- test/cypress/e2e/integration/app-frontend/stateless.js
- test/cypress/e2e/pageobjects/app-frontend.js
- test/cypress/e2e/support/app-frontend.js
- test/cypress/e2e/support/index.d.ts
Copy of Altinn/altinn-studio#8344.
code from altinn-studio repo will be removed once all pipelines are setup.
> new tests in app frontend

- test/cypress/e2e/integration/app-frontend/options.js
- test/cypress/e2e/pageobjects/app-frontend.js
- test/cypress/e2e/support/app-frontend.js
- test/cypress/e2e/support/index.js
- test/cypress/e2e/support/wcag.js
- test/cypress/package.json
- test/cypress/yarn.lock
Note: copy of Altinn/altinn-studio#8377
- updated deps for cypress tests projects
- moved wcag custom command to a new file
- new test to build options from repeating groups.
> New tests for app frontend

- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/components/base/CheckboxesContainerComponent.tsx
- src/altinn-app-frontend/src/components/base/RadioButtonsContainerComponent.tsx
Changing colors to constants from theme
- #11
> bug: changing color for checkboxes/radios to theme

- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/features/form/containers/Form.tsx
- src/altinn-app-frontend/src/utils/validation.test.ts
- src/altinn-app-frontend/src/utils/validation.ts
The validation procedure for empty fields failed to account for hidden groups.
- altinn/altinn-studio/issues/6398
> Validation failed to account for hidden groups

- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/features/form/dynamics/types/index.ts
- src/altinn-app-frontend/src/utils/conditionalRendering.test.ts
- src/altinn-app-frontend/src/utils/conditionalRendering.ts
Now supports dynamics in nested groups.
- #55
> feat: dynamics in nested groups

- src/package.json
- src/yarn.lock
Add prettier to dependency in package.json
Prettier plugin in Intellij won't work without installing prettier in project
> Add prettier to package.json

- src/altinn-app-frontend/src/components/presentation/Header.test.tsx
- src/altinn-app-frontend/src/components/presentation/Header.tsx
- src/altinn-app-frontend/src/components/presentation/Progress.tsx
- src/altinn-app-frontend/src/features/form/layout/formLayoutSlice.ts
- src/altinn-app-frontend/src/shared/containers/Presentation.tsx
- src/altinn-app-frontend/src/shared/containers/__snapshots__/Presentation.test.tsx.snap
- src/altinn-app-frontend/src/types/index.ts
- src/shared/src/language/texts/en.ts
- src/shared/src/language/texts/nb.ts
- src/shared/src/language/texts/nn.ts
Progress component displayed in header. To show progress add the setting `"showProgress":"true"` Page settingsfile:
Example:
```json
{
"$schema": "https://altinncdn.no/schemas/json/layout/layoutSettings.schema.v1.json",
"pages": {
"order": [
"student-info",
"school-work",
"well-being"
],
"showProgress": "true"
}
}
```
[As a user I would like to see my progress in the application](https://github.com/Altinn/app-frontend-react/issues/188)
> Progress component

- src/altinn-app-frontend/src/shared/resources/textResources/fetch/fetchTextResourcesSagas.test.ts
- test/cypress/e2e/integration/app-frontend/confirmation.js
- test/cypress/e2e/integration/app-frontend/receipt.js
Minor fixes, as attempts to make unit tests (and cypress tests) more stable. See individual commits for more details.
> Stabilizing tests

- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/components/base/MapComponent.test.tsx
- src/altinn-app-frontend/src/components/base/MapComponent.tsx
- src/altinn-app-frontend/src/components/index.ts
- src/altinn-app-frontend/src/components/summary/MapComponentSummary.tsx
- src/altinn-app-frontend/src/components/summary/SummaryComponentSwitch.tsx
- src/altinn-app-frontend/src/features/form/layout/index.ts
- src/altinn-app-frontend/src/global.d.ts
- src/altinn-app-frontend/webpack.common.js
- src/shared/src/language/texts/en.ts
- src/shared/src/language/texts/nb.ts
- src/shared/src/language/texts/nn.ts
- src/yarn.lock
- tsconfig.json
Map component
Map component for selecting a lat/lon location as described in https://github.com/Altinn/altinn-studio/issues/8480
- https://github.com/Altinn/altinn-studio/issues/8480
- Design system komponent: https://github.com/Altinn/altinn-design-system/pull/60
> Map component

- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupTable.tsx
- src/shared/src/components/molecules/AltinnMobileTable.tsx
> bug: hide top border when mobile rep group has no items

- renovate.json
update renovate config to extend from Altinn defaults https://github.com/Altinn/renovate-config
- #274
> chore: update renovate config to extend from Altinn defaults

- .github/workflows/release.yml
My sloppiness in #433 caused the release script to fail yet again. This time I've done the laborious task of trying to reproduce the script locally (without committing to CDN, obviously). It should work now :crossed_fingers: Sorry for all the noise!
- #430 
- #433
- ~~[ ] All tests run green~~
> Fixing release script (again)

- src/shared/src/language/texts/en.ts
- src/shared/src/language/texts/nb.ts
- src/shared/src/language/texts/nn.ts
After #100 got implemented, this text has gone unused
- #100
- #270
> Removing unused text

- README.md
- docker-compose.yml
- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/webpack.config.docker.js
If you can't/won't install node on your computer, you can also run frontend in docker.
> Docker compose

- README.md
> Include clone command for docker setup

- src/altinn-app-frontend/src/components/base/MultipleSelect.test.tsx
- src/altinn-app-frontend/src/components/base/MultipleSelect.tsx
Add support for using text resources in labels for multiple select component.
- #516
> add language support for labels

- src/altinn-app-frontend/src/features/form/containers/Form.tsx
- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupsEditContainer.tsx
- test/cypress/cypress.config.js
- test/cypress/e2e/integration/app-frontend/components.js
- test/cypress/e2e/integration/app-frontend/confirmation.js
- test/cypress/e2e/integration/app-frontend/message.js
- test/cypress/e2e/integration/app-frontend/on-entry.js
- test/cypress/e2e/integration/app-frontend/print-button.js
- test/cypress/e2e/integration/app-frontend/receipt.js
- test/cypress/e2e/integration/app-frontend/redirect.js
- test/cypress/e2e/integration/app-frontend/reportee-selection.js
- test/cypress/e2e/integration/app-frontend/validation.js
- test/cypress/e2e/integration/app-frontend/wcag.js
- test/cypress/e2e/integration/app-stateless-anonymous/anonymous.js
- test/cypress/e2e/integration/app-stateless-anonymous/options.js
- test/cypress/e2e/integration/app-stateless/feedback.js
- test/cypress/e2e/integration/app-stateless/receipt.js
- test/cypress/e2e/integration/app-stateless/stateless.js
- test/cypress/e2e/integration/app-stateless/wcag.js
- test/cypress/e2e/pageobjects/app-frontend.js
- test/cypress/e2e/support/app-frontend.js
I've been working on stabilizing the Cypress tests that seem to be failing, and these are cherry-picked low-risk commits from that branch. This more functional changes will come later. Look at each commit in isolation to see why I changes these things.
- #575
> Stabilizing cypress tests (part 1)

- src/altinn-app-frontend/package.json
- src/yarn.lock
Includes the new table-component and an update to `react-number-format`.
- https://github.com/Altinn/altinn-design-system/pull/174
- https://github.com/Altinn/altinn-design-system/pull/164
- ~~Relevant automated test added (if you find this hard, leave it and we'll help out)~~
> Update design-system to 0.17.1

- schemas/json/layout/layout.schema.v1.json
Added the missing schema-definitions that where never merged into the old repo.
- Altinn/altinn-cdn#111
- Altinn/altinn-cdn#112
> Added missing schema-definitions

- test/cypress/e2e/support/start-app-instance.js
I guess @ivarne was right in his comments in #525 after all. In #621 many cypress tests failed when running against tt02, becuase the rewrite logic to forcibly load app-frontend from localhost:8080 instead of altinncdn.no did not kick in as anticipated. This failed now because the `frontend-test` application on tt02 now loads its frontend version from altinncdn.no by default as of yesterday evening.
- #525
- #621
> Fixing failing cypress redirect

- .vscode/settings.json
Update `editor.rulers` in `settings.json` to match the new prettier print-width.
- https://github.com/Altinn/app-frontend-react/pull/621
> Update vs-code settings (print-width)

- schemas/json/layout/expression.schema.v1.json
- schemas/json/layout/layout.schema.v1.json
- src/altinn-app-frontend/src/features/expressions/index.ts
- src/altinn-app-frontend/src/features/expressions/types.ts
This adds JsonSchema support for the expressions described in #540 and #355
- closes #577
- #355
- ~~[ ] All tests run green~~
> JsonSchema for expressions

- .github/release.yml
> Adding auto release notes based on labels

- .github/scripts/release.sh
The new release script failed because I have spaces in my name:
https://github.com/Altinn/app-frontend-react/actions/runs/3469849813/jobs/5797335200#step:7:91
- #{issue number}
> Release script: Fixing the author name + email

- src/altinn-app-frontend/src/components/base/CheckboxesContainerComponent.tsx
- src/altinn-app-frontend/src/components/base/RadioButtons/ControlledRadioGroup.tsx
- src/altinn-app-frontend/src/components/base/RadioButtons/radioButtonsUtils.ts
> Align radio and checkbox to top

- .github/scripts/release.sh
The 3.45.0 release did not use the `v` tag prefix, so it rolled out some broken assets on CDN. I've cleaned this up in the linked PR in CDN, but this should also make the release script fail hard if we should make that mistake again in the future.
Also linking #248 here, as I see that it's been solved for a while (easy to test out in the new release script by adding a line to overwrite the `CURRENT_VERSION` variable and test out the result for different versions.
- closes #248
- https://github.com/Altinn/altinn-cdn/pull/117
- Sprint board
> Release script: version number sanity check

- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupTable.tsx
- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupsEditContainer.tsx
- src/altinn-app-frontend/src/features/instantiate/containers/InstanceSelection.tsx
- src/shared/src/components/molecules/AltinnMobileTableItem.tsx
- src/yarn.lock
Upgrading to `v0.24.0` and replacing icons
- Sprint board
> Upgrading to the latest design system version

- schemas/json/layout/layout.schema.v1.json
Updated schema information for Datepicker attribute timestamp
> Datepicker-Timestamp update

- src/altinn-app-frontend/src/components/summary/SummaryGroupComponent.tsx
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- test/cypress/e2e/integration/app-frontend/summary.js
- test/cypress/e2e/support/navigation.js
The `SummaryGroupComponent` previously inserted the indexes into the map incorrectly, this has been fixed. Additionally, another potential bug was discovered when using dynamic options in a repeating group with multipage. This would trigger `initRepeatingGroup`, and the multipage index was not preserved so you could not navigate properly.
Tests were added to confirm that summary is able to display the dynamic options, and that they work in repeating groups. Tests depend on open PR in `frontend-test`. It passes all test when run against the updated `frontend-test`, but it is quite flaky when running locally. Has not been tested against `app-stateless` or `app-anonymous-stateless`.
- closes #680
- https://dev.altinn.studio/repos/ttd/frontend-test/pulls/10 …
> Fix code list with mapping not showing up in summary (repeating group)

- src/altinn-app-frontend/src/utils/rules/rules.test.tsx
- src/altinn-app-frontend/src/utils/validation/validation.test.ts
- src/altinn-app-frontend/src/utils/validation/validation.ts
Fixing alerts from #719
- #719
- Sprint board
> Fixing CodeQL alerts

- src/features/form/containers/RepeatingGroupTable.tsx
- src/features/form/containers/RepeatingGroupTableRow.tsx
Before pushing the new repeating-group-table to prod it might be a good idea to limit the amount of text shown in the table by default to be more in line with how it used to look before #603 gets done. I limited the number of lines to two since the table-rows have room for two lines without expanding its height very much.
- #603
- Sprint board
> Limit repeating-group-table content to two lines by default

- .github/workflows/cypress.yml
- .github/workflows/unit-tests.yml
This fell out when dependencies were moved out of `src`.
- Sprint board
> Running tests on dependency upgrades (again)

- src/layout/GenericComponent.tsx
- src/layout/List/ListComponent.test.tsx
- src/layout/List/ListComponent.tsx
> WCAG updates for List Component

- package.json
- webpack.config.development.js
I'm growing annoyed by the constant barrage of desktop notifications whenever there are syntax errors while I'm developing, so I went looking for a way to disable these. Turns out I had to make it myself.
- Sprint board
> Adding silent mode for webpack/`yarn start:silent`

- schemas/json/layout/layout.schema.v1.json
[Kartkomponent for stedfestelse i kart](https://github.com/Altinn/altinn-studio/issues/8480)
- Sprint board
> Added the missing map-component to layout.schema.v1.json

- src/features/expressions/index.ts
When discussing some expressions that were seemingly failing, we found two problems:
- `this` was mistakenly passed instead of `context`, causing a weird `cannot read properties of undefined` error when an `UnknownTargetType` error was thrown
- The `UnknownTargetType` was also trown by mistake, as it tried to find the `typeof` the default value when the default value was `null`, meaning the expression engine tried to cast the return value to an object (because `typeof null === 'object'`) when running in the `evalExpression()` debug function).
- https://altinn.slack.com/archives/C02FK32SFA4/p1673852667079089
- Support in …
> Expressions: Minor bugs, friction, debugging improvements

- src/features/form/components/Label.tsx
- src/layout/FileUpload/FileUploadComponent.tsx
- src/layout/FileUpload/shared/DropzoneComponent.tsx
- src/layout/FileUploadWithTag/EditWindowComponent.tsx
- src/layout/FileUploadWithTag/FileListComponent.tsx
Tested using voice over on Mac and iPhone.
- closes #31 
- closes #828 
- Sprint board
> WCAG: Fix screen reader issues with FileUpload

- package.json
- src/index.css
- src/styles/tjenester3.css
- yarn.lock
When trying to fix some styling I could not figure out where the css files were coming from. Turns out the (really) old [design system](https://github.com/Altinn/DesignSystem) was still imported as a dev-dependency and injected into `index.css` (only a single stylesheet). To get rid of this dependency I copied the file into this repo since this package has now been deprecated.
- https://github.com/Altinn/app-frontend-react/issues/232
- Sprint board
> Remove old design system dependency and import css directly

- src/features/form/containers/GroupContainer.tsx
- src/layout/Likert/LikertComponent.tsx
- src/layout/Likert/RepeatingGroupsLikertContainer.tsx
- src/utils/formLayout.ts
This is a pr to help the apps-team. Extensive PR-comments could be added by receiving team if needed. 
- closes #316
- Sprint board
> WCAG: Likert component fixes

- src/components/atoms/AltinnAttachment.tsx
- src/components/organisms/AltinnAppHeaderMenu.tsx
- src/components/presentation/CloseButton.tsx
- src/components/presentation/NavBar.tsx
- src/features/form/containers/RepeatingGroupsEditContainer.tsx
- src/index.css
- src/layout/NavigationBar/NavigationBarComponent.tsx
Added focus states to the components specified in figma:
- closes #232 
- Sprint board
> WCAG: Focus states

- package.json
- yarn.lock
Update altinn-design-system dependency to get the latest version of the table to support the correct tabindex.
- closes #830
- Sprint board
> Update altinn-design-system dep

- schemas/json/layout/layoutSettings.schema.v1.json
This property was not described in the schema
- Altinn/altinn-studio-docs/pull/835
- #221
- Sprint board
> Adding missing showProgress to layoutSettings schema

- .github/scripts/release.sh
- .github/workflows/release.yml
Using the existing release script to upload the files controlled by app-frontend-react to the new cdn solution.
For now both the old and the new CDN should be updated, once we are truly confident in the setup we can remove the old.
The new steps require som secrets, will mark the PR as ready when they are available.
- relates to: [altinn/altinn-studio#7566](https://github.com/Altinn/altinn-studio/issues/7566)
- Sprint board
> Add steps to release pipeline to publish to azure CDN

- README.md
Update links in readme to point to new app-localtest repo.
> Update links in readme to point to new app-localtest repo

- schemas/json/layout/layout.schema.v1.json
- src/components/summary/SummaryComponent.tsx
- src/features/expressions/index.ts
- src/features/form/containers/DisplayGroupContainer.tsx
- src/features/pdf/AutomaticPDFLayout.tsx
- src/layout/GenericComponent.tsx
- src/layout/layout.d.ts
- src/styles/print.module.css
- src/utils/formComponentUtils.ts
This changes the pageBreak options from a boolean to 'auto' (default, equivalent to false previously), 'always' (equivalent to true previously), and 'avoid'. This matches the css spec. Another change is that `pageBreak` can be added to components in the form so that it also works in the Automatic generation method.
This came up in a discussion with Eirik, and given that these are "breaking changes" compared to what was there previously, I would like to get this through before posting the updated documentation which I suppose amounts to "officially" releasing the new PDF feature.
- https://github.com/Altinn/app-frontend-react/issues/896
- Automated tests (**Separate issue**)
- ~~[ ] Unit test(s) have been added~~
- ~~[ ] Cypress E2E test(s) have been added~~
- ~~[ ] No …
> PDF: Added more page-break options

- .github/scripts/release.sh
Fix bug in release script
- Sprint board
> Fix release script

- package.json
- yarn.lock
Update digdir design system to get latest bugfixes:
Accordion: Fix subtitle placement issues ([#144](https://github.com/digdir/designsystem/issues/144)) ([316e450](https://github.com/digdir/designsystem/commit/316e4502d3b34a90ca577a45bbb367f547f6fb96))
Button: Enforce icon button to have same width and height ([#139](https://github.com/digdir/designsystem/issues/139)) ([9b3bb93](https://github.com/digdir/designsystem/commit/9b3bb93fc0e73b10a7522c07f54ca250b3d686b8))
HelpText: export help text size prop ([#147](https://github.com/digdir/designsystem/issues/147)) ([7a716bb](https://github.com/digdir/designsystem/commit/7a716bbed965ec8fb5f01799c7aea32be4fdd8e3))
InputWrapper: Change outline style to solid from auto to make outline-offset work …
> Update digdir design-system

- .github/scripts/release.sh
Bug in the release script for schemas part
- Sprint board
> Fix path issues for sync of schemas

- .github/pull_request_template.md
This improves our PR template to the one below:
- Sprint board
- Labels
> Changes to PR template

- tsconfig.json
Adding some options to tsconfig.json regarding strictness of type-checking. Some of these strict checks passed on our code already, but those below the fold are the ones I would like to flip at some point when our code passes those restrictions.
- Sprint board
> Strictness suggestions in `tsconfig.json`

- .github/scripts/release.sh
> Add missing files to sync and only sync schemas on final version

- src/styles/tjenester3.css
In the old design system css, the font-weights were set to `'bold'` instead of `bold`. It may have happened when moving the css file into this repository somehow.
- https://altinn.slack.com/archives/C02EVE4RU82/p1676389451801149
- Sprint board
- Labels
> Fix bold text from text-resources

- src/setupTests.ts
- src/shared/components/ReadyForPrint.tsx
Turned out to be an easy fix after all.
- closes #917 
- Sprint board
- Labels
> Fix fonts not loading in new pdf

- .github/workflows/release.yml
> fix bug in release script

- src/components/summary/SummaryComponent.tsx
Changed the summary component to pass the layout node to `GenericComponent` instead of the "legacy" form component from the formlayout state. This fixes the issue where row-specific text-resource bindings did not get the correct row information in a repeating group summary.
- closes #883 
- Sprint board
- Labels
> Fix generic component in group summary

- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
Endret valideringsmelding når det gjelder krav om min/max verdi. Bytter ut "verdi" med "tall". 
- closes #781
- Sprint board
- Labels
> Changed error message text - min & max

- src/layout/List/ListComponent.tsx
Added possibility to change language on headers in ListComponent.
- Sprint board
- Labels
> Add getTextResourceAsString to headers in listcomponent

- test/e2e/integration/app-frontend/multipart-save.ts
- Adds automatic export of some debug data so that we can figure out what went wrong if it fails again
- Inlined the code to add a row to repeating group, forcing a wait for saving between each step.
- Comparing the first row deletion in the repeating group using an object instead of array, so that we don't rely on order
- Sprint board
- Labels
> Fixing `multipart-save` flakyness

- package.json
- test/e2e/pageobjects/app-frontend.ts
- yarn.lock
Update to latest version of digdir designsystem which contains a fix for NVDA screen reader for helptext.
- closes #817 
- Sprint board
- Labels
> Update dependency digdir/designsystem

- package.json
- yarn.lock
Updated altinn-design-system dependency to the latest version.
- closes #999 999
- Sprint board
- Labels
> Updated altinn-design-system dependency to the latest version.

- .github/workflows/cypress.yml
- test/README.md
- test/e2e/config/at21.json
- test/e2e/config/at22.json
- test/e2e/config/local.json
- test/e2e/config/tt02.json
- test/e2e/integration/app-frontend/prefill.ts
- test/e2e/integration/app-stateless-anonymous/anonymous.ts
- test/e2e/integration/app-stateless-anonymous/options.ts
- test/e2e/integration/app-stateless-anonymous/validation.ts
- test/e2e/integration/app-stateless/stateless.ts
- test/e2e/integration/signing/double-signing.ts
- test/e2e/pageobjects/app-frontend.ts
- test/e2e/support/auth.ts
- test/e2e/support/global.d.ts
- test/e2e/support/index.ts
- test/e2e/support/start-app-instance.ts
- This PR only changes the cypress tests.
- All of the configuration needed to run the tests are now in `tt02.json` and `local.json`.
- In addition to a default user, three new users have been added for tt02 and localtest to test the signing flow:
- an accountant,
- a manager,
- and an auditor, all representing the same organization.
- The authentication logic has been moved to a new file `auth.ts`, and support for switching users during a test has been added.
- Since the necessary changes to show whether or not you have permission to confirm are not implemented yet, the signing test that was added simply tests a happy path that switches to the correct user for each step.
- first step in: #1003  …
> Cypress: Multiple users and basic signing test

- src/features/customReceipt/containers/CustomReceipt.tsx
- src/features/receipt/containers/ReceiptContainer.test.tsx
Fixes the bug with custom receipt not loading and instead showing the entire form. It appeared during a refactor from components to nodes.
- https://altinn.slack.com/archives/C02FK32PVFS/p1673350191793079
- Sprint board
- Labels
> Fix custom receipt not showing the correct layout

- src/components/presentation/LanguageSelector.tsx
Quick fix by adding a reasonable minimum width. Tested on mobile size with all other buttons present.
- closes #1022 
- Sprint board
- Labels
> Added minimum width to language selector

- src/components/summary/SummaryItemCompact.tsx
- src/layout/Dropdown/DropdownComponent.tsx
- src/layout/GenericComponent.tsx
- src/layout/List/ListComponent.tsx
- src/layout/Paragraph/ParagraphComponent.tsx
- src/layout/index.ts
- src/layout/layout.d.ts
- src/types/index.ts
- src/utils/formComponentUtils.ts
There was a missing null check in `SummaryItemCompact`. This error was quite subtle, because there was a check for `textResourceBindings`, but not `textResourceBindings.title`. This was a problem because the markdown parsing function did not accept undefined, and would crash if given undefined.
Typescript did not complain about this, even though we know perfectly well that not all possible items inside of `textResourceBindings` are defined. Turns out that the `ITextResourceBindings` type was defined so that anything inside can never be undefined. I changed the type to `string | undefined` to better reflect reality so that hopefully this will not happen so much again.
- https://altinn.slack.com/archives/C02EENC8KBR/p1679659341081909
- …
> Added null check for textResourceBindings.title in `SummaryItemCompact`

- schemas/json/layout/layout.schema.v1.json
Quick fix to remove incorrect warnings on group panel configuration:
> Fix group panel schema

- src/features/devtools/DevTools.tsx
Shift + k = K on my machine
- Sprint board
- Labels
> Fixing the devtools keyboard shortcut

- src/features/process/completeProcessSagas.ts
- src/features/profile/profileSlice.ts
- src/utils/party.ts
- src/utils/urls/appUrlHelper.ts
- src/utils/urls/urlHelper.ts
- test/e2e/integration/app-stateless/feedback.ts
- test/e2e/integration/app-stateless/receipt.ts
This adds a new query parameter to process.next `lang`, which is the current language used when filling out the form. This also uses the query-parameter `lang` in app-frontend to show the correct language when generating the PDF.
This fixes the issue where the user changing the language through the language selector is not respected by the PDF generation, but also requires app-lib to add the parameter from process.next to the app-url that is sent to the pdf-service.
- closes #1073 
- depends on https://github.com/Altinn/app-lib-dotnet/pull/227 …
> Support language selector in PDF

- src/features/devtools/components/LayoutInspector/LayoutInspector.module.css
- src/features/devtools/components/LayoutInspector/LayoutInspector.tsx
- src/features/devtools/components/LayoutInspector/LayoutInspectorItem.tsx
- src/features/devtools/components/SplitView/SplitView.module.css
- src/features/devtools/components/SplitView/SplitView.tsx
I wanted something cool to show off on Altinn Kaffe, this allows you to modify component properties and see how it affects your layout. I think this makes the developer experience much better since you normally would have to refresh the entire page to try out small changes. Additionally, you don't have to make changes to your actual layout file and risk forgetting to change them back.
https://user-images.githubusercontent.com/47412359/232710147-9eb9ea75-4a5f-4afe-b7e0-df9ee5188e87.mov
> DevTools: Change component properties

- schemas/json/layout/layout.schema.v1.json
- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
- src/types/index.ts
- test/e2e/integration/app-frontend/components.ts
Enables the use of descriptions for options in CheckboxGroups and RadioGroups
- https://github.com/Altinn/app-frontend-react/issues/260
Backend PR: https://github.com/Altinn/app-lib-dotnet/pull/230
- Sprint board
- Labels
> Enable description for checkboxes and radiobuttons

- src/components/presentation/Header.tsx
Added screen reader to progress indicator
- closes #1028 
- Sprint board
- Labels
> Progress indicator - Screen Reader

- src/features/devtools/DevToolsControls.tsx
- src/features/devtools/components/DevNavigationButtons/DevNavigationButtons.tsx
- src/features/devtools/components/OpenDevToolsButton/OpenDevToolsButton.module.css
- src/features/devtools/components/PermissionsEditor/PermissionsEditor.module.css
- src/features/devtools/components/PermissionsEditor/PermissionsEditor.tsx
In order to work with expressions and conditional layouts based on policy permissions, as will be the case with signing; it is nice to be able to see how they work without having to log in to a different user. This does pretty much the same thing as the "dev-tools" in the signing-test app, allowing you to update the permissions to see how that affects the layout. This is currently disabled as it checks the backendFeature flag for processPermissions, but as soon as that is enabled and the app is updated this will become available.
https://user-images.githubusercontent.com/47412359/235697759-1dc04cb3-e9f1-44e9-81cf-9e126c87cf8a.mov
- #991 
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell- …
> Policy editor in developer tools

- src/layout/Image/ImageComponent.tsx
- src/layout/Paragraph/ParagraphComponent.tsx
Update paragrapch component and image component to use getTextResource for helptext in order to support rich text.
slack thread reporting issue:
https://altinn.slack.com/archives/C02ESDSC929/p1683035943162759
- Sprint board
- Labels
> Allow rich text in helptext for paragraph and image components

- src/layout/Panel/Panel.module.css
- src/layout/Panel/PanelGroupContainer.tsx
Making the panel body fix render the body text as a full-width element (in case there are grid components inside).
Turns this:
Into this:
- #1153 
- #1154
- Sprint board
- Labels
> Non-repeating group panel body fix for grid components

- src/layout/Group/GroupContainer.tsx
- src/layout/Group/RepeatingGroupTable.tsx
- src/layout/Group/RepeatingGroupsEditContainer.test.tsx
- src/layout/Group/RepeatingGroupsEditContainer.tsx
- test/e2e/integration/app-frontend/hide-row-in-group.ts
- test/e2e/pageobjects/app-frontend.ts
Generic nextIndex that works as intended also when the feature `hiddenRow` is used.
- closes #1146 
- Sprint board
- Labels
> Fix behavior of display "save and open next"-button when some rows are hidden

- src/features/devtools/DevToolsControls.tsx
- src/features/devtools/components/VersionSwitcher/VersionSwitcher.tsx
- src/utils/urls/appUrlHelper.ts
Adds a frontend version selector to developer tools. Refresh the page to revert to using the original version.
- https://github.com/Altinn/app-frontend-react/issues/1021
- Sprint board
- Labels
> DevTools: Frontend version switcher

- src/layout/Likert/GroupContainerLikert.test.tsx
- src/layout/Likert/GroupContainerLikertTestUtils.tsx
- src/layout/Likert/LikertComponent.tsx
The bug is described in details in the issue. 
- closes #1205
- Sprint board
- Labels
> Bug: Fix label for Likert table

- schemas/json/layout/layout.schema.v1.json
- src/layout/IFrame/IFrameComponent.tsx
- src/layout/IFrame/types.d.ts
- src/layout/IFrame/utils.test.ts
- src/layout/IFrame/utils.ts
This adds a new `sandbox` property to the `IFrame` configuration. The thought here is that we make available a subset of the sandbox attributes from the spec: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#sandbox. This is configured to use the same names as in the spec but in camelCase to be consistent with our config, it should be very easy to make new attributes available in the future if there are new requirements.
Now for example if you want to allow links to open in a new tab from the IFrame, you would want to set:
- `allowPopups: true` to be allowed to open links at all. And
- `allowPopupsToEscapeSandbox: true` to not have any sandbox restrictions on the new tab. This is required for even running javascript.
- closes #1216 
- …
> IFrame: Allow popups properties

- src/styles/tjenester3.css
This one was quite strange, there was a rule from the old old design system that would make `.form-group` hidden on `@media print`. In this one app only this rule was not overridden and so all generic components were hidden from PDF. Maybe we should bite the bullet and finally do [#858](https://github.com/Altinn/app-frontend-react/issues/858).
I tested this manually on the app from the slack thread:
https://altinn.studio/repos/udir/vfkl
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1685703534127879
- …
> Quickfix: Generic component hidden in PDF in some cases

- package.json
- src/components/atoms/AltinnAttachment.tsx
- src/components/organisms/AltinnAppHeaderMenu.tsx
- src/components/presentation/NavBar.module.css
- src/features/footer/components/shared/shared.module.css
- src/index.css
- src/layout/Datepicker/DatepickerComponent.tsx
- src/layout/Group/__snapshots__/SummaryGroupComponent.test.tsx.snap
- src/layout/Likert/LikertComponent.tsx
- src/layout/NavigationBar/NavigationBarComponent.tsx
- src/styles/utils.module.css
- test/e2e/integration/app-frontend/mobile.ts
- test/e2e/integration/app-frontend/options.ts
- test/e2e/integration/app-frontend/rules.ts
- test/e2e/integration/app-frontend/summary.ts
- test/e2e/support/custom.ts
- test/e2e/support/global.d.ts
- test/e2e/support/index.ts
- yarn.lock
- Updated digdir design system to v0.13.0.
- Fixed some broken tests
- Updated focus design of our components so they still match
- Updated datepicker design to (almost) match design system inputs. (does not have an error icon)
- Sprint board
- Labels
> Dep: update @digdir/design-system-react to 0.13.0

- src/layout/TextArea/TextAreaComponent.tsx
Textareas should have a default height and the user should be able to resize the textarea with "drop and drag".
**Result:**
- closes PR it self.
- Sprint board
- Labels
> Default height on <TextArea/>

- src/App.tsx
The text in error messages below components stopped being styled. This was fixed by importing a new token package for typography from the design system.
Just a note, the design system uses fluid typography, so you'll see that the font size changes based on the width of the screen. 
Not sure if this is problematic considering other text elements that do not use fluid typography.
https://digdir.github.io/designsystem/?path=/docs/kjernekomponenter-typography--docs#bruk
- …
> Quick fix - fix styling of error message

- src/utils/render.tsx
This is related to [this pull request](https://github.com/Altinn/app-frontend-react/pull/1240), which involves adjusting the font size of error messages using fluid typography. As per the design team's recommendation, we will be using the "small" font size. Therefore, after the next release of the Design System, the error messages will have the same font size as the charLimit message.
https://github.com/Altinn/app-frontend-react/pull/1240
- …
> change size - ErrorMessage typography

- src/components/wrappers/ProcessWrapper.tsx
This small change will make sure that the `<Form />` component is used to display any step that has a layout set, not just data/confirm.
- https://github.com/Altinn/app-template-dotnet/issues/170
- Sprint board
- Labels
> Support layout sets for signing task type

- package.json
- schemas/json/layout/layout.schema.v1.json
- src/components/form/RadioButton.module.css
- src/components/form/RadioButton.test.tsx
- src/components/form/RadioButton.tsx
- src/components/form/RadioGroup.module.css
- src/components/form/RadioGroup.tsx
- src/layout/Checkboxes/types.d.ts
- src/layout/Likert/LikertComponent.tsx
- src/layout/Likert/types.d.ts
- src/layout/RadioButtons/ControlledRadioGroup.tsx
- src/layout/RadioButtons/RadioButtonsContainerComponent.tsx
- src/layout/RadioButtons/radioButtonsUtils.ts
- src/layout/RadioButtons/types.d.ts
- src/layout/layout.d.ts
- yarn.lock
- Added a new `RadioButton` component which has the option of being rendered with a `Card` wrapped around the component. 
- Added a `RadioGroup` component which accepts `RadioButtons` as children.
- Refactored the old `ControlledRadioGroup` component to use this new `RadioGroup` component instead of using `RadioGroup` from `@digdir/design-system`. 
- closes #1247 
- Sprint board
- Labels
> Add new RadioButton and RadioGroup components.

- src/features/devtools/DevToolsControls.tsx
- src/features/devtools/components/ExpressionPlayground/ExpressionPlayground.tsx
- src/features/devtools/components/FeatureToggles/FeatureToggles.module.css
- src/features/devtools/components/FeatureToggles/FeatureToggles.tsx
- src/features/devtools/components/SplitView/SplitView.tsx
- src/features/devtools/data/types.ts
- src/features/toggles.ts
- src/global.d.ts
- src/hooks/useAlwaysPromptForParty.ts
- src/setupTests.ts
Let me know if the text I added here is correct, @bjosttveit.
You can now view the current settings for each feature toggle, and override it using:
1. Cookies (set on the `/org/app` path, with session-only validity)
2. The `window.featureToggles` object, to be able to override frontend features per-app, permanently
- Sprint board
- Labels
> DevTools: Control panel for setting feature toggles

- schemas/json/text-resources/text-resources.schema.v1.json
- src/utils/layout/getAllLayoutSets.ts
- src/utils/layout/schema.test.ts
Creating a schema for text resource files. This should at some point be added to the default text resources in the app template, and be added to new text resource files added by Studio. Adding to existing files should be easy, just add:
```json
{
"$schema": "https://altinncdn.no/schemas/json/text-resources/text-resources.schema.v1.json",
"language": "..",
"resources": []
}
```
To your text resource file (after this has been merged and released). This should give you autocomplete suggestions for new text resources and variables.
- https://altinn.slack.com/archives/C02EVE4RU82/p1687880934464099
- User …
> JsonSchema for text resources

- src/layout/FileUpload/FileUploadComponent.module.css
- src/layout/FileUpload/FileUploadTableRow.module.css
Fixed borders not being displayed in the table for FileUpload + adjusting spacing.
- Sprint board
- Labels
> Quick Fix: styling in FileUploadTable

- src/features/pdf/PDFView.tsx
Turns out logging to devtools in the `PDFComponent` caused an infinite loop of rerenders, now using a ref to make sure it only logs once.
- closes #1323 
- Sprint board
- Labels
> Fixed log-related render loop in pdf view

- src/components/presentation/LanguageSelector.tsx
- src/features/devtools/DevToolsControls.tsx
- src/features/devtools/components/DevLanguageSelector/DevLanguageSelector.tsx
Small PR to add the language selector to devtools, so different languages can be easily tested without adding a language selector to the app.
- #1021 
- Sprint board
- Labels
> DevTools: Language selector

- src/layout/Group/RepeatingGroupTableRow.tsx
- src/layout/LayoutComponent.tsx
- src/layout/index.ts
In the `RepeatingGroupTableRow` component [the first rule of hooks](https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) was broken. This would probably not lead to any errors in real world use, as the number of table headers shown never changes at runtime, but it caused a crash when trying to change `tableHeaders` using the developer tools when looking into [this problem from slack](https://altinn.slack.com/archives/C047F8FK2NQ/p1691394353848259).
- ~~closes #{issue number}~~
- …
> Fix useDisplayData hook usage in `RepeatingGroupTableRow`

- renovate.json
Trying to fix the renovate schedule, using cron syntax instead.
> Renovate schedule for design system

- src/hooks/useFormattedOptions.tsx
- src/layout/Dropdown/DropdownComponent.tsx
- src/layout/FileUpload/FileUploadTable/FileTableComponent.tsx
- src/layout/FileUploadWithTag/EditWindowComponent.tsx
- src/layout/MultipleSelect/MultipleSelectComponent.tsx
I went ahead and refactored the options formatting into a hook, so that we are more consistent. This also adds support for description in tag options.
- closes #1382 
- Sprint board
- Labels
> fix(FileUploadWithTag): Unable to use langauge resource files

- schemas/json/application/application-metadata.schema.v1.json
- src/utils/layout/schema.test.ts
The test for the application metadata schema wasn't really working (it checked the wrong location and failed to import the package needed for the date-time format to work). Also, improving the schema to disallow additional properties wherever we can, adding some missing properties, changing some texts, etc. My sources include the [docs](https://docs.altinn.studio/nb/api/models/app-metadata/) and [storage models](https://github.com/Altinn/altinn-storage/tree/main/src/Storage.Interface/Models). By making the schema stricter, we find a few mistakes in existing configuration files that are most likely caused by mis-typing or misunderstanding. Without setting `additionalProperties = false` the schema would only give the user hints and tips, but no guarding against filling out properties that …
> Multiple fixes to applicationmetadata schema (and tests)

- src/components/EditIconButton.tsx
- src/components/molecules/DeleteWarningPopover.tsx
- src/components/presentation/NavBar.tsx
- src/features/devtools/DevToolsPanel.tsx
- src/features/devtools/components/DevToolsLogs/DevToolsLogs.tsx
- src/features/devtools/components/DownloadXMLButton/DownloadXMLButton.tsx
- src/features/devtools/components/FeatureToggles/FeatureToggles.tsx
- src/features/devtools/components/LayoutInspector/LayoutInspector.tsx
- src/features/devtools/components/NodeInspector/NodeInspector.tsx
- src/features/devtools/components/OpenDevToolsButton/OpenDevToolsButton.tsx
- src/features/devtools/components/PDFPreviewButton/PDFPreviewButton.tsx
- src/features/devtools/components/VersionSwitcher/VersionSwitcher.tsx
- src/features/instantiate/containers/InstanceSelection.tsx
- src/features/instantiate/containers/PartySelection.tsx
- src/features/instantiate/containers/UnknownError.tsx
- src/layout/ActionButton/ActionButtonComponent.tsx
- src/layout/Button/WrappedButton.tsx
- src/layout/FileUploadWithTag/EditWindowComponent.tsx
- src/layout/Group/GroupContainer.tsx
- src/layout/Group/RepeatingGroupTableRow.tsx
- src/layout/Group/RepeatingGroupsEditContainer.tsx
- src/layout/Link/LinkComponent.tsx
- src/layout/NavigationButtons/NavigationButtonsComponent.tsx
- src/layout/Panel/PanelReferenceGroupContainer.tsx
- src/layout/PrintButton/PrintButtonComponent.tsx
- src/layout/Summary/EditButton.tsx
Adjusted button size to small in preparation for the [upcoming design update](https://github.com/Altinn/app-frontend-react/pull/1377), which will switch the default size from small to medium.
- Sprint board
- Labels
> Maintain small button size after design update

- src/layout/Alert/Alert.tsx
Opens up for using Markdown and HTML inside the body of an `Alert` component.
- closes #1404 
- Sprint board
- Labels
> feat(Alert): Add possibility for Markdown in body

- src/hooks/useCanSubmitForm.ts
- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/Button/ButtonComponent.module.css
- src/layout/Button/ButtonComponent.tsx
- src/layout/Button/ButtonLoader.module.css
- src/layout/Button/GoToTaskButton.tsx
- src/layout/Button/WrappedButton.tsx
Disable submit button if attachments are pending.
- closes #1407 
- Sprint board
- Labels
> Wait for upload attachment before submit

- package.json
- src/App.tsx
- yarn.lock
Fix the title WCAG title violation and add `@types/reselect` to fix unknown type returned by `appName` and `appOwner` selectors.
- closes #1395
> WCAG: Fix special character in title

- package.json
- src/features/expressions/index.ts
- src/features/formRules/checkRulesSagas.ts
- src/features/layout/formLayoutTypes.ts
- src/features/layout/repGroups/initRepeatingGroupsSaga.ts
- src/features/layout/repGroups/repGroupAddRowSaga.ts
- src/features/layout/repGroups/repGroupDeleteRowSaga.ts
- src/features/layout/update/updateFormLayoutSagas.ts
- src/hooks/useStateDeepEqual.ts
- src/layout/Address/AddressComponent.tsx
- src/layout/Group/RepeatingGroupTableRow.tsx
- src/layout/LayoutComponent.tsx
- src/layout/index.ts
- src/utils/appMetadata.ts
- src/utils/databindings.ts
- src/utils/rules/index.ts
- src/utils/rules/rules.test.tsx
- yarn.lock
These changes should make it easier to merge from main when working on #1175 in the future. Fixes:
- Installing `use-immer`, as it is needed in the new form data context (and `package.json` and `yarn.lock` gets rapid-fire changes all the time)
- Fixing a problem in setting validation messages in the Address component that I spent a lot of time debugging in the branch - it caused re-render loops without this fix.
- Updating some comments, fixing some type returns
- Making sure to fetch `formData` not the entire form data state object in some cases. These made it harder to rewrite where we fetch formData from.
- #1175
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we …
> Minor changes to make merging from main in #1175 easier

- src/features/devtools/components/DownloadXMLButton/DownloadXMLButton.tsx
- src/features/devtools/components/OpenDevToolsButton/OpenDevToolsButton.module.css
- src/features/logging.ts
Fixing some small issues that have been bugging me:
- Error indicator on devtools button had fallen beneath the button
- Upload XML did not work when using ProcessDataWrite
- When logging axios errors, the response was not included even though it usually contains useful information
> Small tweaks/fixes to dev tools

- src/features/instantiate/containers/InstanceSelection.tsx
Fixes the functionality to work on Mac (or whenever you've clicked using the meta key), and opening the links in a background tab (just like the browser would for other links)
- #1427
- Sprint board
- Labels
> Fixing the 'open instance in new tab' functionality to work on Mac

- schemas/json/layout/layoutSettings.schema.v1.json
After publishing a new version of the layout json schema, @bjosttveit noticed that the reference to triggers in `layoutSettings.schema.v1.json` was broken. Changed this to a relative reference so that we have a chance to notice these things before the schema is published to CDN.
- #832
- Sprint board
- Labels
> Fixing reference for triggers in `layoutSettings.schema.v1.json`

- src/index.css
Change font to Inter.
- https://github.com/Altinn/app-frontend-react/pull/1385
- Sprint board
- Labels
> Update font to Inter

- src/features/devtools/components/FeatureToggles/FeatureToggles.tsx
- src/features/toggles.ts
- src/hooks/useAlwaysPromptForParty.ts
- test/e2e/integration/frontend-test/reportee-selection.ts
Respect the profile preference for do not prompt for party. Also remove feature toggle and show a message in dev tools since the beta-functionality tab is empty now
- https://github.com/Altinn/app-frontend-react/issues/268
- Sprint board
- Labels
> Respect do not prompt for party preference and remove feature toggle

- src/codegen/Common.ts
Updated description of read-only.
https://altinn.slack.com/archives/C02ESDSC929/p1693308338743449
https://github.com/Altinn/altinn-studio-docs/pull/1168
- Sprint board
- Labels
> Update readOnly description

- src/features/attachments/upload/uploadAttachmentSagas.ts
Fixing a missing await in backend introduced a change in the respons
Change was made in this PR https://github.com/Altinn/app-lib-dotnet/pull/282 and released in v7.13.1 of app-lib
Best effort to check to determine if the response from backend is of the new or old format
- Sprint board
- Labels
> Fixing a missing await in backend introduced a change in the API response

- src/layout/RadioButtons/ControlledRadioGroup.module.css
- src/layout/RadioButtons/ControlledRadioGroup.tsx
Aligns help text and label for radio groups. 
- #1453
- Sprint board
- Labels
> fix(RadioGroup): align helptext with label

- .github/workflows/release.yml
This change should also be cherry picked to the v3 branch
- Sprint board
- Labels
> Switch release pipeline to production CDN.

- src/components/form/RadioButton.tsx
- src/layout/Likert/LikertComponent.module.css
- src/layout/Likert/LikertComponent.tsx
- src/layout/Likert/RepeatingGroupsLikertContainer.test.tsx
…added.
- closes #1535
- Sprint board
- Labels
> Likert: Remove extra labelledById attribute

- src/codegen/Common.ts
- src/features/options/useGetOptions.ts
- src/layout/Dropdown/DropdownComponent.tsx
- src/layout/Dropdown/config.ts
- src/layout/RadioButtons/RadioButtonsContainerComponent.test.tsx
Adds the support for a `sortOrder` property to all selectable components and not just Dropdown.
- closes #1599 
- Sprint board
- Labels
> feat: add support for sortOption for all selection components

- jest.config.js
- package.json
- src/__mocks__/fileMock.ts
- src/setupTests.ts
- src/test/jestTools/transformCss.js
- src/test/jestTools/transformFile.js
- template.env
- yarn.lock
[Jest Preview](https://www.jest-preview.com/) allows us to preview a unit test `render()` call by rendering the resulting DOM in a browser.
In order to use this functionality, one would have to add the following to the local `.env` file:
```
JEST_PREVIEW=true
```
One could also set `JEST_PREVIEW_AUTO=true` to automatically render in jest-preview for every failing test. If not, you can simply call the `debug()` function from the `jest-preview` package in your test to make it show up in the browser.
Before running any tests that debug to jest-preview, you have to start the server by executing `yarn test:preview`. The first time you run these tests with jest-preview it will take some time for jest-preview to ingest the CSS files we import in tests. I've also added `yarn test:clear-cache` as …
> Adding `jest-preview`

- src/components/form/RadioButton.tsx
- src/components/molecules/DeleteWarningPopover.tsx
- src/layout/Checkboxes/CheckboxesContainerComponent.module.css
- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
- src/layout/Checkboxes/WrappedCheckbox.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
- test/e2e/integration/frontend-test/components.ts
This PR fixes three bugs related to the alertOnChange feature:
1. Dialog buttons mispositioned when checkBox has a horizontal layout.
2. Checkbox group triggers dialog on every checkbox, not just the intended checkbox.
3. Radiobuttons dialog doesn't translate option labels in the dialog box.
By adding cypress tests, this aims to prevent the recurrence of these issues.
- closes https://github.com/Altinn/app-frontend-react/issues/1593
- Sprint board
- Labels
> Fix: alertOnChange bugs

- src/features/language/LanguageProvider.tsx
- test/e2e/integration/frontend-test/language.ts
Fixes an issue where the user can have the value `"null"` stored in localStorage as the selected language which results in a failure of the app. 
- closes #1729
- Sprint board
- Labels
> Language provider fetching null language

- src/__mocks__/getApplicationMetadataMock.ts
- src/components/altinnError.tsx
- src/features/applicationMetadata/ApplicationMetadataProvider.tsx
- src/features/applicationMetadata/OldVersionError.tsx
- src/features/applicationMetadata/index.d.ts
- src/features/instantiate/containers/InstantiationErrorPage.tsx
- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/utils/network/networking.ts
This implements an error message when the nuget/backend packages are too old for us to run the frontend. Current message is:
- closes #1496
- Sprint board
- Labels
> Implementing an error message when backend version is outdated

- src/index.tsx
- test/e2e/integration/frontend-test/navigation.ts
Fixes an issue where  scroll position was not restored to top when navigating between pages.
- closes #1753 
- Sprint board
- Labels
> fix: Navigating between pages scrolls the window to top

- src/features/devtools/DevTools.module.css
- src/features/devtools/DevToolsControls.tsx
- src/features/devtools/components/DevNavigationButtons/DevNavigationButtons.tsx
- src/features/devtools/components/DownloadXMLButton/DownloadXMLButton.tsx
- src/features/devtools/components/ExpressionPlayground/ExpressionPlayground.module.css
- src/features/devtools/components/ExpressionPlayground/ExpressionPlayground.tsx
- src/features/devtools/components/FeatureToggles/FeatureToggles.module.css
- src/features/devtools/components/LayoutInspector/LayoutInspector.module.css
- src/features/devtools/components/LayoutInspector/LayoutInspector.tsx
- src/features/devtools/components/NodeInspector/NodeInspector.tsx
- src/features/devtools/components/PermissionsEditor/PermissionsEditor.tsx
- src/features/devtools/data/DevToolsStore.ts
- src/features/logging.ts
- src/features/pdf/PDFWrapper.tsx
- src/layout/GenericComponent.module.css
- Fixes broken layout caused by removing `tjenester3.css` among other things
- Fixes logs disappearing
- Reimplement saving changes from layout inspector to work with tanstack query
- Reimplement permisson editing to work with tanstack query
- Mark pages missing from order as "hidden"
- Navigating to hidden pages is still not possible, added TODO
- Added `window.location.reload()` after uploading form data xml
- Could not find a proper way to reload the formData, invalidating the tanstack cache did cause a refetch, but it did not update the form data state, added TODO
- Fixed PDF preview button
- #1701  …
> DevTools bugfixes

- src/features/pdf/PDFView.module.css
- src/features/pdf/PDFWrapper.tsx
- src/hooks/usePdfPage.ts
- test/e2e/integration/frontend-test/pdf.ts
Using a custom layout for PDF was broken, this is fixed now along with `pdfFormatIsLoading` being weird (switched from isLoading to isFetching which solved it and is probably more correct). Also made a subtle change to `PDFWrapper` so it does not have to rerender the entire form when clicking the preview pdf button.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1706871336121199?thread_ts=1706691275.749619&cid=C02EJ9HKQA3
- Sprint board
- Labels
> Fix custom PDF layout

- src/features/pdf/PDFView.module.css
- src/features/pdf/PDFView.tsx
- src/features/pdf/usePdfFormatQuery.ts
- src/hooks/usePdfPage.ts
- src/layout/Summary/SummaryContent.module.css
Enable using the `grid` property in PDF.
- Automatically generated PDF-layouts will use the grid-configuration from the source component.
- In a custom PDF layout, the grid-configuration is no longer overridden.
- Also fixes the PDF format query which accidentally used the data model name instead of the data element guid.
- ~~closes #{issue number}~~
- Sprint board
- Labels
> Enable grid support in custom pdf

- src/layout/Group/GroupComponent.tsx
- src/layout/Group/config.ts
When grouping content one can set a title of the group with `textResourceBindings.title`, but this title defaults to a `h1`, `h2` or `h6` heading. This should be customisable, and this PR adds the property `headingLevel` which can be anything from `1` to `6`. 
- Sprint board
- Labels
> Added support for the property headingLevel on group components

- src/layout/CustomButton/CustomButtonComponent.tsx
This PR gives the developer som hints about what might be wrong when trying to execute a `ClientAction`. It also does not try to run ClientActions when they do not have an Id. 
- closes #1797 
- Sprint board
- Labels
> fix: add logging to devtools whenever an action fails. 

- src/layout/RepeatingGroup/Summary/SummaryRepeatingGroup.tsx
- src/layout/RepeatingGroup/Summary/__snapshots__/SummaryRepeatingGroup.test.tsx.snap
- test/e2e/integration/frontend-test/group.ts
Fixed issue:
https://github.com/Altinn/app-frontend-react/issues/1553
- closes #1553
- Sprint board
- Labels
> hiding hidden rows in summary

- src/features/form/layout/LayoutsContext.tsx
Cleanup of remaining code for non-layout-set support
- closes #1485
> Remove support for non-layout-sets apps

- src/features/layout/fetch/fetchFormLayoutSagas.test.ts
- src/features/layout/fetch/fetchFormLayoutSagas.ts
- src/hooks/queries/useFormDataQuery.ts
- src/hooks/useProcess.ts
- src/layout/Likert/RepeatingGroupsLikertContainer.test.tsx
- test/e2e/integration/frontend-test/custom-confirm.ts
- test/e2e/integration/frontend-test/validation.ts
This should fix the different state issues that caused the `go-to-task` button to not work properly in v3. Adding a test for it to make sure it continues to work (will port this over to v4+v8, using `ActionButton`).
- #1552
- Sprint board
- Labels
> Fixing `go-to-task` button, adding tests (v3)

- src/layout/Grid/GridComponent.tsx
See https://github.com/Altinn/app-frontend-react/pull/1819
> Fix `labelFrom` in Grid (v3)

- src/layout/LayoutComponent.tsx
- src/layout/RepeatingGroup/RepeatingGroupContainer.tsx
- src/layout/RepeatingGroup/index.tsx
This PR fixes a warning that was present in the `console`. The error was reported on slack https://altinndevops.slack.com/archives/C045EB3JA9X/p1708067852304989
- Sprint board
- Labels
> fix: use forwardRef instead of renaming the ref-component

- src/components/wrappers/Presentation.tsx
- src/features/layout/formLayoutSlice.ts
Fixes an issue with screen reader focus after page navigation. The focus is now set to the main content. If this focus is  not managed, screen readers may apply the focus at random.
- closes #1408 for v3
- Sprint board
- Labels
> fix: navigate to main content whenever the user performs a page navigation

- src/components/form/Form.tsx
- src/components/presentation/Presentation.tsx
- src/hooks/useNavigatePage.ts
- test/e2e/integration/frontend-test/navigation.ts
This fixes an issue where the screen reader focus is seemingly set at random when the user navigates a page. I have tested the changes with JAWS, NVDA and Orca. 
- fixes #1408 for `v4`
- Sprint board
- Labels
> fix: focus on main content of the form on page navigation

- src/features/options/useAllOptions.test.tsx
- src/features/options/useAllOptions.tsx
- src/features/options/useGetOptions.ts
`useGetOptions` will now log to dev-tools if the query fails. `useAllOptions` will show unknown error if any of its options fail to fetch, instead of loading indefinitely.
- closes #1834 
- Sprint board
- Labels
> Show unknown error on options not found

- src/features/applicationMetadata/appMetadataUtils.ts
- src/features/form/dynamics/DynamicsContext.tsx
- src/features/form/layoutSettings/LayoutSettingsContext.tsx
- src/features/form/rules/RulesContext.tsx
- src/queries/queries.ts
- src/utils/urls/appUrlHelper.test.ts
- src/utils/urls/appUrlHelper.ts
I found some more code related to non-layoutset apps, that we no longer support in v4. Cleaning it up.
- #1485
- Sprint board
- Labels
> Removing some more code related to non-layoutset apps

- .github/scripts/release.sh
Once we release v4.0.0, the schemas for v3 would have been overwritten. With this change, the schemas for v4 only live in the toolkits folder where they belong - but all apps upgraded to v4 now needs to use this new path for their `$schema`.
With this change, #1483 is no longer relevant, so I'm closing that PR.
- closes #1705
- Sprint board
- Labels
> Removing release-script functionality that overwrites JsonSchema files

- src/hooks/useNavigatePage.ts
- src/layout/Summary/SummaryComponent.tsx
A conflict emerged between #1875 and #1881, not an actual merge conflict, but the tests passed independently but not after merging the two.
- I combined the `useNavigateWithEffect` with the one I made for resetting `returnToView` into one.
- Also removed the await from the edit-button navigation, as it takes a long time for some components to time out, and then the "Back to summary" text takes a long time to get set. Seems to work consistently though, but can be done differently if necessary.
- #1875 
- #1881 
- …
> Fix conflict between #1875 and #1881

- test/e2e/integration/expression-validation-test/expression-validation.ts
- https://github.com/Altinn/app-lib-dotnet/pull/462
- Sprint board
- Labels
> Re-enable expression validation tests

- src/features/applicationMetadata/ApplicationMetadataProvider.tsx
This makes sure the version checker for backend required v8.0.0
- https://github.com/Altinn/altinn-studio-docs/pull/1438
- Sprint board
- Labels
> Marking 8.0.0 final as our dependency

- src/layout/RepeatingGroup/Summary/LargeGroupSummaryContainer.tsx
- src/layout/RepeatingGroup/Summary/SummaryRepeatingGroup.tsx
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1709903064872859
- Sprint board
- Labels
> Fix title in repeating group summary with reference to datamodel

- src/features/form/layout/PageNavigationContext.tsx
- src/hooks/useNavigatePage.ts
- src/layout/NavigationButtons/NavigationButtonsComponent.tsx
- src/layout/Summary/SummaryComponent.tsx
- src/layout/Summary/config.ts
- test/e2e/integration/frontend-test/navigation.ts
This PR adds the property `returnToSummaryButtonTitle` to a `Summary` component's `textResourceBindings`. The text specified in this property will be displayed on the "Next"-button in `NavigationButtons` component when `returnToView` is set.
- closes #1666 
- Sprint board
- Labels
> feat: add textResourceBinding.returnToSummaryButtonTitle for Summary component

- src/layout/NavigationButtons/NavigationButtonsComponent.tsx
- src/layout/Summary/config.ts
- test/e2e/integration/frontend-test/navigation.ts
This PR implements a feature which allows app owners to configure that the next button should show up when clicking change on a summary component.
- closes #1515 
- Sprint board
- Labels
> feat: add property nextButton to Summary component's display property

- .husky/pre-commit
- package.json
Simply following the release notes for husky v9: https://github.com/typicode/husky/releases/tag/v9.0.1
- #1966
- Sprint board
- Labels
> Fixes for husky upgrade to v9

- src/layout/NavigationButtons/NavigationButtonsComponent.module.css
- src/layout/NavigationButtons/NavigationButtonsComponent.tsx
This PR makes the "back" button have a secondary variant if there exists a "next" or a "backToSummary" button. 
- closes #1791 
- Sprint board
- Labels
> fix: make the back button be secondary variant if next button is present

- src/layout/Group/GroupComponent.tsx
Fallback to title for summaryTitle when used in summary. 
- closes #1973 
- Sprint board
- Labels
> Fallback to title for summary titles for group

- src/components/message/ErrorReport.test.tsx
- src/features/instance/ProcessNavigationContext.tsx
- src/features/validation/backendValidation/backendValidationUtils.ts
- src/features/validation/backendValidation/useBackendValidation.ts
- src/features/validation/callbacks/onFormSubmitValidation.ts
- src/features/validation/index.ts
- src/features/validation/selectors/taskErrors.ts
- src/features/validation/validationContext.tsx
- test/e2e/integration/frontend-test/validation.ts
- test/e2e/support/custom.ts
- test/e2e/support/global.d.ts
Validation issues returned by `process/next` no longer causes unknown error. Instead, they are shown to the user in the error report.
Additionally, we do not look for task validations in regular backend validations anymore, as it turns out task validation does not happen there anyway.
These changes were lifted from the [multiple-datamodels](https://github.com/Altinn/app-frontend-react/compare/main...multiple-datamodels) branch, as this issue was already fixed there.
- Support in Altinn …
> Fix "Unknown error" on submit when there are validation messages

- src/layout/CustomButton/CustomButtonComponent.tsx
Removes an unnecessary logging in the dev tools when an action from the custom button is failing. The stack trace gave little help when the code was minified anyways. 
- Sprint board
- Labels
> chore: remove unnecessary logging of error stack in custom button

- schemas/json/validation/validation.schema.v1.json
Error severities were changed for v4, the expression validation schema was not updated accordingly.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1715005031945139
> Fix severities in expression validation schema

- test/e2e/support/custom.ts
The cypress test for `components.ts` -> `is possible to upload and delete attachments ` keeps failing in GitHub. I was able to reproduce it locally by enabling network throttling. Cypress says the error is due to mixing up synchronous and asynchronous code, and this fixed it locally. I am not exactly sure how this custom cypress command works, so please correct me if this is wrong @olemartinorg 😅
> Fix cypress error caused by mixing up sync and async code

- src/layout/RepeatingGroup/RepeatingGroupContainer.tsx
- test/e2e/integration/frontend-test/group.ts
- closes #2004 
- Sprint board
- Labels
> refactor: never show add button when maxCount is reached

- src/layout/FileUpload/utils/fileEndings.test.ts
- src/layout/FileUpload/utils/fileEndings.ts
Nomalizing extensions to lower case is good practice. Here it helps the icon rendering understand which icon to use.
- closes #2150 
- Sprint board
- Labels
> fix: normalize file extensions to lower case

- test/e2e/integration/payment-test/payment.ts
Disable e2e test for payment until it can be fixed properly.
- Sprint board
- Labels
> Skip payment e2e test

- test/e2e/integration/frontend-test/tabs.ts
> FIx tabs cypress test to correspond with the code

- src/features/attachments/utils/mapping.ts
> fix: using overriden taskId to display attachments

- src/layout/Grid/GridSummary.module.css
Quick fix.
Before:
After:
- Sprint board
- Labels
> fixed line breaks

- src/features/instance/InstanceContext.tsx
- src/features/validation/backendValidation/backendValidationUtils.ts
- src/features/validation/backendValidation/useBackendValidation.ts
- src/features/validation/validationContext.tsx
- src/queries/appPrefetcher.ts
- src/queries/formPrefetcher.ts
Since #2108 will take a bit longer to finish I have transfered some bug-fixes here, so we can close the `dataElementValidatedAtWrongTask` issue. This should also fix the signing-tests so they are no longer flaky.
The changes are as follows:
- Check if the current data element is locked when determining whether we should fetch initial validations
- Prevent next process task from loading with stale instance data, this is a prerequesite for making the above fix work
- closes https://github.com/Altinn/app-frontend-react/issues/2091 …
> Fix DataElementValidatedAtWrongTask bug

- src/features/subFormData/useSubFormMutations.tsx
- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/SubForm/SubFormComponent.tsx
> Feature/subform jh.lek

- src/codegen/CodeGeneratorContext.ts
Smaller changes to make the file easier to read.
- Sprint board
- Labels
> smaller code changes to CodeGeneratorContext

- .husky/pre-commit-check-for-skipped-tests
- package.json
- test/e2e/integration/frontend-test/footer.ts
- test/e2e/integration/frontend-test/validation.ts
This also fixes our pre-commit hook so that it works on mac. This should prevent future accidents where tests are skipped.
- Sprint board
- Labels
> Re-adding skipped tests

- schemas/json/application/application-metadata.schema.v1.json
For https://github.com/Altinn/app-lib-dotnet/pull/671
and https://github.com/Altinn/altinn-storage/pull/426
- closes https://github.com/Altinn/app-lib-dotnet/issues/361
- Sprint board
- Labels
> Update applicationmetadata schema for manual instantiation

- src/components/form/Form.tsx
- src/components/label/Label.module.css
- src/components/label/Label.tsx
- src/components/label/LabelContent.module.css
- src/components/label/LabelContent.tsx
- src/components/message/ErrorReport.tsx
- src/components/presentation/Header.tsx
- src/features/pdf/PDFView.tsx
- src/layout/Accordion/Accordion.tsx
- src/layout/Address/AddressComponent.tsx
- src/layout/Cards/Cards.tsx
- src/layout/Image/ImageComponent.tsx
- src/layout/LikertItem/LikertItemComponent.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
- src/layout/RepeatingGroup/RepeatingGroupTableRow.tsx
- src/layout/RepeatingGroup/RepeatingGroupsEditContainer.tsx
- src/layout/Summary/SummaryComponent.tsx
- src/theme/altinnAppTheme.tsx
Fixes label spacings according to Designsystemet.
- Sprint board
- Labels
> Fix label spacings

- src/layout/Group/GroupSummary.tsx
Quick fix of missing group title.
- Sprint board
- Labels
> fixed missing group title

- package.json
- yarn.lock
> V3: Upgrade altinn-design-system to 0.30.2

- package.json
- src/layout/Map/MapComponent.tsx
- yarn.lock
> Upgrade altinn-design-system to 0.30.2

- src/components/label/LabelContent.tsx
- src/layout/InstanceInformation/InstanceInformationComponent.tsx
- src/utils/dateHelpers.ts
PDF was only showing date previously.
- closes #{1589}
- [] No testing done/necessary
- Sprint board
- Labels
> fix: added timestamp to pdf

- src/components/message/ErrorPaper.tsx
- src/components/wrappers/ProcessWrapper.tsx
- src/features/devtools/components/DevNavigationButtons/DevNavigationButtons.tsx
- src/features/devtools/components/ExpressionPlayground/ExpressionPlayground.tsx
- src/features/devtools/components/NodeInspector/NodeInspectorDataField.tsx
- src/features/devtools/components/NodeInspector/NodeInspectorDataModelBindings.tsx
- src/features/devtools/components/NodeInspector/NodeInspectorTextResourceBindings.tsx
- src/layout/FileUpload/FileUploadComponent.tsx
- src/layout/FileUpload/FileUploadTable/FileTableRow.tsx
- src/layout/Group/SummaryGroupComponent.tsx
- src/layout/Likert/Summary/LargeLikertSummaryContainer.tsx
- src/layout/Likert/Summary/LikertSummary.tsx
- src/layout/Payment/PaymentComponent.tsx
- src/layout/Payment/SummaryPaymentComponent.tsx
- src/layout/RepeatingGroup/Summary/SummaryRepeatingGroup.tsx
- src/layout/Summary2/SummaryComponent2/ComponentSummary.tsx
After we got `typescript-plugin-css-modules` in our `tsconfig.json`, WebStorm showed me lots of missing CSS classes being used in the 'Problems' tab. This was annoying, so I removed those references. 
- Sprint board
- Labels
> Removing undefined CSS classes

- src/layout/Grid/Grid.module.css
- src/layout/Grid/GridComponent.tsx
- test/e2e/integration/frontend-test/grid.ts
This fixes a bug introduced in v4.6.0
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1723704547806319?thread_ts=1723548623.978509&cid=C02EJ9HKQA3
- https://digdir.slack.com/archives/C076GU2QHCG/p1723704846314289
- Sprint board
- Labels
> Grid: Rendering header rows and non-header rows in order

- package.json
- src/layout/InstanceInformation/InstanceInformationComponent.tsx
- src/utils/dateHelpers.ts
- yarn.lock
Fixes broken timestamp in PDF.
I've added the moment-timezone dependency as discussed on slack as I think its the most pragmatic solution to get this done fast, this will be removed when we move to a new date library anyways.
Ref this conversation: https://altinn.slack.com/archives/C02EJ9HKQA3/p1723713014909379
- Sprint board
- Labels
> chore: fix broken timestamp in pdf

- src/language/sharedLanguage.ts
- src/layout/Paragraph/ParagraphComponent.test.tsx
- src/layout/Paragraph/ParagraphComponent.tsx
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1723722789648419?thread_ts=1723617628.368379&cid=C02EJ9HKQA3
- Sprint board
- Labels
> Fix inconsistent text styling

- src/layout/Summary2/CommonSummaryComponents/MultipleValueSummary.module.css
- src/layout/Summary2/CommonSummaryComponents/MultipleValueSummary.tsx
- src/layout/Summary2/CommonSummaryComponents/SingleValueSummary.module.css
- src/layout/Summary2/CommonSummaryComponents/SingleValueSummary.tsx
Fixes the styling of validation messages for `SingleValueSummary` and `MultipleValueSummary` to be in sync with the design.
Image showing the error exists in issue #2291 
Fixed:
- closes #2291 
- Sprint board
- Labels
> Fix summary2 validation message styling

- src/layout/FileUpload/FileUploadComponent.tsx
Ref this discussion: https://altinn.slack.com/archives/C02EJ9HKQA3/p1723633039289689
Previous solution did not work in complex mode.
- Sprint board
- Labels
> not wrapping dropzone in label to prevent unwanted filepicker in complex mode 

- src/features/applicationMetadata/types.ts
- src/features/instantiate/containers/PartySelection.tsx
- src/features/party/PartiesProvider.tsx
- src/features/party/partyProviderUtils.test.ts
- src/features/party/partyProviderUtils.ts
Makes party selection page simpler, easier to read and more React idiomatic.
- Sprint board
- Labels
> Make party selection page simpler

- src/__mocks__/getExpressionDataSourcesMock.ts
- src/features/expressions/expression-functions.ts
- src/utils/layout/useExpressionDataSources.ts
> Remove non-used expression data sources

- src/components/label/Label.tsx
- src/components/label/LabelContent.tsx
- src/layout/Address/AddressComponent.tsx
- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
- src/layout/FileUpload/AttachmentSummaryComponent2.tsx
- src/layout/Grid/GridComponent.tsx
- src/layout/Grid/GridSummary.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
- test/e2e/integration/component-library/address.ts
Fikser https://altinn.slack.com/archives/C02EJ9HKQA3/p1724673207635629
- Sprint board
- Labels
> Ensures id in labelcontent for correct label and description ids

- src/layout/Summary2/SummaryComponent2/SummaryComponent2.test.tsx
> Run all tests in SummaryComponent2.test.tsx

- src/layout/List/ListSummary.tsx
- src/layout/List/config.ts
- src/layout/List/index.tsx
- src/layout/Summary2/config.tsx
Add a summary 2 for List component
- closes #2388 
- Sprint board
- Labels
> Add summary2 for List component

- src/layout/Tabs/Tabs.module.css
- src/layout/Tabs/Tabs.tsx
The spacing between components that were rendered in a tab was not there. This PR adds spacing.
- Sprint board
- Labels
> Add spacing for components rendered in tabs

- src/features/form/dynamics/HiddenComponentsProvider.tsx
- src/features/formData/LegacyRules.ts
- src/test/allApps.ts
- src/utils/layout/all.test.tsx
This suddenly caused a harder crash after changes to this code in the performance branch. Logging errors about this so that app developers will notice.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1725884502222389?thread_ts=1725871420.505879&cid=C02EJ9HKQA3
- Sprint board
- Labels
> Preventing crash if function in ruleHandler is not found

- src/features/options/useGetOptions.ts
- test/e2e/integration/frontend-test/options.ts
We didn't have any tests for this, but obviously we should avoid removing stale values for hidden nodes (just like we do for `preselectedOptionIndex`).
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1725888977231759?thread_ts=1725871420.505879&cid=C02EJ9HKQA3
- Sprint board
- Labels
> Avoiding removing stale options for hidden nodes

- test/e2e/integration/subform-test/subform.ts
- test/e2e/pageobjects/app-frontend.ts
> add subform cypress tests

- src/layout/Summary2/CommonSummaryComponents/LayoutSetSummaryAccordion.module.css
- src/layout/Summary2/CommonSummaryComponents/LayoutSetSummaryAccordion.tsx
- src/layout/Summary2/SummaryComponent2/LayoutSetSummary.tsx
The before picture can be found in the bug report:  #2422
- The accordions where rendered in each their own accordion root element. This PR groups all the accordion items into the same accordion root as suggested by the design system documentation.
- Setting width to 100% solved the accordions not spanning the entire page.
- Also changed the typography of the accordion headings to use bold after consulting with designer @Edavda 
- Fixed grid not working and missing spacing within accordion items
- closes #2422
- …
> Fixed accordion view for Summary2 of a layoutset

- src/layout/Group/GroupSummary.module.css
- src/layout/Group/GroupSummary.tsx
- src/layout/RepeatingGroup/Summary2/RepeatingGroupSummary.module.css
- src/layout/RepeatingGroup/Summary2/RepeatingGroupSummary.tsx
- src/layout/Tabs/Tabs.module.css
- src/layout/Tabs/Tabs.tsx
Replace custom solutions for grid multiple places, some of which where not working as intended. By explicitly using the MUI grid component it will be simpler to find all the places in our code that are relevant when we eventually replace MUI grid with our own grid system.
Also removed description from the Group Summary component as the description is not supposed to be included for any of our summary components.
- Sprint board
- Labels
> Fix grid not working multiple places

- src/codegen/ComponentConfig.ts
- src/features/formData/FormDataWrite.tsx
- src/features/formData/jsonPatch/createPatch.test.ts
- src/features/formData/jsonPatch/createPatch.ts
- src/features/options/evalQueryParameters.ts
- src/features/options/useGetOptions.ts
- src/layout/LayoutComponent.tsx
- src/layout/Likert/Generator/LikertGeneratorChildren.tsx
- src/layout/Likert/Generator/LikertRowsPlugin.tsx
- src/layout/RepeatingGroup/useTableNodes.ts
- src/utils/layout/NodesContext.tsx
- src/utils/layout/generator/GeneratorContext.tsx
- src/utils/layout/generator/GeneratorStages.tsx
- src/utils/layout/generator/LayoutSetGenerator.tsx
- src/utils/layout/generator/NodeGenerator.tsx
- src/utils/layout/generator/NodeRepeatingChildren.tsx
- src/utils/layout/plugins/NodeDefPlugin.tsx
- src/utils/layout/plugins/RepeatingChildrenPlugin.tsx
- src/utils/layout/plugins/RepeatingChildrenStorePlugin.tsx
- src/utils/layout/types.ts
- test/e2e/integration/frontend-test/all-process-steps.ts
- test/e2e/integration/frontend-test/auto-save-behavior.ts
- test/e2e/integration/frontend-test/cards.ts
- test/e2e/integration/frontend-test/components.ts
- test/e2e/integration/frontend-test/dynamics.ts
- test/e2e/integration/frontend-test/number-text.ts
- test/e2e/integration/frontend-test/options.ts
- test/e2e/integration/frontend-test/validation.ts
- test/e2e/support/global.ts
- test/e2e/support/navigation.ts
Merges changes from `v4.8-patches` into `main`. This fixes some bugs, and fixes compatibility with the support for multiple datamodels.
- Sprint board
- Labels
> Merging `v4.8-patches`

- src/layout/Group/GroupSummary.tsx
- src/layout/Tabs/TabsSummary.tsx
Fixes console warnings for missing keys for the TabSummary component. 
Fixes console warning for use of `spacing` property for GridSummary component.
- Sprint board
- Labels
> Fix console warnings 

- test/e2e/integration/component-library/address.ts
- test/e2e/integration/component-library/dropdown.ts
- test/e2e/integration/component-library/fileupload.ts
- test/e2e/integration/component-library/input.ts
- test/e2e/integration/component-library/multiple-select.ts
- test/e2e/integration/component-library/summary-of-previous-task.ts
- test/e2e/integration/component-library/utils/fillAddressAndVerify.ts
- test/e2e/integration/component-library/utils/inputAndVerify.ts
- test/e2e/integration/component-library/utils/uploadFileAndVerify.ts
> fixed e2e test

- src/layout/Map/Summary2/MapSummary.module.css
- src/layout/Summary2/CommonSummaryComponents/MultipleValueSummary.module.css
- src/layout/Summary2/CommonSummaryComponents/SingleValueSummary.module.css
Avoiding components breaking over two pages in PDF.
- closes #{[issue number](https://github.com/Altinn/app-frontend-react/issues/2480)}
- Sprint board
- Labels
> added break-inside: avoid; to relevant components

- src/features/pdf/PdfView2.tsx
Fallback to summary1 is not needed as we have implemented all necessary summary components with Summary2.
This also fixes a bug where headers would be rendered in summary which it should not.
- Sprint board
- Labels
> removed summary1 fallback

- src/styles/shared.css
Before:
After:
- closes #2401 
- Sprint board
- Labels
> scaling down font size in pdf by overriding base font-size

- src/features/devtools/components/PDFPreviewButton/PDFGeneratorPreview.tsx
- src/layout/ActionButton/ActionButtonComponent.tsx
- src/layout/ActionButton/config.ts
Adds printPrevew option to action button that will show a pdf preview of your app.
- closes #1804
- Sprint board
- Labels
> feat: added print preview action type to action button

- src/components/presentation/Header.tsx
- src/layout/Group/GroupSummary.tsx
- closes #2346
- Sprint board
- Labels
> removed flex wrap from header

- test/e2e/integration/frontend-test/all-process-steps.ts
> fix for test

- src/layout/Grid/GridComponent.tsx
Swapped tbody to rows in Grid
- closes https://github.com/Altinn/app-frontend-react/issues/1851
- Sprint board
- Labels
> fix: swapped tbody to rows

- src/components/form/Fieldset.module.css
- src/components/form/Fieldset.tsx
- src/layout/Grid/GridComponent.tsx
Fix `Grid` not using language, and fix size of `Input` fields inside of a `Group`.
- closes #2531 
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1727942496577269
- Sprint board
- Labels
> Fix small visual bugs in grid and group

- src/layout/Button/ButtonComponent.tsx
Change ButtonComponent to call process next for any task type.
When I added a button to the layout set being used by my singing task the button did nothing. I expected it to call process next.
Let me know if this can't be solved this way.
- #2501 
- Sprint board
- Labels
> Change ButtonComponent to call process next for any task type.

- package.json
- yarn.lock
Contains fix for combobox aria-controls
- closes #2517 
- Sprint board
- Labels
> Udate designsystem react to 0.63.1

- src/components/form/Description.tsx
- src/features/dataLists/useDataListQuery.tsx
- src/layout/List/ListComponent.module.css
- src/layout/List/ListComponent.tsx
- test/e2e/integration/frontend-test/list-component.ts
- test/e2e/integration/frontend-test/mobile.ts
- test/e2e/pageobjects/datalist.ts
- test/e2e/support/custom.ts
> Refactors legacy listcomponent to new designsystemet

- src/features/formData/FormDataWrite.tsx
- src/features/formData/types.ts
- https://github.com/Altinn/app-lib-dotnet/pull/835
- Sprint board
- Labels
> Add instance to single-patch response

- src/layout/Datepicker/DatePickerCalendar.tsx
- src/layout/Datepicker/DatepickerComponent.test.tsx
Fix error in datepicker test when trying to select the default selected day
- Sprint board
- Labels
> Fix error when test trying to click on default selected date.

- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- Fix broken link to Single services and roles page in error page. https://altinn.no/hjelp/profil/roller-og-rettigheter/ does not exist anymore, should be https://altinn.no/hjelp/profil/enkelttjenester-og-roller/
- Sprint board
- Labels
> Fix broken link to roles on error page

- src/features/devtools/components/PDFPreviewButton/PDFGeneratorPreview.tsx
- src/layout/ActionButton/ActionButtonComponent.tsx
- src/layout/ActionButton/config.ts
Reverts Altinn/app-frontend-react#2489
see https://github.com/Altinn/app-frontend-react/pull/2489#issuecomment-2426253555
> Revert "feat: added print preview action type to action button"

- .github/workflows/check-label-added.yml
> Created github action to check that a label has been added before merge

- src/layout/PaymentDetails/config.ts
> Feature/PaymentDetails - set renderInCards: true

- src/components/wrappers/ProcessWrapper.tsx
See issue: https://github.com/Altinn/app-frontend-react/issues/2613
- closes https://github.com/Altinn/app-frontend-react/issues/2613
- Sprint board
- Labels
> hiding button

- src/layout/Likert/Summary2/LikertSummary.tsx
- src/layout/Summary2/SummaryComponent2/ComponentSummary.tsx
- src/layout/Summary2/SummaryComponent2/SummaryComponent2.test.tsx
- src/layout/Summary2/config.tsx
Summary now supports compact view.
- closes [#{issue number}](https://github.com/Altinn/app-frontend-react/issues/2623)
- Sprint board
- Labels
> Feat/2623 isCompact support for summary2

- src/layout/List/ListComponent.tsx
Before the rewrite, pagination was only rendered if explicitly configured. Restoring this behavior.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1729680724828269?thread_ts=1729512493.045959&cid=C02EJ9HKQA3
- #2373 
- Sprint board
- Labels
> Don't render pagination in `List` without explicit config

- src/components/wrappers/ProcessWrapper.tsx
- src/features/instance/ProcessContext.tsx
- src/features/instance/ProcessNavigationContext.tsx
- src/hooks/useNavigatePage.ts
Removes zustand in process context because it is duplicating tanstack behavior. 
- Sprint board
- Labels
> Refactor ProcessContext

- src/App.tsx
- src/components/wrappers/ProcessWrapper.tsx
- src/features/entrypoint/Entrypoint.tsx
- src/layout/Subform/SubformWrapper.tsx
Refactors routes to be more explicit and avoid components like `ProcessWrapperWrapper`. Paves way for further cleanup later, hopefully.
Can be read commit for commit.
- Sprint board
- Labels
> Refactor routes

- package.json
- src/layout/GenericComponent.tsx
- src/layout/Likert/Generator/LikertGeneratorChildren.tsx
- src/layout/RepeatingGroup/Pagination/RepeatingGroupPagination.tsx
- src/layout/RepeatingGroup/Table/RepeatingGroupTableRow.tsx
- src/layout/Summary/SummaryComponent.tsx
- src/utils/layout/generator/NodeRepeatingChildren.tsx
- yarn.lock
`eslint-plugin-react-hooks` doesn't allow `_` at the start of a component's name. Refactored to comply.  
- Sprint board
- Labels
> updates eslint-plugin-react-hooks and fixes errors

- src/features/formData/FormDataWrite.tsx
- src/features/instantiate/InstantiationContext.tsx
- src/queries/queries.ts
- src/utils/urls/appUrlHelper.test.ts
- src/utils/urls/appUrlHelper.ts
- test/e2e/integration/frontend-test/party-selection.ts
- test/e2e/integration/multiple-datamodels-test/readonly.ts
- test/e2e/integration/multiple-datamodels-test/saving.ts
- test/e2e/support/custom.ts
Adds the current language to the multi-patch and instantiation URLs.
- closes #2636
- Sprint board
- Labels
> Add language to multipatch and instantiation

- src/layout/Subform/Summary/SubformSummaryComponent2.tsx
- src/utils/layout/NodesContext.tsx
- test/e2e/integration/subform-test/subform.ts
> Fix PDF generation when using subform

- src/language/texts/nb.ts
Fix a spelling mistake in payment receipt
"Kontakte-post" --> "Kontakt-e-post"
- Sprint board
- Labels
> Fix spelling mistake in payment receipt

- src/__mocks__/getApplicationMetadataMock.ts
- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/Subform/SubformValidator.tsx
- src/types/shared.ts
Frontend implementation of issue https://github.com/Altinn/app-frontend-react/issues/2569
- https://github.com/Altinn/app-frontend-react/issues/2569
- Sprint board
- Labels
> Remove `ApplicationLogic.AllowInSubform` property

- src/core/structures/ShallowArrayMap.test.ts
- src/core/structures/ShallowArrayMap.ts
- src/hooks/delayedSelectors.ts
It turns out that delayed selectors often don't ever select anything, and with thousands of components this leads to a lot of overhead. This change makes unused selectors essentially free by not creating the SelectorMap or subscribing to the store until a selector is used.
**Edit**: Also updated `ShallowArrayMap` to store indexes to an array instead of the values directly, this makes iterating over the values much faster as I can just return the array directly instead of traversing the maps …
> Performance: Make delayed selector much cheaper

- .github/workflows/release.yml
- .github/workflows/revert.yml
Matching PR for https://github.com/Altinn/app-lib-dotnet/pull/881
- N/A
- Sprint board
- Labels
> Associate test and staging envs in pipeline

- src/layout/Checkboxes/__snapshots__/MultipleChoiceSummary.test.tsx.snap
- src/layout/Group/__snapshots__/SummaryGroupComponent.test.tsx.snap
- src/layout/RepeatingGroup/Summary/__snapshots__/SummaryRepeatingGroup.test.tsx.snap
- src/utils/layout/generator/LayoutSetGenerator.tsx
- src/utils/layout/generator/NodeRepeatingChildren.tsx
React's `getHostSibling` function can be very slow for renderless components, this will make sure it finds the sibling immediately by adding a `HostText` fiber-node directly below. The space will be added to the DOM, but should not be visible. See https://github.com/facebook/react/blob/ed15d5007ca7ee4d61294c741ce3e858d3c1d461/packages/react-reconciler/src/ReactFiberCommitHostEffects.js#L222-L226
**Edit**: Turns out the space will be added to the DOM, but they are at least not visible. I could not find a better or less hacky method of solving this issue.
- https://digdir.slack.com/archives/C076GU2QHCG/p1730812212231269?thread_ts=1730710072.922749&cid=C076GU2QHCG …
> Performance: Speed up `getHostSibling` for repeating group row generation

- .github/workflows/cypress.yml
> Upgrade Cypress GitHub Action

- .github/workflows/release.yml
- .github/workflows/revert.yml
- .github/workflows/test/release-preview-invalid-suffix.json
- .github/workflows/test/release-preview-success.json
- .github/workflows/test/release-rc-invalid-suffix.json
- .github/workflows/test/release-rc-success.json
- .github/workflows/test/release-stable-invalid-prerelease-value.json
- .github/workflows/test/release-stable-invalid-suffix.json
- .github/workflows/test/release-stable-missing-v.json
- .github/workflows/test/release-stable-success.json
Validation step related to https://github.com/Altinn/app-frontend-react/pull/2700
- N/A
- Sprint board
- Labels
> Steps to validate tag name in pipelines

- src/features/expressions/shared-tests/functions/displayValue/date.json
- src/features/expressions/shared-tests/functions/displayValue/number.json
- src/features/expressions/shared-tests/functions/displayValue/text.json
- src/layout/Date/index.tsx
- src/layout/Number/index.tsx
- src/layout/RepeatingGroup/Summary2/RepeatingGroupSummary.tsx
- src/layout/RepeatingGroup/Summary2/RepeatingGroupTableSummary/RepeatingGroupTableSummary.module.css
- src/layout/RepeatingGroup/Summary2/RepeatingGroupTableSummary/RepeatingGroupTableSummary.tsx
- src/layout/RepeatingGroup/Table/RepeatingGroupTableTitle.tsx
- src/layout/RepeatingGroup/config.ts
- src/layout/RepeatingGroup/index.tsx
- src/layout/RepeatingGroup/useTableNodes.ts
- src/layout/Summary2/CommonSummaryComponents/EditButton.tsx
- src/layout/Text/index.tsx
- test/e2e/integration/component-library/repeating-group.ts
Adds a table summary for repeating group.
Enables the use of Text, Number and Date components in Repeating group.
- Sprint board
- Labels
> Repeating group summary2 table mode

- src/layout/Map/Map.tsx
- src/layout/Map/config.ts
Added an optional property for the map-component to be able to configure and use WMS-type tilelayers in the map.
Exposed properties relevant to wms-type tilelayers for configuration, and given them relevant descriptions and defaults.
- closes #2455
- Sprint board
- Labels
org/dmf
kind/product-feature
> Added support for wms-type tilelayers in map-component

- src/components/organisms/AltinnAppHeaderMenu.module.css
- src/components/organisms/AltinnAppHeaderMenu.tsx
- src/layout/Checkboxes/__snapshots__/MultipleChoiceSummary.test.tsx.snap
- test/e2e/integration/stateless-app/stateless.ts
- test/e2e/pageobjects/app-frontend.ts
Refactors logout popover from using MUI components to using Designsystemet Popover component. This also removes console error from MUI.
- Sprint board
- Labels
> Fix distracting MUI console error

- src/features/validation/ValidationPlugin.test.tsx
> maybe fix flaky test

- .github/workflows/cypress.yml
Percy wasn't running on main because of faulty check. No wonder no screenshots were updated 🙈 
- Sprint board
- Labels
> Run Percy on main branch

- src/app-components/Label/Label.module.css
- src/app-components/Label/Label.tsx
- src/components/form/Fieldset.tsx
- src/components/form/OptionalIndicator.tsx
- src/components/form/caption/Caption.tsx
- src/components/label/Label.tsx
- src/components/label/LabelContent.tsx
- src/layout/Address/AddressComponent.tsx
- src/layout/Datepicker/DatepickerComponent.tsx
- src/layout/Dropdown/DropdownComponent.tsx
- src/layout/GenericComponent.tsx
- src/layout/Input/InputComponent.tsx
- src/layout/Likert/LikertComponent.tsx
- src/layout/List/ListComponent.tsx
- src/layout/MultipleSelect/MultipleSelectComponent.tsx
- src/layout/TextArea/TextAreaComponent.tsx
- src/utils/layout/useLabel.tsx
- test/e2e/integration/frontend-test/group.ts
- test/e2e/integration/frontend-test/mobile.ts
- test/e2e/integration/frontend-test/validation.ts
Extracts label version of the label component into a dumb version. This is needed for the PersonLookup component.
The plan is to extract all versions of the Label component into their own dumb components.
- Sprint board
- Labels
> Extract label type from label

- src/layout/Address/AddressComponent.tsx
- test/e2e/integration/component-library/address.ts
- closes #2520 
- Sprint board
- Labels
> Fixes address padding and validation error positions

- package.json
- yarn.lock
After the new datepicker was introduced, this dependency is no longer needed
- closes #146
- Sprint board
- Labels
> Removing dep @material-ui/pickers

- src/app-components/Panel/Panel.tsx
- src/layout/Panel/PanelComponent.tsx
This is a reversal of a breaking change, although the use case in which it breaks is strange. I have added the bug label as none other seems fitting.
Link to relevant support thread: https://altinn.slack.com/archives/C02EJ9HKQA3/p1733134009118219
- Sprint board
- Labels
> hotfix-header-uten-innhold

- src/App.tsx
- src/components/wrappers/ProcessWrapper.tsx
- src/features/instance/ProcessContext.tsx
- src/features/receipt/ReceiptContainer.test.tsx
- src/features/receipt/ReceiptContainer.tsx
- src/index.tsx
- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/index.ts
- src/types/index.ts
- src/utils/formLayout.ts
- test/e2e/integration/frontend-test/custom-confirm.ts
Smaller changes to more streamline and more easily see what's going on.
- Sprint board
- Labels
> Update task resolution code

- src/layout/List/ListComponent.module.css
Before:
After:
- closes [#{issue number}](https://github.com/Altinn/app-frontend-react/issues/2746)
- Sprint board
- Labels
> removed table-layout fixed

- src/layout/RepeatingGroup/Summary2/RepeatingGroupTableSummary/RepeatingGroupTableSummary.tsx
- test/e2e/integration/component-library/repeating-group.ts
Fixes an issue where every row used the same node data. Retrieving nodes per row using the index solved the issue.
- Sprint board
- Labels
> Fix repeating group table summary

- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
> Adds missing error messages for organisation lookup

- src/layout/OrganisationLookup/OrganisationLookupComponent.tsx
Org name was cleared between renders because of local state. Using saved value in datamodel instead. 
- Sprint board
- Labels
> Shows saved orgname instead of local state

- src/layout/OrganisationLookup/index.tsx
- src/layout/PersonLookup/index.tsx
When the type for org nr or ssn in the data model is set at a number, leading zeros are being removed on save. Validates type and returns error to ensure data type is set to string.
- closes #2809 
- Sprint board
- Labels
> Validate org and person data model binding types

- webpack.common.js
New Webpack and/or Axios results in errors when Webpack is trying to resolve Axios dependency. Might be because the default in Webpack is not aligned with Axios any more and thus doesn't manage to resolve it correctly. Could be that it would've worked if we were using ESM, but to refactor to ESM from CommonJS is a bigger job. 
- Sprint board
- Labels
> Hotfix for resolving axios correctly in webpack

- src/layout/OrganisationLookup/OrganisationLookupComponent.module.css
- src/layout/OrganisationLookup/OrganisationLookupComponent.tsx
Added paragraph for consistent font size (differed depending on where the component was used) and added a tiny bit of margin top to the org name.
- Sprint board
- Labels
> Organisation Lookup minor styling fixes

- src/layout/OrganisationLookup/index.tsx
- src/layout/PersonLookup/index.tsx
> fix pdf generation issue with lookup components

- .github/workflows/unit-tests.yml
The `--runInBand` flag to jest makes sure tests are run serially. Can be useful for debugging, but maybe not for running tests on every PR 🤷‍♀️  Seems like it is saving around 4 min.
- Sprint board
- Labels
> Run jest tests concurrently

- test/e2e/support/index.ts
> Reset command timeout before each

- src/features/useCurrentPartyRoles.ts
disabling roles api call if api version is too low
- closes https://github.com/Altinn/app-frontend-react/issues/2089
- Sprint board
- Labels
> disabling roles api call if api version is too low

- eslint.config.mjs
- src/components/PDFGeneratorPreview/PDFGeneratorPreview.tsx
- src/features/devtools/components/DevToolsLogs/DevToolsLogs.tsx
- src/features/devtools/components/FeatureToggles/FeatureToggles.tsx
- src/layout/GenericComponent.tsx
Fixes eslint not catching missing key in component list if using fragment and key after spread operator.
- Sprint board
- Labels
> Updates eslint react key rule and fixes errors

- src/layout/Group/GroupComponent.tsx
- src/styles/shared.css
Updates pdf font sizes according to https://github.com/Altinn/app-frontend-react/issues/2401
- Sprint board
- Labels
> updates font sizes for print and group component heading

- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/FileUpload/DropZone/DropzoneComponent.tsx
- src/layout/FileUpload/FileUploadTable/FileTableRow.tsx
- src/layout/SigneeList/SigneeListComponent.test.tsx
- src/layout/SigneeList/SigneeListComponent.tsx
- src/layout/SigneeList/SigneeListError.tsx
- src/layout/SigningDocumentList/SigningDocumentListComponent.test.tsx
- src/layout/SigningDocumentList/SigningDocumentListComponent.tsx
- src/layout/SigningDocumentList/SigningDocumentListError.tsx
- src/layout/SigningDocumentList/api.ts
- src/layout/SigningDocumentList/config.ts
- src/layout/SigningDocumentList/index.tsx
- src/utils/attachmentsUtils.ts
- test/e2e/integration/frontend-test/attachments-in-group.ts
A list over documents to sign in signing.
Should only work in a `signing` task and only show documents that are configured to be signed in `process.bpmn`. 
E.g. 
```bpmn
<altinn:signatureConfig>
<altinn:dataTypesToSign>
<altinn:dataType>ref-data-as-pdf</altinn:dataType>
</altinn:dataTypesToSign>
<altinn:signatureDataType>signatures-founders</altinn:signatureDataType>
<altinn:signeeStatesDataTypeId>signeeStates-founders</altinn:signeeStatesDataTypeId>
<altinn:signeeProviderId>founders</altinn:signeeProviderId>
<altinn:signatureConfig>
```
- closes #2801  …
> Documents to Sign List

- src/features/useCurrentPartyRoles.ts
Updates queryKey for fetchCurrentPartyRoles to properly refetch roles when instance or party changes.
- closes https://github.com/Altinn/app-frontend-react/issues/2864
- Sprint board
- Labels
> refetching roles when party and instance changes

- test/e2e/integration/frontend-test/pdf.ts
Trying to get more info out of flaky PDF tests when they fail
- N/A
- Sprint board
- Labels
> More info in assertion failure output for pdf test

- test/e2e/integration/frontend-test/pdf.ts
> updates way of intercepting requests

- src/styles/shared.css
Resets base font size in PDF to 10px not to break any existing PDFs.
- Sprint board
- Labels
> Sets base font size for pdf to 10px

- src/features/validation/schemaValidation/SchemaValidation.tsx
- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/Datepicker/index.tsx
For some reason Ajv will always report an error for `formatMinimum` etc. even if the value violates the format itself. We only want this error if the value is valid according to the `format`, but is outside of the range specified. The incorrect cases should be ignored now.
Added language resouces for `formatMinimum` and `formatMaximum`.
Filter out `formatMinimum` etc. for Datepicker if a similar restriction is also defined on the component to avoid multiple messages for the same thing.
- closes #2319 
- Support in …
> Fix `formatMinimum` and `formatMaximum` behavior

- src/app-components/Label/types.ts
- src/layout/OrganisationLookup/OrganisationLookupComponent.tsx
- src/layout/PersonLookup/PersonLookupComponent.tsx
Setting display `grid` with `className` does not work with the new `Flex` component, so used a div instead. 
Also removed some unused types from mui i saw.
- Sprint board
- Labels
> fixes layout for person and org lookup components

- src/components/message/ErrorPaper.module.css
- src/index.css
- src/layout/Checkboxes/CheckboxesContainerComponent.module.css
- test/e2e/integration/frontend-test/party-selection.ts
Fixed some typos and string values in css.
- Sprint board
- Labels
> Fixed some typos and string values in css.

- src/app-components/Label/Label.module.css
- src/layout/ComponentStructureWrapper.tsx
InnerGrid is overwritten by xs:12 if innergrid contains xs. Made a condition to only overwrite if innergrid doesn't have xs.
Added an extra fix for the "Hjelpetekst" bubble size.
- closes #2912 
- closes #2470 
- Sprint board
- Labels
> InnerGrid is overwritten by xs:12 in ComponentStructoreWrapper

- src/layout/SigningDocumentList/SigningDocumentListComponent.tsx
- src/layout/SigningDocumentList/api.ts
Previously filtered out datamodel xml if listed in `dataTypesToSign`, but should not filter out any documents because this is what the user is actually signing.
- Sprint board
- Labels
> Removes documents to sign filter

- renovate.json
This should make sure we don't get spammed with v3 PRs from renovate. There's barely activity in that branch any longer, so maintaining deps is less of a priority now.
- https://digdir.slack.com/archives/C076GU2QHCG/p1724329831269319
- Sprint board
- Labels
> Dropping dependency updates for v3

- src/layout/Summary/SummaryComponent.tsx
> Fixes unique key console error for summartyerrors

- src/features/validation/backendValidation/BackendValidation.tsx
- src/features/validation/backendValidation/backendValidationQuery.ts
- src/features/validation/backendValidation/backendValidationUtils.ts
- src/features/validation/callbacks/onPageNavigationValidation.ts
- src/features/validation/validationContext.tsx
- src/hooks/useNavigatePage.ts
Refactors to more easily follow logic. No functional changes. 
- Sprint board
- Labels
> Refactors backend validation query function file for readability

- src/layout/CustomButton/CustomButtonComponent.tsx
- src/queries/queries.ts
Added missing language in doPerformAction in CustomButtonComponent.tsx.
- closes https://github.com/Altinn/app-lib-dotnet/issues/927
- closes https://github.com/Altinn/app-frontend-react/issues/2759
- Sprint board
- Labels
> Added language to doPerformAction in CustomButtonComponent.tsx

- .github/workflows/pr-actions.yml
Matching changes to https://github.com/Altinn/app-lib-dotnet/pull/1044
- https://github.com/Altinn/app-lib-dotnet/pull/1044
- Sprint board
- Labels
> Improve PR release workflow

- .github/workflows/pr-actions.yml
Followup to https://github.com/Altinn/app-frontend-react/pull/2927
Need to string the `v` before constructing the links in the comment
- https://github.com/Altinn/app-frontend-react/pull/2927
- Sprint board
- Labels
> Remove 'v' prefix in PR release url

- src/features/validation/backendValidation/backendValidationQuery.ts
- src/layout/SigningStatusPanel/PanelSubmit.tsx
- src/layout/SigningStatusPanel/SigningStatusPanelComponent.tsx
Runs backend validation for signing state when signee list has changed.
- Sprint board
- Labels
> Signing backend validation

- src/layout/Dropdown/DropdownComponent.tsx
- src/layout/FileUploadWithTag/EditWindowComponent.tsx
- src/layout/MultipleSelect/MultipleSelectComponent.tsx
- src/utils/options.ts
- closes #2506 
- Sprint board
- Labels
> Improved search in Dropdown and MultipleSelect

- src/layout/RepeatingGroup/Container/RepeatingGroupContainer.tsx
Slack: https://altinn.slack.com/archives/C02EJ9HKQA3/p1737548935921869
Seems like the design system `FieldSet` has a very aggressive default `size: md`. Form components will prefer the size from the field set context over its own props, so even if you don't explicitly pass a `size` to the field set the default `md` will override any props in components under it.
This will apparently not be the case in the `next` design-system
- Sprint board
- Labels
> Fix Input size in repeating group with mode showAll

- src/layout/SigningStatusPanel/PanelAwaitingOtherSignatures.tsx
- src/layout/SigningStatusPanel/PanelNoActionRequired.tsx
- src/layout/SigningStatusPanel/SigningStatusPanelComponent.tsx
- Show signing button regardless of if the current user is in the original signee list or not as long as they have sign rights and have not already signed. 
- Also did some minor cleanup of props.
- Sprint board
- Labels
> Show signing button if sign access

- src/__mocks__/getPartyMock.ts
- src/features/party/partyProviderUtils.test.ts
- src/features/party/partyProviderUtils.ts
- src/types/shared.ts
Duplicating what's being done on the backend, essentially: https://github.com/Altinn/app-lib-dotnet/blob/main/src/Altinn.App.Core/Helpers/InstantiationHelper.cs
- closes #2973
- https://digdir.slack.com/archives/C079ZFUSFMW/p1738750152285599
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1738744972285099
- https://digdir.slack.com/archives/C0760NPT2BE/p1738754176145969
- Sprint board
- Labels
> Refactoring the party filter, properly support subunits and bankruptcy estates

- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/PersonLookup/validation.ts
- test/e2e/integration/component-library/personlookup.ts
> Reduces required length of last name in person lookup from 2 to 1

- src/features/formData/FormDataWrite.tsx
- src/queries/queries.ts
- src/utils/urls/appUrlHelper.ts
- closes https://github.com/Altinn/app-frontend-react/issues/2065
- Sprint board
- Labels
> including current party in headers for POST stateless/data

- src/features/validation/backendValidation/backendValidationQuery.ts
In #2922 the refetch method was changed to use a `useQuery` for the backend validation query and simply returns the `refetch` method. However, this query was not disabled so it would cause an automatic fetch even when we should not fetch backend validations. When in the receipt, fetching validation fails and would log an error to dev tools. I simply added `enabled: false` on the query in this method, and I tested triggering a refetch using this disabled query still works. This should also be covered by the subform validation tests. The percy snapshots now show that we no longer get an error in dev tools when entering receipt.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1739193148883319 …
> Fix validation exception in receipt

- src/App.tsx
- src/components/form/Form.tsx
- src/features/instance/InstanceContext.tsx
- src/features/instance/ProcessContext.tsx
- src/features/payment/PaymentProvider.tsx
- src/features/routing/AppRoutingContext.tsx
- src/features/useCurrentPartyRoles.ts
- src/hooks/useNavigatePage.ts
- src/layout/CustomButton/CustomButtonComponent.tsx
- src/queries/appPrefetcher.ts
- src/test/renderWithProviders.tsx
- src/test/routerUtils.tsx
Renaming param to avoid future mistakes. 
- Sprint board
- Labels
> renames partyId param to instanceOwnerPartyId

- src/layout/SigneeList/api.ts
- src/layout/SigningStatusPanel/PanelAwaitingCurrentUserSignature.tsx
- src/layout/SigningStatusPanel/PanelSigning.tsx
- src/layout/SigningStatusPanel/PanelSubmit.tsx
- Prevents double clicking for actions
- Always refetches signee list on mount to avoid stale state
- Sprint board
- Labels
> Signing CTA fixes

- src/app-components/Table/Table.tsx
- src/layout/SigningDocumentList/SigningDocumentListComponent.tsx
- src/layout/SigningStatusPanel/PanelAwaitingCurrentUserSignature.tsx
- src/layout/SigningStatusPanel/PanelSigning.tsx
- src/layout/SigningStatusPanel/PanelSubmit.tsx
- src/layout/SigningStatusPanel/SigningStatusPanel.module.css
- src/layout/SigningStatusPanel/SigningStatusPanelComponent.test.tsx
- src/layout/SigningStatusPanel/SigningStatusPanelComponent.tsx
- src/layout/SigningStatusPanel/SubmitSigningButton.tsx
Shows submit button in awaiting current user signature panel if:
- current user can write, and
- there are no missing signatures (i.e. the validator validates ok)
- Sprint board
- Labels
> Fix missing submit button when user can sign, but isn't required

- src/features/devtools/DevTools.module.css
- src/features/devtools/DevToolsPanel.tsx
- src/features/devtools/components/LayoutInspector/LayoutInspector.module.css
- src/features/devtools/components/LayoutInspector/LayoutInspector.tsx
- src/features/devtools/components/NodeInspector/NodeInspector.tsx
Small tweaks to make close button less annoying on smaller screens
> make dev tools close button less annoying

- src/features/payment/usePerformPaymentMutation.ts
- src/layout/CustomButton/CustomButtonComponent.tsx
- src/layout/SigneeList/api.ts
- src/layout/SigningStatusPanel/PanelAwaitingCurrentUserSignature.tsx
- src/queries/queries.ts
> Invalidate all signing querie on serveraction sign

- src/features/pdf/PdfView2.tsx
- test/e2e/integration/frontend-test/pdf.ts
- test/e2e/support/global.ts
- test/e2e/support/index.ts
This fix doesn't directly _solve_ the issue from https://github.com/Altinn/app-frontend-react/issues/3059, but it prevents this particular configuration error from happening again in the future.
- Closes https://github.com/Altinn/app-frontend-react/issues/3059
- Reverts https://github.com/Altinn/app-frontend-react/pull/3009
- Sprint board
- Labels
> Validate that custom PDF layout exists

- src/layout/Cards/Cards.module.css
- src/layout/Cards/Cards.tsx
Adds styling to card media to make the element float correctly for both top and bottom placement. 
- Sprint board
- Labels
> Makes card media float correctly

- src/features/pdf/PdfView2.tsx
- test/e2e/integration/frontend-test/pdf.ts
- test/e2e/support/global.ts
- test/e2e/support/index.ts
> validate that custom pdf layout exists (#3063)

- src/layout/Divider/DividerComponent.tsx
- src/layout/Divider/config.ts
- src/layout/Divider/index.tsx
- src/layout/Summary2/config.tsx
- test/e2e/integration/component-library/divider.ts
Adds a divider component that can be placed between other components.
```
{
"id": "DividerPage-Divider",
"type": "Divider"
}
```
- closes #3011 
- Sprint board
- Labels
> Add Divider component

- src/features/processEnd/confirm/containers/ConfirmPage.tsx
- src/features/receipt/ReceiptContainer.tsx
- src/layout/AttachmentList/AttachmentListComponent.tsx
- src/utils/attachmentsUtils.test.ts
- src/utils/attachmentsUtils.ts
Filters "app:owned" data elements so that they are not shown in the frontend. They will still be available in the data sent from the API. Do we want that?
- closes #3111 
- Sprint board
- Labels
> Filter app:owned data elements from shown attachments in local receipt

- src/app-components/Datepicker/DatePickerInput.tsx
- src/app-components/DynamicForm/DynamicForm.tsx
- src/features/expressions/expression-functions.ts
- src/layout/Date/DateComponent.tsx
- src/layout/Datepicker/DatepickerComponent.tsx
- src/layout/Datepicker/useDatepickerValidation.ts
- src/layout/InstanceInformation/InstanceInformationComponent.tsx
- src/layout/Payment/PaymentReceiptDetails/PaymentReceiptDetails.tsx
- src/layout/SigneeList/SigneeListSummary.tsx
- src/utils/dateUtils.test.ts
- src/utils/dateUtils.ts
Converts signing timestamp to Europe/Oslo time. 
- closes #3106 
- Sprint board
- Labels
> converts timestamp string to zoned date and formats

- src/layout/Group/SummaryGroupComponent.tsx
I've been looking through older issues to try to clean up some of them, and this looked like it was just about as easy to fix as it was to reproduce. 
Before:
After:
- closes #2034
- Sprint board
- Labels
> Fixing summary title variables lookup by referencing the target node

- src/components/label/LabelContent.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
- src/utils/layout/useLabel.tsx
- test/e2e/integration/frontend-test/pdf.ts
Multiple labels seemed to have broken support for markdown. This worked in `v4.5.0`, so it was an unintended breaking change when rewriting the labels functionality. Opening PR now to see how much Percy will find, and I'll focus on adding better tests for this later (after some meetings). 
- closes #2362
- Sprint board
- Labels
> Fixing support for markdown in multiple labels

- package.json
- src/components/form/MessageBanner.module.css
- src/components/form/MessageBanner.test.tsx
- src/features/instantiate/containers/PartySelection.module.css
- src/features/instantiate/containers/PartySelection.tsx
- src/index.css
- src/index.tsx
- yarn.lock
We were almost there -- this should remove all the rest of the old design system.
- closes #2788
- Sprint board
- Labels
> Removing old design system

- src/layout/Accordion/config.ts
- src/layout/AccordionGroup/config.ts
- src/layout/AttachmentList/config.ts
- src/layout/FileUpload/config.ts
- src/layout/FileUploadWithTag/config.ts
- src/layout/Grid/config.ts
- src/layout/InstanceInformation/config.ts
- src/layout/Likert/config.ts
- src/layout/List/config.ts
- src/layout/Map/config.ts
- src/layout/OrganisationLookup/config.ts
- src/layout/PersonLookup/config.ts
- src/layout/RepeatingGroup/config.ts
- src/layout/Subform/config.ts
- src/layout/Summary2/config.tsx
As in the example in #2795, Cards can also be used as a near-full-width component, so there's no good reason for limiting large components from being rendered inside it. Opening up for more components to be rendered inside cards with this PR.
- closes #2795
- Sprint board
- Labels
> Allowing more components to be rendered in cards

- src/layout/RepeatingGroup/Summary2/RepeatingGroupSummary.tsx
- src/layout/RepeatingGroup/Summary2/RepeatingGroupTableSummary/RepeatingGroupTableSummary.tsx
Summary2 title does not have translation support 
- Sprint board
- Labels
> Support translation for summary2 title

- src/layout/SimpleTable/ApiTable.tsx
Make use of path property to filter to the correct data on externalApi on SimpleTable
- closes #3131 
- Sprint board
- Labels
> ExternalApi on SimpleTable does not support path parameter

- src/features/validation/expressionValidation/ExpressionValidation.tsx
- src/layout/RepeatingGroup/Summary2/RepeatingGroupSummary.tsx
- src/layout/RepeatingGroup/Summary2/RepeatingGroupTableSummary/RepeatingGroupTableSummary.tsx
- src/layout/SimpleTable/ApiTable.tsx
> Cherry-picks for v4.18.1

- src/features/validation/expressionValidation/shared-expression-validation-tests/many-errors-direct.json
- src/features/validation/expressionValidation/shared-expression-validation-tests/nested-repeating.json
- src/features/validation/expressionValidation/shared-expression-validation-tests/override.json
- src/features/validation/expressionValidation/shared-expression-validation-tests/repeating-direct.json
- src/features/validation/expressionValidation/shared-expression-validation-tests/repeating.json
- src/features/validation/expressionValidation/shared-expression-validation-tests/single-field-equals.json
- src/features/validation/expressionValidation/shared-expression-validation-tests/warning.json
As requested on Slack: https://digdir.slack.com/archives/C085N9FPDFS/p1742912047881549?thread_ts=1742911514.683619&cid=C085N9FPDFS
This adds a regression test for #3165. This has been tested to be broken before this fix, and working after the fix.
- Sprint board
- Labels
> Syncing shared expression-validation tests with backend

- src/core/errorHandling/DisplayErrorProvider.tsx
- src/features/instance/useProcessNext.tsx
- src/index.tsx
- test/e2e/integration/frontend-test/process-next.ts
When refactoring ProcessNavigationContext into a hook, showing the Unknown Error page on uncaught exceptions did not get carried over. For this I need a context that blocks rendering on error, so I made a simple `DisplayErrorProvider` to achieve this. Added some tests related to whether failing PDF generation should show unknown error or just a toast which also covers this issue in general.
- https://digdir.slack.com/archives/C076GU2QHCG/p1742980600330939
- #2831
- Sprint board
- Labels
> Show unknown error when uncaught exception happens in process next

- src/layout/Grid/GridSummary.tsx
- test/e2e/integration/component-library/grid.ts
When refactoring in #3041, I broke rendering of Grid in Summary2, when compoents in cells have no value. This also adds testing that Grid Summary2, so that we're better suited to catch bugs here going forwards.
- closes #3206
- Sprint board
- Labels
> Fixing displayData as used in GridSummary.tsx, adding regression test

- src/layout/Grid/GridSummary.tsx
- src/layout/RepeatingGroup/Summary2/RepeatingGroupTableSummary/RepeatingGroupTableSummary.tsx
- src/layout/RepeatingGroup/Table/RepeatingGroupTableRow.tsx
(At least) two app developers have encountered a `Node with id ... not found` error in the wild. I'm not sure of the root cause, and I don't think it's time to try to debug that either (ref #3147, where we're planning to get rid of this entirely). Instead, if it's a case of nodes not being ready yet, this should fix itself automatically in a later render anyway - so it's better to just render something empty in the meantime.
This also renames some components that were copied from `GridComponent.tsx`, as I got confused when I looked at these components in the React devtools and ended up finding the wrong react component to try to debug an earlier issue (#3214).
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1743505404148709?thread_ts=1743418155.877269&cid=C02EJ9HKQA3
- Manual …
> Fixing rare case of `Node with id ... not found`

- src/features/devtools/components/ExpressionPlayground/ExpressionPlayground.tsx
Docs have been restructured, update the url to point to the correct location
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1743692023290309?thread_ts=1743682950.892349&cid=C02EJ9HKQA3
> Update URL for expression doc in dev tools

- .github/scripts/purge-frontdoor-cache.sh
> Add `--no-wait` option to afd purge command

- src/features/party/PartiesProvider.tsx
- src/features/party/partyUtils.ts
> Fixes valid parties not being flattened

- src/features/party/PartiesProvider.tsx
- src/features/party/partyUtils.ts
Backport of https://github.com/Altinn/app-frontend-react/pull/3266
- Sprint board
- Labels
> Backport flatten parties

- src/app-components/Date/Date.module.css
- src/app-components/Number/Number.module.css
- src/app-components/Text/Text.module.css
- src/layout/Date/DateComponent.tsx
- src/layout/Number/NumberComponent.tsx
- src/layout/Option/Option.module.css
- src/layout/Option/OptionComponent.tsx
- src/layout/Text/TextComponent.tsx
Change label fontsize on Date, Number, Text and Option component
- closes #3024 
- Sprint board
- Labels
> Change label fontsize on Date, Number, Text and Option component

- webpack.config.development.js
https://github.com/webpack/webpack-dev-server/issues/5446#issuecomment-2768816082
- Sprint board
- Labels
> add workaround for dev-server

- .github/workflows/revert.yml
> Test roll-back with dry-run

- .github/workflows/revert.yml
Reverts Altinn/app-frontend-react#3279
> Revert "Test roll-back with dry-run"

- .github/pull_request_template.md
- src/app-components/Date/Date.module.css
- src/app-components/Number/Number.module.css
- src/app-components/Text/Text.module.css
- src/components/PDFGeneratorPreview/PDFGeneratorPreview.tsx
- src/features/formData/useFormDataQuery.tsx
- src/features/instance/ProcessContext.tsx
- src/features/instance/useProcessNext.tsx
- src/hooks/useNavigatePage.ts
- src/layout/Date/DateComponent.tsx
- src/layout/Number/NumberComponent.tsx
- src/layout/Option/Option.module.css
- src/layout/Option/OptionComponent.tsx
- src/layout/Summary/ValidateSummary.tsx
- src/layout/Text/TextComponent.tsx
- src/utils/layout/NodesContext.tsx
- test/e2e/integration/signing-test/double-signing.ts
- test/e2e/integration/signing-test/reject.ts
- test/e2e/pageobjects/app-frontend.ts
- test/e2e/support/apps/signing-test/signing-login.ts
- #3268 
- #3265 
- #3260 
- #3272
> Cherry-picks for v4.18.5

- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/SigneeList/api.test.ts
- src/layout/SigneeList/api.ts
- src/layout/SigningActions/OnBehalfOfChooser.tsx
- src/layout/SigningActions/PanelAwaitingCurrentUserSignature.tsx
- src/layout/SigningActions/api.ts
> Adds error messages instead of disabled button

- .github/workflows/pr-actions.yml
Reverts Altinn/app-frontend-react#3357
> Revert "Bringing back `4.19.0-pr.1090.deleted-parties.bbe09450` v2"

- src/types/shared.ts
- src/utils/attachmentsUtils.test.ts
- src/utils/attachmentsUtils.ts
Support the correct spelling, mark the incorrect as to be deprecated, but continue support.
- closes [3364](https://github.com/Altinn/app-frontend-react/issues/3364)
- Sprint board
- Labels
> Support both spelling types for contribut[or/er]

- src/layout/Summary/SummaryItemSimple.module.css
- src/layout/Summary/SummaryItemSimple.tsx
- src/layout/TextArea/index.tsx
- test/e2e/integration/component-library/text-area.ts
This will show multiline text for TextArea components in the older Summary component (this was already implemented in Summary2).
- closes #3230
- Sprint board
- Labels
> Multiline text for `TextArea` components in Summary

- src/layout/InstanceInformation/InstanceInformationComponent.tsx
- src/utils/dateUtils.test.ts
The bug reported in #3395 is already fixed in https://github.com/Altinn/app-frontend-react/pull/3325 and was caused by the use of getDateTimeFormat.
Screenshot from a test run:
Functionally no difference in this pr, just using a helper method for InstanceInformation as it is done for signeelistsummary. Also added a test to catch any potential future regression errors.
- Sprint board
- Labels
> Date format pdf

- src/layout/Cards/CardsSummary.tsx
- src/layout/Cards/index.tsx
Added summar2 support for Cards.
- closes feat/2895-cards-summary2
- Sprint board
- Labels
> added summary2 support for cards

- src/layout/Accordion/SummaryAccordion.module.css
- src/layout/Accordion/SummaryAccordion.tsx
- src/layout/Accordion/index.tsx
- src/layout/AccordionGroup/SummaryAccordionGroupComponent.tsx
- src/layout/AccordionGroup/index.tsx
- test/e2e/integration/component-library/accordion-group.ts
- test/e2e/integration/component-library/accordion.ts
- test/e2e/integration/component-library/title-tag-updates.ts
Added Summary2 support for Accordion and AccordionGroup.
- closes https://github.com/Altinn/app-frontend-react/issues/2129 and partially https://github.com/Altinn/app-frontend-react/issues/2895
- Sprint board
- Labels
> added summary2 support for accordion

- src/components/LandmarkShortcuts.tsx
- src/features/navigation/AppNavigation.tsx
- src/features/navigation/SidebarNavigation.tsx
> Backports #3455

- src/layout/Header/HeaderComponent.tsx
- test/e2e/integration/frontend-test/custom-button.ts
> Fixes sizes for HeaderComponent

- src/app-components/Datepicker/Datepicker.tsx
> Auto backport demo fail

- src/codegen/ComponentConfig.ts
Adding `removeWhenHidden` property for all components that gets `dataModelBindings`. This is needed by backend.
- https://github.com/Altinn/app-lib-dotnet/issues/1353
- Sprint board
- Labels
> Schema for `removeWhenHidden` property

- src/layout/ImageUpload/ImageUpload.tsx
- src/layout/ImageUpload/imageUploadUtils.ts
Extracts the logic to perform logarithmic zoom in to utils functions.
- Sprint board
- Labels
> Extract logarithmic zoom functions to utils

- src/layout/ImageUpload/ImageUpload.module.css
La til touch-action for å unngå skrolling ved zoom-slideren. 
- Sprint board
- Labels
> fix: prevent scrolling

- src/features/attachments/AttachmentsStorePlugin.tsx
- src/layout/ImageUpload/ImageControllers.module.css
- src/layout/ImageUpload/ImageControllers.tsx
- src/layout/ImageUpload/ImageUpload.tsx
- src/layout/ImageUpload/ImageUploadComponent.tsx
- src/layout/ImageUpload/config.ts
- src/layout/ImageUpload/index.tsx
La til lagre og avbryt knapp med tilhørende funksjonalitet (bilde som er beskjært skal nå lagres) og justert dem etter designet. Valgte å flytte `handleCrop` til imageControllers, da der selve lagringen med beskjæring foregår, men kan endre på det hvis du skulle være uenig i dette, @Magnusrm . Når vi nå har så mange stater å håndtere, skulle vi kanskje ha plassert dem i en kontekst? Her er forslag til en poc som vi evt kan implementere: https://github.com/Altinn/app-frontend-react/tree/image-context-poc (den er laget ut i fra denne PR'en) …
> added save and cancel buttons with functionality (some left for save fn)

- src/layout/ImageUpload/ImageControllers.tsx
- src/layout/ImageUpload/ImageUpload.tsx
Add check at a higher level to decide correctly which state of control panel that should be rendered.
- Sprint board
- Labels
> fix: check for stored image at a higher level
