- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/components/base/ImageComponent.tsx
Solves part of #14 regarding widths defined in percentage of width used in the img.width prop. Moved to style.
Read more here: https://rocketvalidator.com/html-validation/bad-value-x-for-attribute-width-on-element-img-expected-a-digit-but-saw-instead
> wcag: moved width from width-prop to css style

- .github/workflows/build.yml
- src/altinn-app-frontend/package.json
When running the build action on main branch, it will now deploy a new version of app-frontend to CDN, similar to the old pipeline we had in AzureDevOps.
> Extend build action to push new app-frontend version to CDN on main branch

- sonar-project.properties
- src/shared/src/utils/urlHelper.test.ts
- src/shared/src/utils/urlHelper.ts
Sonarcloud config was incorrect, and test files were still counted when measuring code coverage, and duplications. This should fix it 🤞
Also fixed a couple links that were using http instead of https which SonarCloud also complained about.
> chore: update sonar.exclusions list

- sonar-project.properties
- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/features/form/layout/fetch/fetchFormLayoutSagas.test.ts
- src/altinn-app-frontend/src/features/form/layout/fetch/fetchFormLayoutSagas.ts
- src/altinn-app-frontend/src/features/form/layout/formLayoutSlice.test.ts
- src/altinn-app-frontend/src/features/form/layout/formLayoutSlice.ts
- test/cypress/e2e/integration/app-frontend/options.js
Git tired of running into this bug when testing locally so I just fixed it.
- bug: now uses application.id (org/app) as key for persiting selected page in local storage for stateless apps
- bug: now defaults to first page in page order if the cached key no longer exists (for both stateless + instance)
- sonarcloud: fixed glob for excluding test files
- https://github.com/Altinn/altinn-studio/issues/7897
- https://github.com/Altinn/altinn-studio/issues/6975
> bug: fixed stateless cache key + bug if cached key does no longer exist

- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/utils/validation.test.ts
- src/altinn-app-frontend/src/utils/validation.ts
Validation for empty fields broke when using `multiPage: true` in repeating groups. The validation missed the page number prefix in `group.children` and defaulted to validate as individual fields. Adding more unit tests for this and other layouts (such as repeating + nested + multiPage groups, although I haven't tested how that would work in the UI :wink:)
- Altinn/altinn-studio/issues/7478
> Empty fields validation for multiPage repeating groups

- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/utils/validation.test.ts
- src/altinn-app-frontend/src/utils/validation.ts
In the linked issue, the error was caused by an error message being an array mixed with react elements and strings. Checking inside these to look for the required message as well.
- Altinn/altinn-studio/issues/8481
> Checking for validation errors inside arrays recursively

- test/cypress/e2e/integration/app-frontend/options.js
- test/cypress/e2e/support/index.d.ts
The `options` cypress test was flaky. The root cause of this was assumed to be the way `preselectedOptionIndex` is implemented, as the first dropdown component (`source`) is first rendered once before it figures out it should be pre-selecting an option. The component will then set its data and render again shortly after. When this field value is then a dependency for a second dropdown with a list of options (`reference`), the list of options would first get fetched with `source=undefined` (during the first render) and then right after it would fetch options with `source=something`. Only then can the second dropdown (queried in this test) contain the expected option.
For cypress, this meant that it would find the element it was looking for (and verify it was visible), but then try to …
> Fixing flaky options test

- .github/workflows/release.yml
Related to https://github.com/Altinn/app-frontend-react/pull/89 , which had an incorrect condition to only run on refs/heads/main . This will not work, since the ref will be a tag instead.
> chore: remove invalid condition in release workflow

- src/altinn-app-frontend/src/components/base/FileUpload/FileUploadComponent.tsx
- src/altinn-app-frontend/src/shared/resources/attachments/attachmentReducer.test.ts
- src/altinn-app-frontend/src/shared/resources/attachments/attachmentReducer.ts
- src/altinn-app-frontend/src/shared/resources/textResources/replace/replaceTextResourcesSagas.ts
- src/altinn-app-frontend/src/store/index.ts
- src/shared/src/utils/language.test.ts
- src/shared/src/utils/language.ts
- avoid mutating text resources in our redux store (just a pure copy existing logic but create new object instead of mutation)
- cleanup of tests
- avoid mutating file upload state, removed duplicated local + global reducer as this caused issues
- added tests for touched parts of code 
- enabled immutability check for our redux store to avoid such errors again
- Partially solves #159, where we get rid of logic that mutates text resource array which caused problems for #https://github.com/Altinn/app-frontend-react/pull/83, and might have caused other bugs elsewhere.
> bug: avoid mutating redux state

- .github/workflows/build.yml
- .github/workflows/cypress-altinn-app-frontend.yml
- .github/workflows/release.yml
- README.md
- src/.yarnrc.yml
Add info about need for PAT token, and add this as environment variable for our build scripts
This is needed because we are currently using Github registry to publish our npm packages, and they require a PAT token to read from this registry. This is a prerequisite for using [@altinn/altinn-design-system](https://github.com/Altinn/altinn-design-system) package in this repo
> chore: add env variable for PAT token so packages from github registry

- src/altinn-app-frontend/src/shared/resources/profile/profileReducers.ts
- test/cypress/e2e/integration/app-stateless-anonymous/options.js
- test/cypress/e2e/pageobjects/app-frontend.js
Now sets `nb` as the initial preferred language for profile to fix crashing fetching of options for anonymous users.
> bug: failing to fetch options for anonymous users

- .github/workflows/cypress-altinn-app-frontend.yml
The testfiles are checked into git, as part of a change in #182 and the workflow for internal PR's was updated, but external PR step was missed.
- #182
> chore: remove step to create testfiles in external PR pipeline

- src/altinn-app-frontend/src/utils/appMetadata.test.ts
- src/altinn-app-frontend/src/utils/appMetadata.ts
- src/altinn-app-frontend/src/utils/validation.test.ts
- src/shared/src/types/index.ts
- src/shared/src/utils/applicationMetaDataUtils.ts
A weakness in frontend implementation came to show during development of support of auto deletion of dataelements. 
When identifying a dataelement that has a jsonSchema, we should not only check that applogic exists. 
- Altinn/app-template-dotnet#66
~~- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~
> Checking for classref, not only applogic for formData

- test/cypress/e2e/integration/app-frontend/summary.js
Verify that element actually is rendered before running the cypress evaluation. Caused flaky behavior.
> fix flaky cypress test

- README.md
Had problems using PAT for mac using the proposed guide and updated with what worked for me using z shell on mac.
> Update README.md for PAT with z shell on mac

- src/altinn-app-frontend/src/utils/formComponentUtils.ts
It seems like it should be "undefined behaviour" to specify both `options` and `optionsId` on a selection component. Currently most things work, so this change will make the behaviour consistent and pick the api options specified by `optionsId` first if present, also on `RepeatingGroupTable`.
- [Slack discussion](https://altinn.slack.com/archives/C02EVE4RU82/p1655812902474279)
> Make RepeatingGroupTable check optionsId and Options in same order

- .github/workflows/release.yml
Supporting pull request for an upcoming PR in studio, where a list of released versions would be helpful when building a selector for testing previous versions.
`jq` [should be available in ubuntu-latest](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#tools)
- Altinn/altinn-studio/pull/8562
> Support pre-releases in workflow and generate a list of versions as a .json on CDN

- .github/workflows/release.yml
This should fix the failing release publishing now that the command got split into multiple distinct steps
> Fixing release workflow

- .github/workflows/build.yml
Builds from forks always result in a failed check, because they do not have access to the `SONAR_TOKEN` secret. This is very annoying. We investigated possibilities to be able to run this check in a separate workflow which had access to the secret in #255 , but it turned out to be a bit complex, and not worth the trouble.
We should instead disable SonarCloud scan on forks, and if we want coverage checks (or other checks) from forks, we should add other tools to our pipeline (tools which ideally do not require any secrets, because then we get into the same problem again)
- #234 
- #300
> chore: disable SonarCloud scan for forks

- src/altinn-app-frontend/setupTests.ts
- src/altinn-app-frontend/src/features/form/containers/GroupContainerLikert.test.tsx
- src/altinn-app-frontend/src/features/form/containers/GroupContainerLikertTestUtils.tsx
We recently had some unstable tests, due to tests taking more than the allotted time to execute (10 seconds pr test). This was caused by using `getByRole` query, which is not great on a large DOM tree (~600 nodes) in a loop within a loop. The slowest test in this group now takes ~3500ms which is still not _great_, but I think good enough for now 🙂 When running the whole test suite, it takes longer (6-7000ms), which is why I have kept the increased jest timeout of 10000ms.
- Decreased test data set
-  This is to reduce the generated DOM size, to improve the general test performance
- Changed from `getByRole` to `getByDisplayValue` in the innermost loop to improve test performance
- Fixed issue in test data where answers were added with incorrect casing in the key. This was not caught by …
> chore: fix unstable tests

- src/altinn-app-frontend/src/utils/formLayout.test.ts
- src/altinn-app-frontend/src/utils/formLayout.ts
When adding formData to previous rows in a repeating group, and combined with a 303 response from the server causing repeating groups to be recalculated, you could end up with an issue where the repeating group index got overwritten with a lower value - seemingly deleting subsequent rows.
- #307
> Fixing bug causing misindexed repeating groups

- src/altinn-app-frontend/src/utils/databindings.test.ts
- src/altinn-app-frontend/src/utils/databindings.ts
The offending code caused Safari to crash on load.
- #312
> Fixing code using lookbehind + lookahead, for Safari

- src/altinn-app-frontend/src/features/form/containers/GroupContainer.tsx
- src/altinn-app-frontend/src/features/form/layout/formLayoutTypes.ts
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- test/cypress/e2e/integration/app-frontend/group.js
- test/cypress/e2e/support/app-frontend.js
- test/cypress/e2e/support/index.d.ts
I accidentally broke the `openByDefault` edit option for repeating groups in #246 when I extended `updateRepeatingGroupsSaga` to possibly cancel a row removal (when attachments could not be deleted). Adding the functionality back in (with a single dispatched event, causing no races) and adding tests for it.
- #128
> Fixing openByDefault option on repeating groups

- src/altinn-app-frontend/src/components/summary/SummaryGroupComponent.tsx
- src/altinn-app-frontend/src/utils/databindings.test.ts
- test/cypress/e2e/fixtures/texts.json
- test/cypress/e2e/integration/app-frontend/summary.js
- test/cypress/e2e/pageobjects/app-frontend.js
This fix involves three distinct changes:
1. Using a Set instead of iterating the hidden fields to reduce it to a subset. While the group children filter works, it does not filter nested children, so this didn't seem to have the desired effect on nested groups. I assume the filtering is done for performance reasons, so using a Set for this seems more ideal (lookups are cheap, at least).
2. Making sure we check for the full nested dashed path when testing if the field should be hidden. Without this, nested dynamics have no effect when showing a summary.
3. Moving the code so that loops continue earlier when hidden fields are found. Previously it would run the iteration almost to the end before scrapping the result if the field was hidden, which is a bit wasteful. This shouldn't have an …
> Bug: Dynamics/hidden fields in summaries of nested repeating groups

- src/.eslintrc.json
- src/altinn-app-frontend/src/components/advanced/AddressComponent.tsx
Introduced in the recently merged #305, these hooks had missing dependencies. Changing the warning to be an error as well.
- #305
- ~~[ ] Manual testing done (required)~~
> Fixing missing dependencies for hooks

- src/altinn-app-frontend/src/components/base/DatepickerComponent.test.tsx
- src/altinn-app-frontend/src/components/base/ImageComponent.tsx
- src/altinn-app-frontend/src/components/base/ParagraphComponent.test.tsx
- src/altinn-app-frontend/src/components/base/ParagraphComponent.tsx
- src/altinn-app-frontend/src/components/base/__snapshots__/ParagraphComponent.test.tsx.snap
- src/altinn-app-frontend/src/utils/dateHelpers.test.ts
- src/altinn-app-frontend/src/utils/validation.test.ts
- src/altinn-app-frontend/src/utils/validation.ts
This silences some knows warnings in unit tests, and tests for them instead of outputting them to the console. In addition, it cleans up some warnings shown in the console when running some apps.
> Cleaning up some warnings from tests and React runtime

- src/.eslintrc.json
- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/components/GenericComponent.tsx
- src/altinn-app-frontend/src/components/base/ButtonComponent.tsx
- src/altinn-app-frontend/src/features/confirm/containers/Confirm.tsx
- src/altinn-app-frontend/src/features/form/components/Label.tsx
- src/altinn-app-frontend/src/features/form/components/Legend.tsx
- src/altinn-app-frontend/src/features/form/components/RepeatingGroupAddButton.tsx
- src/altinn-app-frontend/src/features/form/containers/DisplayGroupContainer.tsx
- src/altinn-app-frontend/src/features/form/containers/Form.tsx
- src/altinn-app-frontend/src/features/form/data/fetch/fetchFormDataSagas.ts
- src/altinn-app-frontend/src/features/form/data/formDataSlice.ts
- src/altinn-app-frontend/src/features/form/data/submit/submitFormDataSagas.ts
- src/altinn-app-frontend/src/features/form/datamodel/fetch/fetchFormDatamodelSagas.ts
- src/altinn-app-frontend/src/features/form/dynamics/index.ts
- src/altinn-app-frontend/src/features/form/layout/formLayoutSagas.ts
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- src/altinn-app-frontend/src/shared/containers/ProcessWrapper.tsx
- src/altinn-app-frontend/src/shared/resources/options/optionsSagas.ts
- src/altinn-app-frontend/src/shared/resources/queue/infoTask/infoTaskQueueSaga.ts
- src/altinn-app-frontend/src/types/index.ts
- src/altinn-app-frontend/src/utils/databindings.test.ts
- src/altinn-app-frontend/src/utils/databindings.ts
- src/altinn-app-frontend/src/utils/validation.ts
- src/altinn-app-frontend/styleguide/wrapper.tsx
- src/shared/src/components/molecules/AltinnInformationPaper.tsx
- src/shared/styleguide/wrapper.tsx
- src/yarn.lock
- ~I propose to allow unused arguments named `_action`. This should of course be used only when needed, as the example in a saga where its used for TS infering types (see commit [`00ba52d` (#342)](https://github.com/Altinn/app-frontend-react/pull/342/commits/00ba52dfadee0c52931d48710e8e2a1d243d5a62) for details). By allowing this, we dont need to add `eslint-disable-next-line` whenever doing this, explaining why its needed.~ Not going to include this after all, as it will not be needed (ref: https://github.com/Altinn/app-frontend-react/pull/342#commitcomment-78491931). We can always add something like this back if we see the need for it.
- Removal of all `eslint-disable` statements, except one, [where a console.log is used](https://github.com/Altinn/app-frontend-react/blob/v3.46.0/src/alti …
> chore: remove invalid eslint-disable statements

- src/altinn-app-frontend/src/utils/formComponentUtils.test.ts
- src/altinn-app-frontend/src/utils/formComponentUtils.ts
- src/altinn-app-frontend/src/utils/validation.test.ts
- test/cypress/e2e/fixtures/texts.json
After the introduction of better error messages for required fields (`You have to fill out {0}`), I've been slightly irked by these error messages falling back to the `title` text binding (if no `shortName` exists), but keeping the uppercase first letter these titles usually have. This produces error messages like `You have to fill out First name` instead of the more natural `You have to fill out first name`.
It might not be advisable to simply un-uppercase the first letter all the time, as the title text might be an all-uppercase abbreviation, etc. This impulsive PR nobody asked for tries to solve this by looking at the first 5 non-symbol letters in the string in order to decide if it should uncapitalize the first letter.
Demo of what this does (here inside the unfinished #346, with …
> Smart un-uppercasing for required field validations

- src/altinn-app-frontend/src/components/base/FileUpload/FileUploadWithTag/EditWindowComponent.tsx
- src/altinn-app-frontend/src/components/base/FileUpload/FileUploadWithTag/FileUploadWithTagComponent.tsx
The root cause of this round of cypress test problems was caused by the backend being a little slow to respond when uploading the attachment. Because of this, when cypress used the dropdown to select a tag for an uploaded attachment (which seems entirely valid even though the attachment hasn't been uploaded yet), it stored this state using the `tmpAttachmentId`. When the attachment had finished uploading, this tag was stored on the wrong id. This adds a quick-fix where you can't use the select/dropdown until the attachment is fully uploaded.
> Fixing failing cypress test for FileUploadWithTag

- .github/workflows/cypress-altinn-app-frontend.yml
- src/altinn-app-frontend/src/components/hooks/useDelayedSavedState.ts
- src/altinn-app-frontend/src/store/index.ts
- test/cypress/.gitignore
- test/cypress/e2e/fixtures/texts.json
- test/cypress/e2e/support/index.js
- test/cypress/e2e/support/start-app-instance.js
Multiple adjustments to Cypress testing.
1. Adding an option called `responseFuzzing`. When enabled, all API responses from the backend will be artificially delayed a random amount of time, simulating a slow network, I/O load on the backend, etc. This also causes dispatched events in the frontend to sometimes be fulfilled out-of-order, and can thus be used to bring to light any issues where our functionality implicitly relied on server response times in order to update the redux state correctly (like what happened in #365 and #87). Running this right now causes multiple cypress tests to fail, so it's evident we have more problems like this.
2. (Not included in code here, but still relevant to these changes.) I added `crossorigin` to the `<script>` tags in all tested apps, so that Cypress …
> Cypress: Fuzzing and redux logging

- .github/workflows/cypress-altinn-app-frontend.yml
Cypress tests for #326 fails, as the max file watchers haven't been increased for fork PRs.
- #326
> Cypress: Increasing file watcher limits for fork PRs

- src/altinn-app-frontend/src/components/GenericComponent.tsx
- src/altinn-app-frontend/src/components/message/ErrorReport.tsx
- src/shared/src/theme/altinnAppTheme.tsx
- src/shared/src/utils/language.ts
As requested, changing the underline to be `2px black`, and also removing potential links from markdown text in error messages when shown in `ErrorReport`.
Before:
After:
- #100
> Style fixes for #100

- src/altinn-app-frontend/src/utils/formLayout.test.ts
- src/altinn-app-frontend/src/utils/formLayout.ts
Fixed a bug with repeating groups where it would only show max 9 rows, even if you had a much larger datamodel. 
We discovered the bug when implementing the Likert component with rows above 10.
I reproduced the bug in a test and fixed it!
> Fix bug with repeating groups only showing 9 rows

- README.md
- src/.yarnrc.yml
- src/altinn-app-frontend/package.json
- src/yarn.lock
- new version is published on npm feed instead of github, so we no longer need to set up a PAT
> chore: upgrade to latest design system package

- .github/workflows/build.yml
Currently, fork PR's still try to run SonarCloud scan, which will not work since they will not have access to the required secret. This should skip it for external PRs.
> chore: attempt to skip SonarCloud run on external PR's

- src/shared/src/components/organisms/AltinnAppHeader.test.tsx
- src/shared/src/components/organisms/AltinnAppHeaderMenu.tsx
- src/shared/src/types/index.ts
Shows the private person icon as a fallback if ssn or orgNumber is not present in user party.
- #58
> BugFix: Show menu icon when user doesn't have ssn or org number

- src/altinn-app-frontend/src/features/confirm/containers/Confirm.tsx
- src/altinn-app-frontend/src/features/feedback/Feedback.tsx
- src/altinn-app-frontend/src/features/form/containers/Form.tsx
- src/altinn-app-frontend/src/features/instantiate/containers/InstanceSelection.tsx
- src/altinn-app-frontend/src/features/instantiate/containers/InstantiationContainer.tsx
- src/altinn-app-frontend/src/features/receipt/containers/ReceiptContainer.tsx
- src/altinn-app-frontend/src/shared/components/ReadyForPrint.tsx
This element should be injected everywhere in our app at the points where all content has been loaded and the DOM is ready for the user (i.e., after all our loading placeholders). This element (`#readyForPrint`) can be listened for by the PDF generator to know when the page can be printed to a PDF.
As it's notoriously hard to test these things, and I'm not sure how (or even if) we should include this in our Cypress test suite, I opened up the debugger in Chrome and pasted this code inside a file to make sure we trigger a breakpoint (which freezes rendering) when the `readyForPrint` element appears on the page. It's not pretty, but it's what made me find the issue with images that have to be loaded.
```typescript
let iterations = 0;
let found = false;
setInterval(() => {
iterations++; …
```
> Adding an element for the PDF generator to know when the page has loaded

- renovate.json
- Do not group any 0.x.x dependency together with minor/patch PR, because these could contain breaking changes acoording to the semver spec.
- Add schedule for when renovate should create PR's
- Add delay for when a new version is published, before renovate creates a PR to update it. The delay is currently 3 days. See https://docs.renovatebot.com/presets-npm/
- #274
> chore: treat 0.x.x versions as major changes, so they are not grouped in renovate

- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupTable.tsx
- src/shared/src/components/molecules/AltinnMobileTableItem.tsx
Add active css class for editbutton in repeating groups and apply it to the button with the index that is currently being edited. 
#324
> Keep focus styling on edit button when editing group

- .github/workflows/release.yml
This should add all files from the `dist` folder to CDN, not just the js/css file. The only obvious weakness is that it will not delete previous files no longer part of the `dist` folder.
- #429
> Uploading all files to CDN on release

- .github/workflows/release.yml
Release script got broken in #430, because of two oversights:
1. Git gets confused when told to perform operations from a working directory not in git (even though the relative path points to a checked out repo).
2. Removing `*` in a folder produces an error when the folder is empty
Rant: I would love for these scripts to be more easily testable locally
- #430
> Fixing release script

- src/altinn-app-frontend/src/features/form/layout/formLayoutSlice.ts
This variable did not get checked and causes some apps to crash.
> Fix: Nullcheck layoutSets

- src/altinn-app-frontend/src/features/form/dynamics/formDynamicsSlice.ts
Solves a race condition [reported by SSB](https://altinn.slack.com/archives/C02EVE4RU82/p1662552278562939). For dynamics for repeating groups to work the repeating group state must be set before running the rules. This fix prevents the rules running before this init is completed.
> bug: race condition conditional rules

- src/altinn-app-frontend/src/store/index.ts
- src/altinn-app-frontend/webpack.config.production.js
This change enables redux devtools in the production build, which brings with a few hundred bytes extra code, ~~as well as a 7.1mb `altinn-app-frontend.js.map` and a 556kb `altinn-app-frontend.css.map` to be published on altinncdn.no.~~
Adding these to the production build gives us a few advantages when debugging and reproducing strange bugs:
- We can record the redux state history, saving them to a file, making it possible to save and replay the state history for race condition bugs
- ~~Thrown exceptions in our own code will include references to the actual source files, lines and code that caused the error (instead of line 1, column 489984)~~
- #392
- #452
> Enabling redux devtools in production

- .github/workflows/release.yml
Removing `cd ..` which was removed for regular releases in #433, but not for pre-releases (causing the pre-release script to crash). I'm pretty sure I tested this properly in preparation for #437, but this line must have slipped through.. 
- #433
- #437
> Fixing prerelease script

- .github/workflows/release.yml
This makes the regex match the `3.50.5-alpha2` version already on CDN
- #179
- #256
- #433 
- #437 
- #467
- @olemartinorg (*I have issues* with the release script! :face_with_head_bandage:)
- ~~[ ] All tests run green~~
> Fixing index.json regex

- test/cypress/e2e/integration/app-frontend/confirmation.js
- test/cypress/e2e/integration/app-frontend/group.js
- test/cypress/e2e/integration/app-frontend/likert.js
- test/cypress/e2e/integration/app-frontend/mobile.js
- test/cypress/e2e/integration/app-frontend/receipt.js
- test/cypress/e2e/integration/app-frontend/summary.js
- test/cypress/e2e/pageobjects/likert.js
- test/cypress/e2e/support/app-frontend.js
- test/cypress/e2e/support/index.d.ts
- test/cypress/e2e/support/index.js
- test/cypress/package.json
- test/cypress/yarn.lock
Added support for e2e testing of the likert component.
NB: The cypress tests will not work before https://dev.altinn.studio/repos/ttd/frontend-test/pulls/8 is deployed to tt02.
> E2E Likert support

- src/altinn-app-frontend/src/common/hooks/useProcess.ts
- src/altinn-app-frontend/src/components/base/ButtonComponent.test.tsx
- src/altinn-app-frontend/src/components/base/ButtonComponent.tsx
- src/altinn-app-frontend/src/features/form/data/fetch/fetchFormDataSagas.test.ts
- src/altinn-app-frontend/src/features/form/data/fetch/fetchFormDataSagas.ts
- src/altinn-app-frontend/src/features/form/data/submit/submitFormDataSagas.test.ts
- src/altinn-app-frontend/src/features/form/data/submit/submitFormDataSagas.ts
- src/altinn-app-frontend/src/features/form/layout/fetch/fetchFormLayoutSagas.ts
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- src/altinn-app-frontend/src/features/form/validation/singleField/singleFieldValidationSagas.ts
- src/altinn-app-frontend/src/selectors/simpleSelectors.ts
- src/altinn-app-frontend/src/shared/containers/ProcessWrapper.tsx
- src/altinn-app-frontend/src/shared/resources/attachments/map/mapAttachmentsSagas.test.ts
- src/altinn-app-frontend/src/shared/resources/attachments/map/mapAttachmentsSagas.ts
- src/altinn-app-frontend/src/shared/resources/process/completeProcess/completeProcessSagas.ts
- src/altinn-app-frontend/src/shared/resources/queue/infoTask/infoTaskQueueSaga.ts
- src/altinn-app-frontend/src/shared/resources/queue/queueSlice.ts
- src/altinn-app-frontend/src/utils/appMetadata.test.ts
- src/altinn-app-frontend/src/utils/appMetadata.ts
- src/altinn-app-frontend/src/utils/formLayout.test.ts
- src/altinn-app-frontend/src/utils/formLayout.ts
- src/altinn-app-frontend/src/utils/validation/runClientSideValidation.ts
- src/altinn-app-frontend/src/utils/validation/validation.ts
Enables app developers to set up a custom layout for confirmation (or other steps in the future) through the use of our[ layout-set](https://docs.altinn.studio/app/development/ux/pages/layout-sets/) feature.
This feature can be seen implemented in[ this test app](https://altinn.studio/repos/ttd/custom-view-confirm).
Enables app developers to go from this hardcoded view:
To a completely configurable form layout definition with a reference to an earlier data model which they can present data from: 
Please note that for this feature to work entirely we rely on some other new features coming in #262. 
- #482
> feat: custom confirm

- src/altinn-app-frontend/src/components/GenericComponent.tsx
- src/altinn-app-frontend/src/components/summary/GroupInputSummary.tsx
- src/altinn-app-frontend/src/components/summary/SingleInputSummary.tsx
- src/altinn-app-frontend/src/components/summary/SummaryBoilerplate.tsx
- src/altinn-app-frontend/src/components/summary/SummaryComponent.tsx
- src/altinn-app-frontend/src/components/summary/SummaryComponentSwitch.test.tsx
- src/altinn-app-frontend/src/components/summary/SummaryComponentSwitch.tsx
- src/altinn-app-frontend/src/components/summary/SummaryGroupComponent.tsx
- src/altinn-app-frontend/src/components/summary/__snapshots__/MultipleChoiceSummary.test.tsx.snap
- src/altinn-app-frontend/src/components/summary/__snapshots__/SummaryGroupComponent.test.tsx.snap
- src/altinn-app-frontend/src/features/form/containers/Form.tsx
- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupsEditContainer.tsx
- src/altinn-app-frontend/src/features/form/layout/index.ts
- src/altinn-app-frontend/src/utils/formComponentUtils.test.ts
- src/altinn-app-frontend/src/utils/formComponentUtils.ts
- src/altinn-app-frontend/src/utils/layout/index.tsx
Updated summary components with some display options to make it more readable with repeating groups:
- `hideBottomBorder` - to hide the blue dotted border between summary components.
- `useComponentGrid` - allows the summary component to use the layout components defined grid setup. Especially useful for summary groups with `largeGroup: true`.
- `hideChangeButton` - Useful when using summary components f.ex. in a custom confirm view, when it is not possible to navigate directly back to the form to change things.
In addition, updated some styling as discussed with @Febakke:
- Added a pale grey border around repeating group items in summary to make it more readable
- Swapped styling of label/data so that data is bold while label is normal.
Apart from the small styling fixes, existing apps …
> add display options to summary components

- src/altinn-app-frontend/src/shared/resources/language/fetch/fetchLanguageSagas.ts
- src/altinn-app-frontend/src/shared/resources/textResources/fetch/fetchTextResourcesSagas.ts
In PR #480 language loading got subtly changed in a way that caused the user language from the profile to not be loaded. This was caused by a default in the redux store which set the language to 'nb' when no profile had been fetched - but this now caused us to rely on that default when first loading the language.
- #480
- #495
> Fixing language loading

- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupTable.tsx
> Fix issue with text-wrapping in edit container and width of container when deletebutton not present

- src/altinn-app-frontend/src/features/form/data/formDataSlice.ts
- src/altinn-app-frontend/src/features/form/data/formDataTypes.ts
- src/altinn-app-frontend/src/features/form/data/submit/submitFormDataSagas.test.ts
- src/altinn-app-frontend/src/features/form/data/submit/submitFormDataSagas.ts
- src/altinn-app-frontend/src/features/form/data/update/updateFormDataSagas.test.ts
- src/altinn-app-frontend/src/features/form/data/update/updateFormDataSagas.ts
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.test.ts
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- src/altinn-app-frontend/src/shared/resources/options/fetch/fetchOptionsSagas.test.ts
Adds two header values `field` and `componentId` when calling put on a data element (which in turns calls processWrite). 
This enables app developers with some c# knowhow to get the header values from the HTTP-context when running data processing. 
- [Slack discussion (internal link)](https://altinndevops.slack.com/archives/CDU1S3NLW/p1664343663566769)
> feature: include what field/component that triggered save

- src/altinn-app-frontend/src/utils/appUrlHelper.test.ts
- src/altinn-app-frontend/src/utils/appUrlHelper.ts
Quick and dirty fix for `getHostname` function that failed using newest local test url (local.altinn.cloud) and latest app frontend prod build.
Some of these methods could probably be cleaned up, but I did not take the time to evaluate if the throwing of errors are used for anything. 
Fix and forget.
> bug: fix getHostname for new local test url

- src/altinn-app-frontend/src/components/base/DatepickerComponent.test.tsx
- src/altinn-app-frontend/src/utils/render.tsx
- src/shared/src/components/molecules/AltinnMobileTableItem.test.tsx
We had some unit tests that were producing warnings in the console, which makes it difficult to see which tests are failing and why (especially in non-color consoles, like sometimes here on github).
- Removing leftover `screen.debug()`
- Adding missing keys to validation messages (which React complains about). I struggled to find something unique, so serializing all the arguments should be unique enough. 
- ~~[ ] Manual testing done (required)~~
> Cleaning up some unit test warnings in console

- src/altinn-app-frontend/src/utils/appMetadata.ts
- src/shared/src/types/index.ts
#483 introduced code that could fail when `currentTask` was `null`/`undefined` which could crash the receipt page for (older?) apps. [See slack thread here](https://app.slack.com/client/TCQRNBDHS/C02FK32FBR6/thread/C02FK32FBR6-1664794330.261989).
> Null-checking for currentTask

- README.md
- docker-compose.yml
- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/webpack.config.docker.js
Re-merging #492 onto `main` (it was merged into `feat/layout-expressions` by mistake). I experimented with building an image containing (and caching) `node_modules`, but it got a bit too messy. Keeping the feature as-is, just fixing the container name.
- #492
> Docker compose

- src/altinn-app-frontend/__mocks__/instanceDataStateMock.ts
- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/features/instantiate/containers/InstanceSelection.test.tsx
- src/altinn-app-frontend/src/features/receipt/containers/ReceiptContainer.test.tsx
- src/altinn-app-frontend/src/shared/containers/Presentation.test.tsx
- src/altinn-app-frontend/src/utils/appUrlHelper.test.ts
When removing `altinn3local.no` from hosts file two tests started failing locally: one in `InstantiationButton.test.tsx`, and one in `ConfirmPage.test.tsx`:
There are still many references to `altinn3local.no` in several unit tests, in `instanceDataStateMock.ts` and in `package.json`. I did a simple search and replace to update these to use the new `local.altinn.cloud`, and now all of the unit tests run fine locally without the entry in the hosts file.
I am not sure whether there are any other notable consequences to these changes so please look through them thoroughly.
- #{issue number}
> Bug: Tests failing when removing altinn3local.no from hosts

- src/altinn-app-frontend/__mocks__/constants.ts
- src/altinn-app-frontend/src/components/base/CheckboxesContainerComponent.test.tsx
- src/altinn-app-frontend/src/components/base/CheckboxesContainerComponent.tsx
- src/altinn-app-frontend/src/components/base/DropdownComponent.test.tsx
- src/altinn-app-frontend/src/components/base/DropdownComponent.tsx
- src/altinn-app-frontend/src/components/base/RadioButtons/ControlledRadioGroup.tsx
- src/altinn-app-frontend/src/components/base/RadioButtons/RadioButtonsContainerComponent.test.tsx
- src/altinn-app-frontend/src/components/base/RadioButtons/radioButtonsUtils.ts
- src/altinn-app-frontend/src/components/hooks/useDelayedSavedState.ts
- src/altinn-app-frontend/src/features/form/containers/GroupContainerLikert.test.tsx
- src/altinn-app-frontend/src/features/form/containers/GroupContainerLikertTestUtils.tsx
- test/cypress/e2e/integration/app-frontend/likert.js
The original issue was only concerned with checkbox-groups, but similar issues where also present with dropdown and radio-buttons. The useDelayedSavedState hook is now used for checkbox-groups, radio-buttons, and dropdown. This prevents the premature onBlur validation as it only calls handleDataChange if the data has actually changed. This means that tabbing through the form without editing will no longer trigger validation for these components as is already the case with text-inputs. Additionally, it was previously possible to spam the backend with validation requests by holding an arrow-key in a radiobutton group (switching the input very quickly). The useDelayedSavedState hook mitigates this issue as well.
- #237
> Bug: checkbox group onblur validation

- src/altinn-app-frontend/src/features/form/data/submit/submitFormDataSagas.test.ts
- src/altinn-app-frontend/src/features/form/data/submit/submitFormDataSagas.ts
- test/cypress/e2e/pageobjects/app-frontend.js
This should fix a bug where UTF8 characters are sent in the HTTP header when changing a field.
**PS:** This changes the `frontend-test` app, and a new version has been deployed. Most cypress tests will fail until this is merged.
- #{issue number}
> Encoding fields in HTTP headers

- src/altinn-app-frontend/src/features/form/containers/GroupContainer.tsx
- src/altinn-app-frontend/src/features/form/layout/index.ts
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- test/cypress/e2e/integration/app-frontend/group.js
- test/cypress/e2e/pageobjects/app-frontend.js
- test/cypress/e2e/support/app-frontend.js
Changes the openByDefault parameter to accept 'first' and 'last' values in addition to boolean. true and 'first' are equivalent. In the initializeRepeatingGroupsSaga it will check the openByDefault variable to see if it should open the first or last item in a repeating group if it has prefilled values. Otherwise, if there are no prefilled items, it works in the same way as before where it adds a new item to the group and opens it.
Updated schema: https://github.com/Altinn/altinn-cdn/pull/111
Updated docs: https://github.com/Altinn/altinn-studio-docs/pull/688
- #396
> Feat/396 Open by default with prefill

- src/altinn-app-frontend/__mocks__/constants.ts
- src/altinn-app-frontend/src/components/GenericComponent.tsx
- src/altinn-app-frontend/src/components/advanced/AddressComponent.test.tsx
- src/altinn-app-frontend/src/components/advanced/AddressComponent.tsx
- src/altinn-app-frontend/src/components/base/CheckboxesContainerComponent.test.tsx
- src/altinn-app-frontend/src/components/base/DatepickerComponent.test.tsx
- src/altinn-app-frontend/src/components/base/DatepickerComponent.tsx
- src/altinn-app-frontend/src/components/base/DropdownComponent.test.tsx
- src/altinn-app-frontend/src/components/base/InputComponent.test.tsx
- src/altinn-app-frontend/src/components/base/RadioButtons/RadioButtonsContainerComponent.test.tsx
- src/altinn-app-frontend/src/components/base/TextAreaComponent.test.tsx
- src/altinn-app-frontend/src/components/custom/CustomWebComponent.tsx
- src/altinn-app-frontend/src/components/hooks/useDelayedSavedState.ts
- src/altinn-app-frontend/src/components/index.ts
- src/altinn-app-frontend/src/features/form/containers/GroupContainerLikert.test.tsx
- src/altinn-app-frontend/src/features/form/containers/GroupContainerLikertTestUtils.tsx
- src/altinn-app-frontend/src/features/form/data/formDataTypes.ts
- src/altinn-app-frontend/src/features/form/data/update/updateFormDataSagas.ts
- src/altinn-app-frontend/src/features/form/rules/check/checkRulesSagas.ts
- src/altinn-app-frontend/src/utils/formLayout.ts
- src/altinn-app-frontend/src/utils/validation/validation.ts
Components used to be able to turn off the 'required' validation when saving changes, but this should be the default (and no component should be able to force that check). Cleaning up this code.
- #99 
- #100 
- #237
> Removing the checkIfRequired option in handleDataChange

- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupTable.tsx
`RepeatingGroupTable` now uses the textResourceBinding `tableTitle` for the table header if it is defined.
- Updated docs: https://github.com/Altinn/altinn-studio-docs/pull/691
Before (desktop)             |  After (desktop)
:-------------------------:|:-------------------------:
Before (mobile)             |  After (mobile)
:-------------------------:|:-------------------------:
- #68
> Uses tableTitle for table headers if defined

- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/features/form/layout/index.ts
- src/yarn.lock
Importing the type from the design system instead of having the package in this repo
- #487
- ~~[ ] Manual testing done (required)~~
> Removing react-number-format

- src/altinn-app-frontend/src/features/form/containers/GroupContainer.tsx
- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupTable.tsx
- src/altinn-app-frontend/src/features/form/layout/formLayoutTypes.ts
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- src/shared/src/components/molecules/AltinnMobileTableItem.tsx
- test/cypress/e2e/integration/app-frontend/attachments-in-group.js
- test/cypress/e2e/integration/app-frontend/group.js
Minor css changes to fix the width of the Add button in nested repeating groups. Removed leaveOpen-logic from openByDefault as it seems to do nothing besides causing the bug in #442. Nobody I asked knew what the intended behaviour of leaveOpen was, and openByDefault works as documented without this logic.
- #398 
- #442 
- ~~User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~
> Bug: Fix repeating group UI issues

- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
Adding null-checks for possibly missing `edit` property in repeating group component
> Null-checking edit property

- src/altinn-app-frontend/__mocks__/uiConfigStateMock.ts
- src/altinn-app-frontend/src/components/base/NavigationBar.test.tsx
- src/altinn-app-frontend/src/components/base/NavigationBar.tsx
- src/altinn-app-frontend/src/components/presentation/Header.test.tsx
- src/altinn-app-frontend/src/components/presentation/NavigationButtons.test.tsx
- src/altinn-app-frontend/src/components/presentation/NavigationButtons.tsx
- src/altinn-app-frontend/src/components/presentation/Progress.tsx
- src/altinn-app-frontend/src/components/summary/SummaryGroupComponent.test.tsx
- src/altinn-app-frontend/src/features/form/containers/GroupContainerLikertTestUtils.tsx
- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupsTable.test.tsx
- src/altinn-app-frontend/src/features/form/layout/formLayoutSlice.test.ts
- src/altinn-app-frontend/src/features/form/layout/formLayoutSlice.ts
- src/altinn-app-frontend/src/features/form/layout/formLayoutTypes.ts
- src/altinn-app-frontend/src/selectors/getLayoutOrder.test.ts
- src/altinn-app-frontend/src/selectors/getLayoutOrder.ts
- src/altinn-app-frontend/src/shared/containers/Presentation.tsx
- src/altinn-app-frontend/src/types/index.ts
- src/altinn-app-frontend/src/utils/validation/runClientSideValidation.ts
Splitting up the massive #540 into smaller parts. This part includes a new redux structure for 'tracks', (i.e. showing/hiding entire layouts/pages). This structure is needed to group together state that revolves around which pages should be visible, and the order of these pages.
The new rules for page visibility and order is:
1. The order is decided by the backend
2. Hidden pages are removed from the ordered list by the backend
3. The frontend may also hide some pages via expressions in the layout definition (but this should not affect the order)
This PR includes the structures needed to store the expressions in the frontend, the result of these expressions (calculated when there are changes to the form data, etc), and the code to calculate the final ordered list of layouts. 
- #540
- ~~[ …
> Expressions: Tracks

- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/components/base/ButtonComponent/ButtonComponent.module.css
- src/yarn.lock
- test/cypress/e2e/integration/app-frontend/message.js
Updated the design system dependency to 0.14.1. Removed some css from ButtonComponent that used an old figma token that broke the button padding. Updated a cypress test that checks the button width to comply with the new styling.
- ~~#{issue number}~~
- ~~Relevant automated test added (if you find this hard, leave it and we'll help out)~~
- ~~User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~
> Updated design system dependency to 0.14.1

- src/altinn-app-frontend/src/components/base/CheckboxesContainerComponent.test.tsx
- src/altinn-app-frontend/src/components/base/DropdownComponent.test.tsx
- src/altinn-app-frontend/src/components/base/InputComponent.test.tsx
- src/altinn-app-frontend/src/components/base/RadioButtons/RadioButtonsContainerComponent.test.tsx
- src/altinn-app-frontend/src/components/hooks/useDelayedSavedState.ts
- src/altinn-app-frontend/src/features/form/containers/GroupContainerLikert.test.tsx
The setTimeout in useDelayedSaveState was flaky, as sometimes (especially if my computer had more than enough to do), race conditions could occur where timers were not triggered exactly on time. Using fake timers in jest instead hopefully solves the problem.
> Fixing flakyness in mocked setTimeout() calls

- src/altinn-app-frontend/src/features/form/containers/GroupContainer.tsx
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- src/altinn-app-frontend/src/utils/formLayout.ts
Open by default "first" and "last" is also broken by filters. In order to fix this the saga doing the open by default also needs to compute the `filteredIndexList` like the GroupContainer does. This function has been moved out of the component so that both the saga and the GroupContainer can use the same implementation.
~~I tried to make a general function, but the existing implementation did not make complete sense to me. It did not seem like it would work as documented, but by trying to reimplement it differently it broke some cypress tests.~~
The issues related to filters are documented here: https://github.com/Altinn/app-frontend-react/issues/339#issuecomment-1286624933
- #569 
- ~~Relevant automated test added (if you find this hard, leave it and we'll help out)~~
- ~~User …
> Fixed openByDefault to use filter

- src/altinn-app-frontend/src/common/hooks/useProcess.ts
The `startInitialDataTaskQueue` action is dispatched twice (creating a rush of more actions and requests than we need) because the hook dependencies had changed in some properties that wasn't read here. Moving the specific props out to their own variables.
- #511 (this _might_ be the root cause for that bug, but testing that hypothesis remains)
- #575
> Fixing duplicate startInitialDataTaskQueue action

- src/altinn-app-frontend/src/features/form/containers/PanelGroupContainer.tsx
- src/altinn-app-frontend/src/features/form/layout/formLayoutSlice.test.ts
- src/altinn-app-frontend/src/features/form/layout/formLayoutSlice.ts
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- src/altinn-app-frontend/src/shared/resources/language/fetch/fetchLanguageSagas.test.ts
- src/altinn-app-frontend/src/shared/resources/options/fetch/fetchOptionsSagas.test.ts
- src/altinn-app-frontend/src/shared/resources/options/fetch/fetchOptionsSagas.ts
- src/altinn-app-frontend/src/shared/resources/options/optionsSlice.ts
- src/altinn-app-frontend/src/shared/resources/textResources/fetch/fetchTextResourcesSagas.test.ts
- src/altinn-app-frontend/src/utils/sagas.ts
- src/altinn-app-frontend/src/utils/validation/validation.ts
When looking into why cypress tests were failing sometimes, I found that request/response delays (or some other race condition) could lead to the `repeatingGroups` state not being correctly initialized _after_ fetching layouts and _before_ fetching options. This lead to the `likert.js` cypress test sometimes failing, as the likert component never got the correct options to display (since the likert repeating group component was not in `repeatingGroups` when the options were fetched). Setting this state to null after a layout re-fetch and making the options saga wait until it is not-null makes this more stable without having to explicitly declare which sagas we rely on finishing first.
- #574
> Stabilizing fetch options saga

- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupTable.tsx
Made the table header in repeating groups get the same alignment as the cells in the table body.
- #587 
- ~~Relevant automated test added (if you find this hard, leave it and we'll help out)~~
- ~~User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~
> Fix repeating group header alignment

- src/altinn-app-frontend/src/components/custom/CustomWebComponent.tsx
Fix issue with `hidden="false"` sent to custom (web) component. This was causing browser to interpret that `hidden` was set on the html element, thus hiding it.
Solved by setting the `hidden` logic in the `CustomWebComponent` react component.
#592
> extract hidden prop for custom components

- src/altinn-app-frontend/src/components/presentation/Header.tsx
Make sure progress circle is not wrapping
If header title is too long, the progress circle wraps
by setting nowrap and alignItems center, this looks a bit better
- none
> fix: make sure progress circle is not wrapping

- src/altinn-app-frontend/src/components/summary/MultipleChoiceSummary.tsx
- src/altinn-app-frontend/src/components/summary/__snapshots__/MultipleChoiceSummary.test.tsx.snap
See that 3.1 (`"type": "Checkboxes"`) has the wrong font weight on summary page.
> Make MultipleChoiceSummary match styling of normal summary

- src/altinn-app-frontend/src/utils/databindings.test.ts
- src/altinn-app-frontend/src/utils/databindings.ts
@StianVestli found a bug where old-style dynamics did not evaluate correctly after #546 was merged, as empty string values deep inside objects were deleted in the old `flattenObject` implementation, but that quirkyness was not carried over in #546. That caused the newer code to return an empty string (as it should be) to the conditional rendering rule function, which caused it to hide a Paragraph component that did not hide before. Breaking changes should only be released in new major versions (see #339).
- #546
- #339
> Re-introducing brokenness in flattenObject

- .github/scripts/release.sh
- .github/workflows/release.yml
- schemas/json/component/number-format.schema.v1.json
- schemas/json/layout/layout-sets.schema.v1.json
- schemas/json/layout/layout.schema.v1.json
- schemas/json/layout/layoutSettings.schema.v1.json
Currently there are [multiple open PRs in the CDN repo](https://github.com/Altinn/altinn-cdn/pulls), and these 'never' seem to be merged, and most don't have privileges to merge them. Adding to that, functionality (most often implemented in this repo first) is what makes changes to these schemas necessary. Because of this, moving the schemas here is obviously better - and we can roll out changes to them at the exact same time as we release new versions of app-frontend.
Of note here:
- Rewriting most of the release procedure to a bash script we can test locally, instead of having to rely on testing-in-production (see #470 and the related issues!)
- History has been imported from the CDN repo, and the following PRs have been merged along with that history:
- …
> Moving JsonSchemas into this repo

- .github/workflows/cypress.yml
- .github/workflows/unit-tests.yml
In #623, the unit tests run using github actions, although they're not needed (there are no changes to unit-testable code). This change limits the test so they only run when there are changes to `src/` or the unit-test workflow. This also fixes the wrong path after I renamed the cypress workflow.
- #623
> Making unit tests run only when there are changes in `src/`

- schemas/json/component/number-format.schema.v1.json
Since `react-number-format` v5, the split between NumericFormat (thousand-separator, suffix, etc.) and PatternFormat (format, mask, etc.) is more explicit. For backwards compatibility, our implementation ignores this and figures out which component to use based on the props provided. In order to make it easier to set up number-formatting I have updated the schema so that you can either provide props only for NumericFormat, or only for PatternFormat. Additionally, when using PatternFormat, the `format`-prop is required, this can now be enforced in the schema, since there are effectively two sets of allowed properties with their own restrictions.
At first, all properties are valid:
If you add `format`, it will now only match the PatternFormat-props:
It will also inform that `format` is …
> Schema: Require either numeric or pattern format

- src/altinn-app-frontend/src/utils/formLayout.ts
The group with panel + groupReference didn't get the correct component ID set, making it so that hiding the component did not work properly.
- closes #599
> Fixing panel with groupReference when used inside repeating group

- src/altinn-app-frontend/__mocks__/initialStateMock.ts
- src/altinn-app-frontend/src/components/GenericComponent.tsx
- src/altinn-app-frontend/src/components/message/ErrorReport.test.tsx
- src/altinn-app-frontend/src/components/summary/SummaryComponent.test.tsx
- src/altinn-app-frontend/src/features/form/containers/Form.test.tsx
- src/altinn-app-frontend/src/features/form/containers/GroupContainerLikertTestUtils.tsx
- src/altinn-app-frontend/src/features/form/data/formDataTypes.ts
- src/altinn-app-frontend/src/features/form/data/submit/submitFormDataSagas.ts
- src/altinn-app-frontend/src/features/form/data/update/updateFormDataSagas.ts
- src/altinn-app-frontend/src/features/form/dynamics/conditionalRendering/conditionalRenderingSagas.ts
- src/altinn-app-frontend/src/features/form/rules/check/checkRulesSagas.ts
- src/altinn-app-frontend/src/features/form/validation/singleField/singleFieldValidationSagas.test.ts
- src/altinn-app-frontend/src/features/form/validation/singleField/singleFieldValidationSagas.ts
- src/altinn-app-frontend/src/features/form/validation/validationSlice.test.ts
- src/altinn-app-frontend/src/features/form/validation/validationSlice.ts
- src/altinn-app-frontend/src/shared/containers/Presentation.test.tsx
- src/altinn-app-frontend/src/types/index.ts
- test/cypress/e2e/integration/app-frontend/dynamics.js
- test/cypress/e2e/support/app-frontend.js
This change removes validation messages when fields are hidden. This is sub-optimal, as validations should also be hidden along with fields - but implementing such a change is quite a bit riskier (since every location working with validations would have to take into consideration if the validation messages should be hidden or not).
This change is a bit large because:
- It changes the 'single field validation' functionality to pass data/dependencies through other actions instead of relying on global redux state being set in `GenericComponent` which magically gets read by the single field validation action later. That was tied to only being able to work on one field at a time, and it was non-obvious which actions could lead to single-field validation.
- In addition to making sure validation …
> Removing validation messages when hiding fields using dynamics

- src/altinn-app-frontend/src/features/expressions/index.ts
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/component/in-nested-group2.json
- src/altinn-app-frontend/src/features/expressions/shared.test.ts
- src/altinn-app-frontend/src/features/expressions/types.ts
- src/altinn-app-frontend/src/features/expressions/validation.ts
Syncing tests with backend. Adding the `in-nested-group2.json` test breaks, as `"14"` is not equal to `14`. The fundamental problem here was that the `component` function was defined as returning `string`, so types would be cast to string no matter what they were. Introducing an `any` type that avoids casting (which also fixes the peculiarity of the `if` function that required some arguments - and the return type - not to be cast).
- #355
> Expressions: `any` type and shared tests sync

- src/altinn-app-frontend/src/features/expressions/index.ts
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/not/not-changes-notNull-to-false.json
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/not/not-changes-null-to-true.json
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/not/not-errors-on-numbers-not-0-or-1.json
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/not/not-errors-on-two-arguments.json
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/not/not-errors-on-zero-arguments.json
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/not/not-erros-on-two-arguments.json
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/not/not-handles-numeric-zero-as-false.json
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/not/not-inverts-false.json
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/not/not-inverts-true.json
This adds a `not` function. Tests written by	 @ivarne (slightly modified to fit the common error message when argument length is wrong)
- #630
> Expressions: Adding `not` function

- sonar-project.properties
- src/.eslintrc.json
As discussed on Slack. Disabling the complexity check from SonarCloud locally, as it's more of an annoyance than a big help. It is also annoying to have these bugging us on every PR here on GitHub. Having the check on sonarcloud.io is more than enough.
- #341
> Disabling local/github complexity warning

- src/altinn-app-frontend/src/utils/databindings.test.ts
- src/altinn-app-frontend/src/utils/databindings.ts
- src/altinn-app-frontend/src/utils/formLayout.ts
Co-authored-by: Magnus Revheim Martinsen <mrmartinsen.96@gmail.com>
Since updating the flattenObject function, empty repeating groups get added to the formData object like this: `'Innflytter.TidligereBosteder': ''`. If there are elements in the repeating groups this does not happen. This is because `[].toString() = ''`. This then causes a problem inside `getRepeatingGroups`: since:
```typescript
if (groupFormData && groupFormData.length > 0) { // Passes this check
const maxIndex = getMaxIndexInKeys(groupFormData);
if (maxIndex !== -1) { // Fails this check
```
Results in the group not being added to `uiConfig.repeatingGroups`.
Which again is the cause of the bug @Magnusrm described about deleting elements.
> Fix delete bug in repeating groups

- src/altinn-app-frontend/package.json
- src/altinn-app-frontend/src/components/base/ButtonComponent/GoToTaskButton.tsx
- src/altinn-app-frontend/src/components/base/ButtonComponent/SaveButton.tsx
- src/altinn-app-frontend/src/components/base/ButtonComponent/SubmitButton.tsx
- src/altinn-app-frontend/src/components/base/ButtonComponent/WrappedButton.tsx
- src/altinn-app-frontend/src/components/base/PrintButtonComponent.tsx
- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupTable.tsx
- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupsEditContainer.tsx
- src/altinn-app-frontend/src/features/instantiate/containers/InstanceSelection.tsx
- src/shared/src/components/molecules/AltinnMobileTableItem.test.tsx
- src/shared/src/components/molecules/AltinnMobileTableItem.tsx
- src/shared/src/components/molecules/DeleteWarningPopover.tsx
- src/shared/src/theme/commonTheme.tsx
- src/yarn.lock
- test/cypress/e2e/integration/app-frontend/group.js
- test/cypress/e2e/integration/app-frontend/message.js
- test/cypress/e2e/pageobjects/app-frontend.js
Changes the MUI IconButtons in repeating groups to buttons from the design system. 
- Changed delete and edit button into design-system buttons.
- Updated design-system buttons used in WrappedButton component, PrintButton component and DeletePopover component
- #439
> Implement design system button into repeating groups

- src/altinn-app-frontend/src/components/base/DatepickerComponent.test.tsx
- src/altinn-app-frontend/src/components/base/DatepickerComponent.tsx
- src/altinn-app-frontend/src/utils/dateHelpers.ts
Just a small change to fix the date-pickers weird appearance (mostly background-color and font). Also did the border-radius, focus styles and icon color.
Before:
After:
> Fix date-picker appearance to match other components design

- schemas/json/layout/layout.schema.v1.json
- src/altinn-app-frontend/setupTests.ts
- src/altinn-app-frontend/src/components/custom/CustomWebComponent.test.tsx
- src/altinn-app-frontend/src/components/custom/CustomWebComponent.tsx
This bug was caused by React elements being passed to a component, which tried to JSON serialize the object. Solved by converting react elements to static HTML before passing them to the web component.
The inclusion of `react-dom/server` increases the bundle size from `2.87 MiB` to `2.93 MiB`.
- closes #596
> Custom web component: Converting React elements to HTML

- .github/scripts/release.sh
The release script still fails, and it apparently wasn't failing because of my name before (but rather because `--author` is broken when committing without a default author).
- #655
> Yet another release script fix

- src/altinn-app-frontend/src/features/expressions/index.ts
A `null` here is invalid according to JsonSchema, but it seems Studio puts in a `null` anyway. Adding test-case by putting a `null` in one of the components in `frontend-test`.
- #{issue number}
> Bugfix: Crash when `null` in `textResourceBindings`

- .github/pull_request_template.md
- .github/release.yml
I find that the default PR template is not very specific to what we do in this project. Two of the tasks ('your code builds clean' and 'all tests run green') are not needed at all - these things are tested automatically.
This PR template is a lot more specific, and contains a lot more tasks, but I also tried to structure them in a way that makes it so that each 'group' could be interpreted as a radio group, and where at least one checkbox could be checked for any type of PR. For example, there is a big difference between not having ticked off the 'I added documentation for this' checkbox and a change not _needing_ any documentation changes.
@Magnusrm @bjosttveit Do you have any wants, wishes, comments or do you dislike the verbosity of this PR template?
> Improving the PR template

- test/cypress/e2e/support/app-frontend.js
- test/cypress/e2e/support/index.d.ts
- test/cypress/e2e/support/navigation.js
Hopefully fixing #667 by injecting a redux action instead of relying on a request to be intercepted. This _might_ need chagnes in the `frontend-test` app, but I'll let the tests run first without any changes to see if it works without.
- closes #667
- Sprint board
> Removing `go-to-task` trick in Cypress tests

- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- src/altinn-app-frontend/src/utils/validation/validation.ts
- test/cypress/e2e/integration/app-frontend/group.js
Added a function to `validation.ts`: `filterValidationsByRow`. This is used to check validation errors on only the current row when trying to save the row, even with `triggers=validation`. It is also used to filter out serverValidations when using `triggers=validateRow`.
- #653 
- ~~User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~
> Fix saving row with triggers=validation

- src/altinn-app-frontend/src/components/summary/SummaryComponent.tsx
- src/altinn-app-frontend/src/features/form/containers/Form.test.tsx
- test/cypress/e2e/integration/app-frontend/components.js
- test/cypress/e2e/integration/app-frontend/dynamics.js
- test/cypress/e2e/integration/app-frontend/formatting.js
- test/cypress/e2e/integration/app-frontend/likert.js
- test/cypress/e2e/integration/app-frontend/mobile.js
- test/cypress/e2e/integration/app-frontend/options.js
- test/cypress/e2e/integration/app-frontend/prefill.js
- test/cypress/e2e/integration/app-frontend/rules.js
- test/cypress/e2e/integration/app-frontend/summary.js
- test/cypress/e2e/integration/app-frontend/tabbing.js
- test/cypress/e2e/integration/app-frontend/texts.js
- test/cypress/e2e/integration/app-frontend/validation.js
- test/cypress/e2e/support/index.d.ts
- test/cypress/e2e/support/navigation.js
When a component is hidden via dynamics/expressions, the relevant summary component should be hidden as well.
- closes #503
- Sprint board
> Hiding Summary components when original component is hidden

- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- src/altinn-app-frontend/src/utils/layout/hierarchy.ts
- When using `triggers=["validateRow"]` the rowIndex will now be sent to the server for validations. Docs have been updated to reflect this.
- No longer filters out server-validations not related to the current row on validateRow. This was the behaviour only a few days ago, and has been changed back since it is totally legitimate to add validation errors outside of the current group row. The developer is now expected to use the rowIndex in servervalidations to deal with this if necessary. Not really a breaking change, as the validateRow trigger is basically brand new.
- Previously, the group validation trigger would not dispatch an update to validations unless there were new errors present. This was a problem because the server could send back validations that had been fixed, and they …
> Give server rowIndex for validateRow trigger

- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/dataModel/array-is-null.json
- src/altinn-app-frontend/src/features/expressions/shared-tests/functions/dataModel/null-is-null.json
These lookups should return `null` as long as we don't have support for these data types in expressions (yet).
- https://github.com/Altinn/app-lib-dotnet/pull/99
- https://github.com/Altinn/altinn-studio-docs/pull/749
- Sprint board
> Expressions: Tests for `dataModel` lookups against arrays and null

- src/altinn-app-frontend/src/components/base/FileUpload/FileUploadComponent.tsx
- src/altinn-app-frontend/src/components/base/FileUpload/FileUploadWithTag/FileListComponent.tsx
- src/altinn-app-frontend/src/components/base/FileUpload/shared/DropzoneComponent.tsx
- src/altinn-app-frontend/src/components/base/FileUpload/shared/render.tsx
- src/altinn-app-frontend/src/components/base/ImageComponent.tsx
- src/altinn-app-frontend/src/components/summary/EditButton.tsx
- src/altinn-app-frontend/src/components/summary/__snapshots__/MultipleChoiceSummary.test.tsx.snap
- src/altinn-app-frontend/src/components/summary/__snapshots__/SummaryGroupComponent.test.tsx.snap
- src/altinn-app-frontend/src/features/form/containers/RepeatingGroupTable.tsx
- test/cypress/e2e/integration/app-frontend/wcag.js
- test/cypress/e2e/pageobjects/app-frontend.js
- test/cypress/e2e/support/wcag.js
Enabling most wcag tests, but disabling tests because 2 SVGs on the group page seems to be missing [alt-attributes/title-tags](https://dequeuniversity.com/rules/axe/4.5/svg-img-alt?application=axeAPI). Passing the rest over to @Magnusrm (I tried adding `title=''` to these icons, but I've scratched my head on why that didn't work for too long now..
- https://github.com/Altinn/altinn-studio/issues/9273
- Sprint board
> Enabling automatic WCAG tests, fixing some issues 

- src/altinn-app-frontend/src/features/form/components/HelpTextContainer.tsx
- src/shared/src/components/AltinnPopover.tsx
This issue was caused by the popover set to close `onBlur`. Clicking a link inside the popover whould cause `onBlur` to be called and would close the popover, which in some cases, could cause the link not to open. To fix this, the popover itself no longer has an onblur, but only its parent (which checks if the element gaining focus is inside or not). Additionally, the mui popover manages its focus in a kind of annoying way, hence, the new useEffect to deal with this.
- closes #705 
- Sprint board
> Clicking links in help text pop-up causes it to close

- src/altinn-app-frontend/src/features/form/layout/formLayoutSlice.ts
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.test.ts
- src/altinn-app-frontend/src/features/form/layout/update/updateFormLayoutSagas.ts
- test/cypress/e2e/integration/app-frontend/calculate-page-order.js
- test/cypress/e2e/pageobjects/app-frontend.js
Experimental fix for the referenced navigation issue. Unsure if this fixes the problem, but it should/could be an improvement.
What this does, in a nutshell:
1. Changing the way we wait before fulfilling navigation to the next page until data is saved. Using `waitFor` instead of saga logic. Since the saga has two `take` calls, I suspected it might take an entirely different (previously triggered?) action in the queue.
2. If we forcibly navigate to another page because the current one is hidden (see #698), skip all logic and just navigate to that page instantly.
3. Useless unit tests for the now removed `watchUpdateCurrentViewSaga` has been removed 
4. Nice-to-have: Scroll to the top when navigation has been fulfilled.
- closes #712 …
> Possibly fixing navigation issue

- src/altinn-app-frontend/src/components/base/HeaderComponent.tsx
- src/altinn-app-frontend/src/components/summary/HeaderSummary.tsx
- src/altinn-app-frontend/src/components/summary/SummaryComponentSwitch.tsx
Headers look ugly when referenced in a `"type": "Summary"` component and the `Edit` button shows up by default.
This PR makes a custom view for a header component.
- Sprint board
> Improve the display of headers when referenced in summary

- .vscode/extensions.json
There were a lot of recommended extensions in the project that are not really necessary for pure frontend react development like csharp etc. Only kept the ones that are actually needed.
> Remove unnecessary extension recommendations for vs-code

- .eslintrc.json
- schemas/json/layout/layout.schema.v1.json
As proven in #734, ending a component ID with `-5` (or any `<dash><number>`) may cause trouble. Since we add state like that when components are used inside repeating groups, weird stuff will happen if you provide those kinds of IDs yourself. Since it's a very large undertaking to fix this problem in app-frontend right now, we should at least warn developers about this when they edit their layouts in vscode.
- closes #734
- Sprint board
> Showing validation error in vscode when using invalid IDs for components

- src/components/summary/SummaryGroupComponent.tsx
Switched to using `nodesInLayout` to get all children of the group component to check against `formValidations`  properly. I'm not sure if tests are relevant here, as i do not know exactly what caused empty validation objects being left in `formValidations` (causing the old code to show errors), only that it happened quite a lot.
- closes #701
- Sprint board
> Fix `SummaryGroupComponent` showing non-existing validation errors

- schemas/json/layout/expression.schema.v1.json
Also widening the types to allow for castable types.
- Sprint board
> Adding missing `not` function to expresions JsonSchema

- src/features/expressions/shared-tests/functions/component/hidden-in-non-repeating-group.json
- src/features/expressions/shared-tests/functions/component/visible-in-non-repeating-group.json
- src/features/form/dynamics/conditionalRendering/conditionalRenderingSagas.ts
As discussed in #503, summaries for components in non-repeating groups that are hidden, should _also_ be hidden. I started to implement this, but it turned out possibly way easier than I anticipated. Opening a PR to see if the tests pass. Needed parts (especially cypress tests for the summary components) are stil. missing.
- closes #503
- Sprint board
> Hiding components in hidden groups/repeating groups

- src/utils/validation/validation.test.ts
- src/utils/validation/validation.ts
The problem seems to be that when the validations are mapped to the redux store format using `mapDataElementValidationToRedux`, it will sometimes call `mergeComponentValidations` as part of this process. This strips away the *FIXED* validations by trying to remove the errors that are supposed to be fixed. However, in this step of the process we are not yet looking at existing validation errors, so it will simply strip away the *FIXED* validations before we actually merge with the existing validations. I therefore added a `fixValidations` option (`default=true`) to the merge-functions so that it is possible to merge without applying fixed validations and simply keeping them around. This option is then set to `false` in `mapDataElementValidationToRedux`.
This seems to fix the issue in …
> Fix *FIXED* bug

- src/features/form/components/HelpTextContainer.tsx
In #708 a `div` element was introduced, which caused the icon to be a block-level element. Fine for those wrapping it in a `display: flex`, but caused a line-break everywhere else.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1671699864018289
- Sprint board
> Fixing unintended line-break before help-text icon

- src/components/summary/SummaryComponent.tsx
After giving `Header` components a custom look in https://github.com/Altinn/app-frontend-react/pull/725 I got new complaints about the blue line under the header.
There is an existing config `display.hideBottomBorder` (introduced in https://github.com/Altinn/app-frontend-react/pull/489 without docs) that can be set on `Summary` components, to remove the line. Personally I think removing the line should be default for headers, but it's in a different component, so a `if(component.type == "Summary")` would be needed in another file, and I think we should find better solutions (eg. a `const hideBottomBorder = component.hideBottomBorder ?? component.componentTypeDefaults.summary.display.hideBottomBorder`).
This PR removes the extra spacing that is required for the blue dashed line when the …
> When a summary component sets display.hideBottomBorder we don't need space for a border

- src/utils/appMetadata.ts
- src/utils/validation/runClientSideValidation.ts
- src/utils/validation/validation.ts
- test/e2e/fixtures/texts.json
- test/e2e/integration/app-stateless-anonymous/validation.ts
- test/e2e/support/start-app-instance.ts
The validation logic did not fetch the correct data type, and caused the JsonSchema to be undefined, crashing when triggering `validatePage`.
- closes #776
- Sprint board
> Fixing `validatePage` on stateless apps

- src/features/form/layout/formLayoutSlice.ts
- src/features/form/layout/update/updateFormLayoutSagas.test.ts
- src/features/form/layout/update/updateFormLayoutSagas.ts
- test/e2e/integration/app-frontend/summary.ts
Adding a test for the functionality described in #503. When adding this test, I found a bug where my prefill-checkboxes (which uses server-side code to add rows to the repeating group) did not correctly re-calculate hidden fields (because it did not call `checkIfConditionalRulesShouldRun` after re-calculating repeating groups). Fixing that as well. 
- closes #503
- Sprint board
> Adding test for hidden components in group summary + bugfix

- package.json
- src/layout/Map/MapComponent.tsx
- src/layout/Map/MapComponentSummary.tsx
- src/layout/Map/MapIcons.ts
- yarn.lock
When upgrading the design system to v0.25.13, because of https://github.com/Altinn/altinn-design-system/pull/250, some changes are needed to the map component for it to still load images (such as the marker icon).
These changes are needed in order for the design system to be easier to use for others, such as OED (as they don't need the map component, and they don't want to have to support bundling `.png` image files in their webpack configuration just for that component which they don't need).
- https://github.com/Altinn/altinn-design-system/pull/215
- https://github.com/Altinn/altinn-design-system/pull/216
- https://github.com/Altinn/altinn-design-system/pull/250
- …
> Design system v0.25.13 with map component changes

- src/features/expressions/index.ts
- src/features/expressions/shared-tests/functions/instanceContext/only-dict.json
- src/features/expressions/shared-tests/functions/instanceContext/partyTypeOrg.json
- src/features/expressions/shared-tests/functions/instanceContext/partyTypePerson.json
- src/features/expressions/shared-tests/functions/instanceContext/partyTypeSelfIdentified.json
- src/features/expressions/shared-tests/functions/instanceContext/partyTypeUnknown.json
- src/features/expressions/shared-tests/functions/instanceContext/simple-lookup-equals.json
- src/features/expressions/shared-tests/functions/instanceContext/simple-lookup-is-null.json
- src/features/expressions/shared-tests/functions/instanceContext/simple-lookup.json
- src/features/expressions/shared.test.ts
- src/features/expressions/shared.ts
- src/types/shared.ts
- src/utils/instanceContext.test.ts
- src/utils/instanceContext.ts
- src/utils/layout/hierarchy.test.ts
Add property `["instanceContext", "instanceOwnerPartyType"]` so that dynamic expression can reference the type of instance owner.
- closes https://github.com/Altinn/app-frontend-react/issues/794
- https://github.com/Altinn/altinn-studio-docs/pull/790
- Sprint board
> `instanceOwnerPartyType` lookup in expressions

- src/utils/options.ts
When using a repeating group as a source for options, there was a bug where adding a new element to the source repeating group would cause a crash because of a missing null check. This is because it would iterate over the length of the repeating group, and when a new element is added, the length (repeatingGroupIndex) is incremented before any new data is added. This caused a `cannot read properties of undefined` exception. Fixed by a simple null check on the option to be added.
Confirmed that the fix works in `ra0244-01`.
- https://altinn.slack.com/archives/C02EVE4RU82/p1672816833823229
- Sprint …
> Null check empty optionLabel from repeating group

- src/features/pdf/PDFView.tsx
- src/index.css
- src/shared/containers/ProcessWrapper.module.css
- src/shared/containers/ProcessWrapper.tsx
Made some changes to `ProcessWrapper` to make it easier to preview PDF while developing. Now there are three possible states of PDF rendering depending on the query parameter `?pdf`.
- `?pdf` is not defined: Only form is rendered as normal.
- `?pdf=1`: used for generating PDF. Only `PDFView` is rendered to keep PDF-generation fast.
- `?pdf=preview`: both form and `PDFView` are rendered at the same time, but form is hidden and `PDFView` is visible when in print-mode, and opposite if not in print mode (using css). This can potentially be very slow, and is only meant for development use.
Does this seem like a good solution? It makes it much easier to modify form data and quickly check how this changes the PDF without constantly changing the query-parameter back and fourth as I have been …
> Easier preview for PDF development

- src/features/pdf/AutomaticPDFLayout.tsx
- src/features/pdf/PDFView.tsx
- src/features/pdf/index.d.ts
- src/utils/urls/appUrlHelper.ts
PDF view now fetches PDF format from backend and uses this for `excludeComponents` and `excludedPages`. If this fails, it will use what it has in `layoutSettings`. If `IPdfFormatter` is not used, then the backend simply returns whatever is in the static `Settings.json` file. When a custom layout is used, it will not bother fetching pdf format from the backend as this is not used in that case.
When in pdf preview mode (`?pdf=preview`), it will fetch the pdf format whenever the formData is saved so that any dynamic rules based on the formData is up to date and ready for preview.
Tested a lot on frontend-test app, and seems to work well both for `?pdf=preview` and `?pdf=1` (only loads format once).
Also tested on my sogndal app which does not use layout sets and it fetches fine. (except that …
> Fetch PDF format from backend

- src/features/form/containers/GroupContainer.tsx
- src/features/form/containers/RepeatingGroupTable.tsx
- src/features/form/containers/RepeatingGroupsEditContainer.tsx
Was made aware that `mode: showAll` did not display properly, it did not fill the full width. This lead me down a rabbit hole of many display issues related to using different modes in both regular and nested repeating groups. The only real issue that could potentially use a cypress test is that the "save and close" and "save and next" buttons were not hidden in `mode: showAll`.
- n/a
- Sprint board
> Fixed many issues with different modes of repeating groups

- src/components/AltinnSpinner.test.tsx
- src/components/AltinnSpinner.tsx
- src/language/texts/nb.ts
- src/language/texts/nn.ts
AltinnSpinner should be accessible by implementing correct roles and aria-*. If SpinnerText is not provided as a prop I have implemented a fallback to "Laster innhold" as an aria-label which is only presented to screen readers.
Improved validation message for postal code to be more informative.
- closes #25 
- Sprint board
> WCAG: AltinnSpinner should accessibile and validation errors onBlur should be informative

- schemas/json/layout/expression.schema.v1.json
The expression schema contained a loose type reference that caused error messages when referencing the `lessThan`, `lessThanEq`, `greaterThan` and `greaterThanEq` functions (at least). After loosening the types and introducing optional `strict-<type>` definitions, the definitions for these functions were impossible to validate.
As an example, both of these examples failed:
`["lessThan", 5, 500]`
`["lessThan", ["dataModel", "something"], "80"]`
This was because the two arguments could match either a string or number, but each individual type (string and number) was at some point widened to also include the other type (number and string), so multiple paths contained valid solutions. …
> Expression schema: Fixing overlapping type reference

- src/features/form/containers/RepeatingGroupTable.tsx
Continuing with the new `getComponentType()`, I used this to not show irrelevant components in table headers. This hides both `ComponentType.Presentation` components as well as nested groups which does not have any form data to show in the table anyway, and would show up as `Elementer` with empty data.
Only `ComponentType.Form` is actually valid since only they have formData to put in the table. Previously, you would have to manually remove these by specifying `tableHeaders`.
- n/a
- Sprint board
> Repeating groups: Exclude non-form components from table header

- schemas/json/layout/layout.schema.v1.json
The `pageBreak` property was accidentally place outside of the `properties` of the `component` definition.
> Fix `pageBreak` property in component schema

- src/features/form/layout/formLayoutSlice.ts
[This issue](https://altinndevops.slack.com/archives/C045EB3JA9X/p1675197258028169) was caused by the saga not taking into account that the `components` property of `Settings.json` could be undefined, and so it would not initialize it to an empty list and would therefore assume that excludedComponents had not loaded yet.
> PDF: Fix issue when components are undefined in settings

- src/utils/stringHelper.test.ts
- src/utils/stringHelper.ts
The nifty `capitalizeName` function, which is used in `PartySelection`, caused an app to crash when the new test data from Tenor contained a name with a space on the end of the string. Fixing this, and adding a unit test for the function.
- https://altinn.slack.com/archives/C02ESDSGPN1/p1675241690237699
- Sprint board
> Preventing crash on Party selection for users with names that contains abnormal spaces

- src/features/form/containers/RepeatingGroupTableRow.tsx
- src/features/form/containers/RepeatingGroupsEditContainer.tsx
Added an `aria-expanded` attribute to the edit button in repeating groups that is set to true when the group row is open for editing. It also sets `aria-control` to the `RepeatingGroupsEditContainer`, but only when the element is open, since it is not present in the DOM when closed.
- closes #898 
- Sprint board
> WCAG: Added `aria-expanded` to repeating group edit button

- test/e2e/support/app-frontend.ts
- test/e2e/support/global.d.ts
- test/e2e/support/start-app-instance.ts
I found that Cypress tests no longer worked locally when I'm running apps in the http-mode (only one app at a time), as the app selector dropdown is gone now.
- Sprint board
> Supporting Cypress tests in newer LocalTest with http mode

- src/features/form/containers/RepeatingGroupTableRow.tsx
This came up when testing this: https://github.com/Altinn/app-frontend-react/pull/900. Made it so that popover is not present unless alertOnDelete is true. Apparently the popover component itself was responsible for setting these attributes on the button.
- https://github.com/Altinn/app-frontend-react/issues/898
- Sprint board
> WCAG: Fixed `aria-expanded` on delete button without popover

- schemas/json/layout/layout.schema.v1.json
Fixing the very strict (too strict) regex that disallowed our automatically generated UUIDs in some cases. It should only disallow endings with `-<num>` where <num> is a number with 5 or less digits.
- https://altinn.slack.com/archives/C02EVE4RU82/p1676032215952529
- #758
- Sprint board
> Fixing component ID regex to allow our UUIDs

- src/components/summary/EditButton.tsx
- src/components/summary/__snapshots__/SummaryGroupComponent.test.tsx.snap
- src/layout/Checkboxes/__snapshots__/MultipleChoiceSummary.test.tsx.snap
- test/e2e/integration/app-frontend/summary.ts
Replaced the button with the button from the design system.
- closes #909 
- Sprint board
- Labels
> Summary edit button accessibility 

- schemas/json/layout/layout.schema.v1.json
- src/layout/NavigationBar/NavigationBarComponent.test.tsx
- src/layout/NavigationBar/NavigationBarComponent.tsx
- src/layout/NavigationBar/types.d.ts
- test/e2e/integration/app-frontend/components.ts
- test/e2e/integration/app-frontend/mobile.ts
Compact navbar feature – option to configure navbar as compact.
Added a boolean type property “compact” to the layout component NavigationBar. Gives app builder the option to configure if they want to make the navbar appearance as a menu, regardless of the width of the viewport. If this is the case, "compact" is set to true in the layout: ``
{
"id": "nav1",
"type": "NavigationBar",
"compact": true
}
``
NB! This must be configured on each layout page. Maybe on a later stage this can be implemented in Altinn Studio.
- closes #906  …
> Give dev a compact navbar option (#906)

- src/components/organisms/AltinnAppHeaderMenu.tsx
Removed fixed position (right: 25) on user menu. This means that the user menu follows the position of the icon, regardless of the direction of the language that has been selected (left to right or right to left).
- closes #604 
- Sprint board
- Labels
> Positioning user menu based on language direction (ltr and rtl)

- src/components/summary/SummaryGroupComponent.tsx
- test/e2e/integration/app-frontend/summary.ts
It appears that the logic for excluding children in `SummaryGroupComponent` broke during a refactoring. Added a cypress test to prevent this happening again.
- closes #950 
- Sprint board
- Labels
> Bug: Fix excluded children

- src/components/message/ErrorReport.tsx
- src/layout/FileUploadWithTag/FileListComponent.tsx
- test/e2e/integration/app-frontend/validation.ts
- test/e2e/pageobjects/app-frontend.ts
This PR addresses two bugs related to file upload with tag.
- ID being displayed in error message.
- While working on the ID-bug above I encountered a second bug where the error message being duplicated if user try to save without a tag and then try to navigate to next page. 
The ID being displayed in the error message/report also includes an ascii unit. Added errorMessage function to check if this is included in the string. If that is the case a substring is returned and otherwise return string as is.
Added cypress tests to secure that this functionality doesn't break on a later stage.
For the duplicated error, I use the Map object to only display error messages that contains unique ID's for file upload elements. 
`let uniqueObjArray = [...new Map(objArray.map((item) => [item["id"], …
> Error message - remove long ID, duplication fix

- src/features/pdf/data/generatePdfSagas.ts
There was a small oversight when refactoring to using sagas that caused components to be duplicated in automatic layout. This happened because component id's are rewritten, which caused groups to include children with their original ids as they where supposed to, but also the children in the layout where included with rewritten ids as well. The solution is using the topLevelComponents function for each layout file before rewriting and merging them together, which was in the original `AutomaticLayout` file, but was changed in another refactoring leading too this oversight.
- https://altinn.slack.com/archives/C02EENC8KBR/p1677513448745799
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-u …
> PDF: Fix issue with automatic layout duplication

- src/features/form/containers/Form.tsx
- test/e2e/integration/app-frontend/validation.ts
Announce error summary in screen reader when user is blocked from continuing when clicking "next" on a page with form errors.
The "error report" component isn't present in the DOM on page load. Without taking this into account, the screen reader doesn't read the messages being displayed in the error report, without focusing.
By adding a parent div, to error component, that is present in the DOM on page load, and adding a aria-live="polite" to this parent div, the screen reader reads the messages that occurs inside the error component. [Docs for "aria-live"](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA19). 
- closes #903 
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) …
> screen reader - error report

- src/shared/components/altinnAppHeader.test.tsx
- src/shared/components/altinnAppHeader.tsx
- src/types/shared.ts
Different spelling of type organization causes the data to be inaccessible in code. In the store "organization" is used and this PR renames every instance of the word to this.
Redux store:
This is just a suggestion, but I thought it was better to provide a fix than to just create an issue.
- Sprint board
- Labels
> Rename data type to "organization" to match data in store

- src/components/summary/SummaryComponent.tsx
- src/components/summary/SummaryComponentSwitch.tsx
Fixes so that readonly correctly resolves for repeating group summary.
Tested in `krt-1230a-1` and everything resolves correctly now:
- closes #747 
- [?] No automatic tests are needed here (no functional changes/additions)
- Sprint board
- Labels
> Use resolved node in summary switch

- src/features/expressions/index.ts
- src/features/expressions/shared-tests/functions/component/distant-across-page.json
- src/features/expressions/shared-tests/functions/component/distant.json
@olemartinorg's suggested solution to #826  worked great, both for looking up components in groups on the same page and across pages. In both of these cases the component could not be found previously. The shared tests check these two cases, and both tests failed before this change. I named this case "distant" as it cannot be reached using the "closest()"-method, I could not come up with a better name 😅 
- closes #826 
- Sprint board
- Labels
> Fix component expression not finding "distant" components

- src/components/summary/SingleInputSummary.tsx
- src/components/summary/SummaryGroupComponent.tsx
- src/layout/FileUpload/AttachmentSummaryComponent.tsx
- src/layout/FileUploadWithTag/AttachmentWithTagSummaryComponent.tsx
- src/layout/Map/MapComponentSummary.tsx
This is just a very small thing that has bothered me ever since I added the empty summary text. The text saying that a summary has no data is styled differently to not be mistaken for actual user input. However, since the font is slightly smaller they no longer line up when placed in a grid. This small change corrects for that by setting the line height so the borders line up perfectly.
Before:
After:
- ~~closes #{issue number}~~
- Sprint board
- …
> Change line height in empty summary to match size

- package.json
- src/layout/FileUpload/FileUploadComponent.tsx
- src/layout/FileUploadWithTag/EditWindowComponent.module.css
- src/layout/FileUploadWithTag/EditWindowComponent.tsx
- yarn.lock
Encountered that the delete button in container "upload attachment with tag" was too large compared to other elements in the container.
Replaced the button (material ui) and the icon (font awesome) with those from our [design system](https://digdir.github.io/designsystem/?path=/docs/komponentoversikt--page) and [Aksel - NAV  ](https://aksel.nav.no/).
While I was on it, also replaced the check mark icon with the one from Aksel NAV.
Before:
After:
- …
> Attachment with tag container, replaced button from material ui with design system

- src/__mocks__/initialStateMock.ts
- src/__mocks__/profileStateMock.ts
- src/components/hooks/useDelayedSavedState.ts
- src/components/presentation/LanguageSelector.tsx
- src/components/presentation/NavBar.test.tsx
- src/features/instantiate/containers/InstantiateContainer.test.tsx
- src/layout/NavigationBar/NavigationBarComponent.test.tsx
- src/selectors/appLanguageStateSelector.test.ts
- src/selectors/appLanguageStateSelector.ts
- src/shared/components/altinnParty.test.tsx
- src/shared/components/altinnPartySearch.test.tsx
- src/shared/resources/language/fetch/fetchLanguageSagas.test.ts
- src/shared/resources/language/fetch/fetchLanguageSagas.ts
- src/shared/resources/language/languageSlice.ts
- src/shared/resources/profile/index.d.ts
- src/shared/resources/profile/profileSlice.test.ts
- src/shared/resources/profile/profileSlice.ts
- src/shared/resources/textResources/fetch/fetchTextResourcesSagas.test.ts
- src/shared/resources/textResources/fetch/fetchTextResourcesSagas.ts
- src/testUtils.tsx
selectedAppLanguage state is moved to profileState in Redux store (It made more sense to me). When the selectedAppLanguage is changed the language is saved to localStorage as before. BUT the localStorage key include the userId (New). 
I believe this is a breaking change for the users who has changed their language (For them it will default back to profile preferences). 
- closes #1005
- Sprint board
- Labels
> Selected Language stored in localstorage should be saved per user

- test/e2e/integration/app-frontend/receipt.ts
- test/e2e/support/customReceipt.ts
Added a test case for custom receipt to prevent it from unknowingly breaking again.
- https://github.com/Altinn/app-frontend-react/pull/1024
> Added test case for custom receipt

- src/utils/validation/validation.ts
A developer might write
```json
"dataModelBindings": {
"simpleBinding": null,
}
```
and it seems wrong that it should crash frontend on validation.
This is obviously guarded against with json schema, so feel free to discard.
- Sprint board
- Labels
> Add a simple null check to validation code

- src/features/form/containers/RepeatingGroupsEditContainer.tsx
**The bug:**
When _editMode_ was set to _showAll_ and _hiddenRow_ was true, the rows were rendered but as empty rows, like the image below shows.
**Expected behaviour:**
Expected the row not to be rendered at all and to be invisible.
**Solution:**
We do not expect the rows to be shown as empty rows when `hiddenRow` is true, they should not be rendered at all. This PR ensures that rows are hidden when `hiddenRow` is true regardless of the edit mode. …
> Ensure to hide rows regardless of the edit mode if the "hiddenRow" expression evaluates to true.

- package.json
- test/e2e/integration/app-frontend/calculate-page-order.ts
- test/e2e/integration/app-frontend/components.ts
- test/e2e/integration/app-frontend/dynamics.ts
- test/e2e/integration/app-frontend/formatting.ts
- test/e2e/integration/app-frontend/group.ts
- test/e2e/integration/app-frontend/hide-row-in-group.ts
- test/e2e/integration/app-frontend/list-component.ts
- test/e2e/integration/app-frontend/multipart-save.ts
- test/e2e/integration/app-frontend/options.ts
- test/e2e/integration/app-frontend/print-button.ts
- test/e2e/integration/app-frontend/rules.ts
- test/e2e/integration/app-frontend/summary.ts
- test/e2e/integration/app-frontend/tabbing.ts
- test/e2e/integration/app-frontend/texts.ts
- test/e2e/integration/app-frontend/validation.ts
- test/e2e/integration/app-stateless-anonymous/anonymous.ts
- test/e2e/integration/app-stateless/stateless.ts
- test/e2e/support/app-frontend.ts
- test/e2e/support/custom.ts
- test/e2e/support/global.d.ts
- test/e2e/support/navigation.ts
- yarn.lock
Upgrading `eslint-plugin-cypress`, which brings with it a new rule that disallows unsafe chaining. Cleaning up our unsafe chains, fixing the remaining problems.
- #1077 
- Sprint board
- Labels
> Upgrading eslint-plugin-cypress

- src/components/message/ErrorReport.tsx
If there are more than one validation error for the same component, the ErrorReport would give both list entries the same key, since it only depended on the component id. This caused fixed validations not getting removed from the list in certain cases. This change makes the key dependent on the message as well, since there can be several different validation messages on a single component that are independent from each other.
- https://altinn.slack.com/archives/C02EVE4RU82/p1681480308287159
- Changes/additions to …
> Fix: `ErrorReport` not updating properly

- src/layout/Group/SummaryGroupComponent.tsx
- src/layout/Group/__snapshots__/SummaryGroupComponent.test.tsx.snap
- src/layout/Summary/EditButton.tsx
- src/layout/Summary/SummaryBoilerplate.tsx
Added aria-label to edit button in summary page. 
This makes it easier for users with screen reader to understand which component the edit button belongs to.
- closes #1100 
- Sprint board
- Labels
> Added aria-label to edit btn in summary page

- src/utils/validation/validation.ts
A little safety feature is that I only ignore when .code and .description is different, so that user validations that uses the text code "required" isn't affected.
- Improves https://github.com/Altinn/app-frontend-react/issues/1062
- Sprint board
- Labels
> Ignore all backend validations that uses the code: "required"

- src/features/devtools/DevTools.tsx
This adds Altinn Studio to the list of hostnames that should display the devtools button in addition to `local.altinn.cloud`. Tested by @standeren .
> Enable DevTools button in Studio preview

- src/features/formData/update/updateFormDataSagas.ts
- src/layout/Datepicker/DatepickerComponent.tsx
- src/layout/Datepicker/index.tsx
- src/layout/InstanceInformation/InstanceInformationComponent.tsx
- src/utils/dateHelpers.test.ts
- src/utils/dateHelpers.ts
- src/utils/validation/runClientSideValidation.ts
- src/utils/validation/validation.test.ts
- src/utils/validation/validation.ts
Using the user's profile or the selected app language to format dates accurately. Using the appropriate language setting is crucial to ensure that dates are displayed correctly in the user's desired format.
The PR itself.
- Sprint board
- Labels
> Ensure to use the profile or selectedAppLanguage when format the dates

- src/components/message/ErrorReport.module.css
- src/components/message/ErrorReport.tsx
Resized font in list-items in error report - were too small. Also moved some material-ui to css-modules.
- Sprint board
- Labels
> fix font-size in errorReport + material-ui to css-modules

- src/utils/formComponentUtils.test.ts
- src/utils/formComponentUtils.ts
If you pass an empty string as the field key for validation the `smartLowerCaseFirst()` function crashes as this edge case was not handled. This fixes the edge case and adds a test case for it.
- https://altinn.slack.com/archives/C02ESDSC929/p1683185354761459
- Sprint board
- Labels
> Fix `smartLowerCaseFirst()` crashing

- src/__mocks__/processMock.ts
- src/features/confirm/components/ConfirmButton.tsx
- src/features/process/index.d.ts
- src/features/process/processSlice.ts
- src/layout/ActionButton/ActionButtonComponent.tsx
- src/layout/Button/ButtonComponent.tsx
- src/layout/Button/WrappedButton.module.css
- src/layout/Button/WrappedButton.tsx
When submitting the form, a submittingId is set in redux which can be checked to make sure you cannot repeatedly click the button and spamming the backend. This was not the case for standard confirmation, custom confirmation or the new action button. I now added a similar thing for process.complete, where you can set a componentId when completing the step so that we can show loading status and prevent spamming process.next.
I tested the changes in the app linked in the issue, and the action button in signing-test.
- closes #1126  …
> Fix: Confirm button spam

- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
The font size for the title in a `FieldSet` suddenly changed in the design system (by mistake). This quick-fix reverts the font size to `16px` (as it was). 
- https://altinn.slack.com/archives/C02ESDSC929/p1683632334511939
- Sprint board
- Labels
> Quickfix for checkbox/radio font size change from the design system

- src/layout/Panel/Panel.module.css
- src/layout/Panel/PanelGroupContainer.test.tsx
- src/layout/Panel/PanelGroupContainer.tsx
The use of the body textresource was omitted after updating panelgroup component to better suit the signing case. 
This PR reintroduces the use of the optional textresource in order to allow setting a body in the panelgroup when using children to specify the groups components instead of groupReference.
- closes https://github.com/Altinn/app-frontend-react/issues/1153
- Sprint board
- Labels
> Reintroduce panel body to panel groups that use children

- src/hooks/queries/useActiveInstancesQuery.ts
- test/e2e/integration/app-frontend/on-entry.ts
Sorting list of active instances before rendering instance selector (this was done before, but was probably missed during the query rewrite). Added regression test.
- https://altinn.slack.com/archives/C02ESDSGPN1/p1683879046181739
- Sprint board
- Labels
> Fixing sorting of active instance list

- package.json
- schemas/json/layout/expression.schema.v1.json
- schemas/json/layout/layout.schema.v1.json
- src/hooks/useMapToReactNumberConfig.ts
- src/layout/layout.d.ts
- src/utils/formattingUtils.test.ts
- src/utils/formattingUtils.ts
- src/utils/layout/getAllLayoutSets.ts
- src/utils/layout/schema.test.ts
- test/e2e/integration/app-frontend/formatting.ts
- tsconfig.json
Compacting the number formatting configuration, so that we save one level of depth. This way you can configure a field to: `"formatting": { "currency": "NOK" }` instead of the more verbose `"formatting": { "currency": { "valuta": "NOK" }}`. I think we can get away with having a top-level `currency` and `unit` property here, and re-use the `position` property for both `currency` and `unit`.
Also:
- Refactored the cypress test so there's less duplication of code, and hopefully clearer which format leads to which expectations in the number formatted field.
- Updated the schema, fixing the syntax error in it
- Added a unit test to make sure the schema files are valid
- #1132
- #717 …
> Compacting the number formatting configuration + schema tests

- src/components/form/MessageBanner.tsx
- src/features/instantiate/containers/InstantiationErrorPage.tsx
- src/features/language/languageSlice.test.ts
- src/hooks/useLanguage.ts
- src/language/languages.ts
- src/language/sharedLanguage.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/Address/AddressLabel.tsx
- src/layout/Grid/GridComponent.tsx
- src/layout/Group/RepeatingGroupTable.tsx
- src/layout/List/ListComponent.test.tsx
- src/layout/List/ListComponent.tsx
- src/types/shared.ts
- src/utils/textResource.ts
- src/utils/validation/validation.ts
- test/e2e/integration/app-frontend/grid.ts
This fixes two issues with Grid (also when displaying Grid rows in the repeating group table):
1. Text cells can now contain markdown (either when used directly, or when referencing a text resource key)
2. When displaying a Grid (or a nested repeating group table), the first and last cells would mistakenly add the padding for full-width extension to the cell, causing the content to be compressed into one side of the cell)
In order to fix the markdown issue, I created a new `useLanguage` hook that should make it easier to work with language/text resources. This looks inside text resources first, then finds a language key if no text resource was found. It also provides auto-completion for language keys and keeps the number of parameters to a minimum, making for a better developer experience …
> Markdown/text formatting support in Grid cells + nesting fix

- src/layout/Group/GroupContainer.tsx
Bugfixed undesirable jumping to the first field in a repeating group by doing some code-splitting to avoid "side-effects" that are focusing on the first focusable element, when a row is added initially with a useEffect-hook.
- closes #1089
- Sprint board
- Labels
> Bugfixed undesirable jumping to the first field in a repeating group

- src/layout/Grid/hierarchy.ts
- src/layout/Group/hierarchy.ts
- src/utils/layout/HierarchyGenerator.ts
- src/utils/layout/hierarchy.ts
- test/e2e/integration/app-frontend/grid.ts
Implementing proper text resource rewriting for `Grid` component rows, as it uses a non-standard way of referencing text resources (in cells, not in `textResourceBindings`). This fixes a problem reported on Slack.
- https://altinn.slack.com/archives/C02EVE4RU82/p1684823161039679
- Sprint board
- Labels
> Grid/`rowsBefore`/`rowsAfter`: Resolving text resource bindings inside repeating groups

- src/utils/validation/validation.ts
- test/e2e/integration/app-frontend/group.ts
- test/e2e/integration/app-frontend/validation.ts
- test/e2e/integration/app-stateless-anonymous/validation.ts
- test/e2e/pageobjects/app-frontend.ts
We already hide validation messages for components that are hidden, but there were validations that slipped through the cracks. In this case, JsonSchema validation for a component would still be included even if the component was hidden - this change fixes the problem.
I also took the liberty to refactor the field validation selectors we use in cypress tests - which adds a lot of changes to the PR.
- Mentioned during a meeting with `org/ssb` last week, with details and follow-up in a private Slack thread between me and @rvessb …
> Validations: Hiding validations for hidden components (JsonSchema edition)

- src/components/form/FullWidthWrapper.module.css
This makes the fullWidthWrapper css only apply to screen and not print.
Previously it would have a negative margin to the sides, and if it was on the bottom/top of its page it would also comsume bottom/top padding making it overlap with other things.
Before:
After:
> Quickfix: Panel in PDF

- schemas/json/layout/layout.schema.v1.json
- src/features/pdf/PDFView.tsx
- src/features/pdf/data/generatePdfSagas.ts
- src/layout/Group/DisplayGroupContainer.module.css
- src/layout/Group/DisplayGroupContainer.tsx
- src/layout/Group/GroupRenderer.tsx
- src/layout/Group/SummaryGroupComponent.tsx
- src/layout/Group/types.d.ts
- src/layout/Summary/SummaryComponent.tsx
Added optional groupingIndicator, line + indent, also added body text.
Anything about this that need unit/cypress testing?
I made some changes to how non-repeating groups are treated in summary to make it work a bit better. I made it so that largeGroup is true for nested non repeating groups, this will make it look more like how it does when filling out the form. I also made the bottomBorder not visible when not using summaryBoilerplate, this applies to group and grid, which have a custom rendering that makes it look better without it in my opinion. It looked very strange for non-repeating groups at least. TLDR; There were too many borders imo. 😅 
https://www.figma.com/file/Pvti3aRcOwH0k5Z7DrLznk/Arbeidsomr%C3%A5de%3A-Altinn-Studio-APPS?type=design&node-id=4745%3A110013&t=xrvnNTRiNxSh5H4u- …
> Added grouping indicator to non-repeating group

- src/components/altinnParty.tsx
- src/layout/Group/DisplayGroupContainer.tsx
This is a quick fix that adds `role=button` to the party selection items, these ones:
This has annoyed me for a while since i use [vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb) to navigate in the browser and it could not detect these as clickable since it was just a div with no role. It was likely not great to use with screen readers either.
> WCAG: Party selection buttons

- src/__mocks__/hierarchyMock.ts
- src/features/expressions/ExprContext.ts
- src/features/expressions/index.ts
- src/features/expressions/shared-tests/functions/language/should-return-profile-settings-preference.json
- src/features/expressions/shared.test.ts
- src/features/expressions/shared.ts
- src/layout/Group/DisplayGroupContainer.tsx
- src/utils/layout/hierarchy.ts
Small refactoring to improve the code by using **dataSources** instead of **AltinnWindow**.
- closes #1176 
- Sprint board
- Labels
> Refac: use dataSources instead of AltinnWindow

- src/__mocks__/formDataStateMock.ts
- src/__mocks__/uiConfigStateMock.ts
- src/features/formData/formDataSlice.ts
- src/features/formData/formDataTypes.ts
- src/features/formData/index.d.ts
- src/features/formData/submit/submitFormDataSagas.ts
- src/features/layout/fetch/fetchFormLayoutSagas.test.ts
- src/features/layout/fetch/fetchFormLayoutSagas.ts
- src/features/layout/formLayoutSlice.ts
- src/features/layout/formLayoutTypes.ts
- src/features/layout/repGroups/updateRepeatingGroupEditIndexSaga.ts
- src/features/layout/update/updateFormLayoutSagas.ts
- src/layout/Button/ButtonComponent.test.tsx
- src/layout/Button/ButtonComponent.tsx
- src/layout/Group/RepeatingGroupsTable.test.tsx
- src/layout/Group/SummaryGroupComponent.test.tsx
- src/layout/Likert/GroupContainerLikertTestUtils.tsx
- src/layout/NavigationBar/NavigationBarComponent.test.tsx
- src/layout/NavigationButtons/NavigationButtonsComponent.test.tsx
- src/types/index.ts
- src/utils/validation/validation.test.ts
- src/utils/validation/validation.ts
Removing the `autoSave` toggle. My reasons for this is:
- You have to know what you're doing to toggle it off, because it isn't documented anywhere (you had to read our code to find it).
- Nobody is using this setting, as far as I can tell (and I've downloaded every app currently in production and every app I could get a hold of that's on tt02).
- Server-side calculations stop being responsive if you toggle it off.
- There's been a notice in our code for a while asking if that setting is used at all, and everyone had to code around it hoping other changes to form saving didn't break this unknown feature.
- If you try to enable it, you might find that we only respect the setting from the _last layout file we processed_, so it would've been best to set it on every single layout file if you …
> Removing autosave functionality (not in use)

- package.json
- src/features/devtools/DevTools.module.css
- src/features/devtools/components/LayoutInspector/LayoutInspector.module.css
- src/features/devtools/components/OpenDevToolsButton/OpenDevToolsButton.module.css
- src/index.css
- yarn.lock
Only other change is removing the z-index workaround for dev-tools and adjusting the z-index of the dev tools panel. It is still not possible to set the z-index for select, but I now get the same results as before without the workaround.
> Update @digdir/design-system-react to 0.14.0

- src/layout/Summary/SummaryComponent.tsx
This quickfix fixes the formatting that broke for summary titles. 
- https://github.com/Altinn/app-frontend-react/pull/1234
> Quickfix: summary title formatting

- test/e2e/integration/app-frontend/reportee-selection.ts
I noticed that the test for doNotPromptForParty failed locally, this is because the default user in localtest only has a single valid party. I Fixed this by adding a mock party to the list of valid parties.
It also turns out that I did an upsie and forgot to remove `describe.only()`, so the other reportee-selection test was not running since #1204 was merged.
> Fix doNotPromptForParty test locally

- src/features/layout/update/updateFormLayoutSagas.ts
- test/e2e/integration/app-frontend/auto-save-behavior.ts
This will fix two of the cases for triggers on the NavigationButton. When the trigger is undefined the user is naviagted to next page. This also happens for autoSaveBehavior="OnChangePage".
Single field validation still won't work.
- closes 2/3 #1257
- Sprint board
- Labels
> Wait for save before validating autoSaveBehavior="OnChangePage"

- src/components/ThemeWrapper.tsx
- src/layout/Datepicker/DatepickerComponent.tsx
- src/layout/Datepicker/index.tsx
- src/layout/FileUpload/shared/summary.ts
- src/layout/Summary/SummaryItemSimple.tsx
- test/e2e/integration/app-frontend/components.ts
- test/e2e/support/custom.ts
- Hiding dates from the date picker in tests (these change all the time! _duh_)
- Sorting attachments shown in Summary by name (avoids randomness, improves user experience)
- Delaying setting `viewport-is-(mobile|tablet|desktop)` classes to hopefully fix some issues where the layout was not entirely rendered yet when we took a screenshot
- Making sure the error report is visible when taking a screenshot in `components:text-countdown`. This was sometimes captured, sometimes not. Changing the field should trigger validation, and should display the error report.
- Preventing focus on the submit button to sometimes change the background color for it in screenshots, giving us slight color diffs for things we didn't change
- Automated …
> Visual testing: Making screenshots less flaky

- src/layout/Grid/GridComponent.tsx
Wave reported a WCAG issue when a text cell was set to `{ "text": "" }` in a header row. This should fix the issue.
- https://altinn.slack.com/archives/C04CZ3KND6Z/p1687272343721849?thread_ts=1687259663.141289&cid=C04CZ3KND6Z
- Sprint board
- Labels
> Grid: Empty text cells should be treated the same as `{}` and `null`

- test/e2e/integration/app-frontend/hide-row-in-group.ts
More fixes. This time:
- Making sure the `preselectedOptionIndex` takes effect before taking the screenshot in `hide-row-in-group`
- #1264
- https://percy.io/700b0900/altinn-app-frontend-react/builds/28364684/changed/1576701856?browser=chrome&browser_ids=38&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=987&widths=987
- Sprint board
- Labels
> Visual testing: Making screenshots less flaky (2)

- src/components/message/ErrorReport.tsx
- src/layout/Group/RepeatingGroupTableRow.tsx
- src/utils/layout/LayoutNode.ts
- test/e2e/integration/app-frontend/validation.ts
- test/e2e/pageobjects/app-frontend.ts
Fixing a few bugs:
- When a component in a repeating group is set to `showInExpandedEdit: false` and is not editable in the table, it is implicitly hidden, so the user cannot fix any validation messages for it either. Marking this field as hidden, so that we also hide any validation messages for it. This is most likely an implementation mistake if hiding required fields (or fields with errors in them).
- Allowing an app developer to set `editInTable: false` even when using `mode: onlyTable` on a repeating group. This means that you can opt out of editing a component in the table if you want to. (These components are also implicitly hidden, but their values still appear in the table). Verified that no apps in tt02/prod currently use this setup, so this should not be breaking.
- Fixing …
> Prevent opening group for editing when clicking validation messages in some cases

- src/layout/Custom/index.tsx
- src/utils/formLayout.ts
This should allow Custom components to be rendered inside a ButtonGroup and a table (aka. `Grid` and repeating `Group`). We sadly don't have any tests for custom components currently.
- closes #1256
- Sprint board
- Labels
> Allowing Custom components to be rendered in table, ButtonGroup

- src/layout/Group/RepeatingGroupTableRow.tsx
- src/layout/Group/RepeatingGroupsEditContainer.tsx
- test/e2e/integration/app-frontend/components.ts
- test/e2e/integration/app-frontend/group.ts
This should fix an edge-case where text resource bindings for edit/delete/etc buttons in repeating groups were set to empty strings. See the linked discussion for details.
- https://altinn.slack.com/archives/C02EVE4RU82/p1687858029037189
- #1255
- Sprint board
- Labels
> Fixing text resource bindings set to empty strings in repeating groups

- src/layout/Dropdown/DropdownComponent.tsx
- test/e2e/integration/app-frontend/components.ts
Fixes values in Dropdown sometimes being overwritten/set to empty value. The Dropdown component relied on `options` being `undefined` until set to something, causing it to overwrite values previously set in the form data/prefill if you refreshed the page or loaded an existing instance. 
- https://altinn.slack.com/archives/CCQEQKGJD/p1688032374868919?thread_ts=1688030638.433839&cid=CCQEQKGJD
- Sprint board
- Labels
> Urgent: Fixing state overwrite in Dropdown

- src/layout/Button/WrappedButton.module.css
- src/layout/Button/WrappedButton.tsx
- test/e2e/integration/app-frontend/hide-row-in-group.ts
- test/e2e/integration/app-frontend/validation.ts
- test/e2e/support/custom.ts
Performing axe/a11y testing before running Percy, as Percy resizes the viewport in order to make snapshots of different screen sizes, which apparently also disrupts some components in the design system, making the dropdown not show its value after resizing a little while.
This will probably also cause flakiness in Percy testing, but we'll cross that bridge with a more generically fitting solution if it becomes necessary. …
> Fixing flaky a11y/wcag error

- src/components/form/SelectOptionItem.module.css
- src/components/form/SelectOptionItem.tsx
- src/layout/Dropdown/DropdownComponent.tsx
- src/layout/MultipleSelect/MultipleSelectComponent.tsx
- src/utils/options.module.css
- src/utils/options.ts
To improve the visual appearance, the font-weight is adjusted based on whether the option list contains descriptions in any of the options. If some or all options have descriptions, the labels/titles will be styled with semibold font-weight. If no options have descriptions, the labels/titles will be styled with regular font-weight.
I wasn't sure about the specific numeric value for semibold, but according to [the documentation here](https://drafts.csswg.org/css-fonts/#font-weight-numeric-values) it is recommended to use 600. Let me know if this value is wrong to use. 
- closes #https://github.com/Altinn/app-frontend-react/issues/1169
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utfo …
> Option select styling with and without description

- src/components/form/RadioGroup.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
This PR fixes a bug that was reported on [slack](https://altinndevops.slack.com/archives/C045EB3JA9X/p1688553637421089)
The new `RadioButtons` component did not pass along the disabled prop to `FieldSet` when `readOnly` was set to `true`.
- closes #1310 
- Sprint board
- Labels
> fix(RadioButtons): add disabled property to FieldSet when readOnly is true

- src/features/formData/submit/submitFormDataSagas.ts
- test/e2e/integration/app-frontend/auto-save-behavior.ts
When saving formData for statefull app the http request was not cancelled if the saga was cancelled (takeLatest). This would lead to the user beeing stuck on the same page if the Naviagtion was triggered two times in a row on slow internett.
- closes #1313
- Sprint board
- Labels
> Fix bug for auto save behavior on change page

- src/utils/validation/schemaValidation.test.ts
- src/utils/validation/validation.test.ts
Added test cases for the predefined formats that can be used on text in json schema, confirming that all formats from studio are supported. I copied the list of formats from [studio](https://github.com/Altinn/altinn-studio/blob/master/frontend/packages/schema-model/src/types/StringFormat.ts).
- closes #153
> Testing schema formats

- src/layout/GenericComponent.tsx
- src/layout/Likert/LikertComponent.tsx
- src/layout/RadioButtons/radioButtonsUtils.ts
- src/layout/layout.d.ts
- test/e2e/integration/app-frontend/hide-row-in-group.ts
- test/e2e/support/custom.ts
- test/e2e/support/global.d.ts
This should make sure to wait for all Dropdown components to show their values before taking a snapshot.
- #1266 
- #1264
- Sprint board
- Labels
> Visual testing: Making screenshots less flaky (3)

- src/features/pdf/PDFView.tsx
- src/features/pdf/data/generatePdfSagas.ts
- src/utils/layout/LayoutNode.ts
This makes components with `renderAsSummary: true` behave like actual `Summary` components for PDF generation, giving more flexibility when using a custom PDF layout.
Removed some type assertions as well since `LayoutComponentOrGroup` resolves to `any` and therefore makes no difference.
- https://altinndevops.slack.com/archives/C05FCB9738R/p1688979831492709?thread_ts=1688388588.706849&cid=C05FCB9738R
- Sprint board
- Labels
> Support `renderAsSummary` components in PDF

- package.json
- yarn.lock
I'm working on #832 in a branch, and the code generator I'm working on will need to have `ts-node` and `tsconfig-paths` installed in `package.json`. Adding a PR for that here, so that the [branch diff](https://github.com/Altinn/app-frontend-react/compare/main...feat/type-schema-generation) doesn't get larger than it already is.
- Sprint board
- Labels
> Installing `ts-node` and `tsconfig-paths`

- schemas/json/layout/layout.schema.v1.json
- src/components/form/SoftValidations.test.tsx
- src/components/form/SoftValidations.tsx
- src/layout/Alert/Alert.module.css
- src/layout/Alert/Alert.test.tsx
- src/layout/Alert/Alert.tsx
- src/layout/Alert/AlertBaseComponent.test.tsx
- src/layout/Alert/AlertBaseComponent.tsx
- src/layout/Alert/index.tsx
- src/layout/Alert/types.d.ts
- src/utils/render.tsx
- test/e2e/integration/app-frontend/validation.ts
Added a new `Alert` component, with options for 
- `severity` - sets the style of the alert, and has four valid values `"success" | "info" | "danger" | "warning"`.  
- `title` - sets the title via `textResourceBindings`.
- `description` - sets the description via `textResourceBindings`.
- ~~`useAsAlert` - A boolean which specifies whether the component should have `role="alert"` or not. It should not have this for static elements displaying information, but should have it for dynamic elements that appear after a certain user input. I currently implemented the `aria-live` attribute with `polite`, but I think maybe this should be configurable. Or maybe it should be based on severity label. if `useAsAlert` is set, and `severity` is >= `warning`, `aria-live` should be set to `assertive`.~~ …
> feat(Alert): add Alert component which uses @digdir/design-system-react

- src/hooks/useMapToReactNumberConfig.ts
- src/hooks/useReload.ts
- src/layout/Input/InputComponent.tsx
- src/layout/Input/index.tsx
- src/utils/formattingUtils.test.ts
- src/utils/formattingUtils.ts
If the form data we save to the backend cannot be parsed into the strong types of the data model class, the save fails with 400 bad request and due to our handling of such errors, the app "crashes" with "unknown error". Since we use `decimal` as our preferred number type when generating the data model classes in studio (even if you select integer it seems), we should probably make sure that our `Input` component with number formatting is "safe" to use with numeric data types in the data model.
This change will check whether the number can be parsed into the `decimal` type before saving the data when using number formatting. The `react-number-format` already restricts what you can type into the box, but there are a few edge cases that this deals with. For example, you need to be able to …
> Prevent crash on save invalid decimal value

- schemas/json/layout/layout.schema.v1.json
- src/features/options/fetch/fetchOptionsSagas.test.ts
- src/features/options/fetch/fetchOptionsSagas.ts
- src/hooks/useGetOptions.ts
- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
- src/layout/Dropdown/DropdownComponent.tsx
- src/layout/Likert/RepeatingGroupsLikertContainer.tsx
- src/layout/MultipleSelect/MultipleSelectComponent.tsx
- src/layout/RadioButtons/radioButtonsUtils.ts
- src/layout/layout.d.ts
- src/types/index.ts
- src/utils/options.ts
- src/utils/urls/appUrlHelper.test.ts
- src/utils/urls/appUrlHelper.ts
This introduces a new option for setting static query parameters in options (similar to mapping, but not from the data model). 
This can be done by adding the `queryParameters` property with the form:
```json
{
"id": "some-id",
"type": "Dropdown",
"optionsId": "options",
"queryParameters": {
"name": "value"
}
}
```
This object can be extended in the future to add [expression support](https://github.com/Altinn/app-frontend-react/issues/1181), but this would likely require a major rewrite, possibly by moving over to [tanstack query](https://github.com/Altinn/app-frontend-react/issues/1294). If and when these things happen, we could deprecate and later remove `mapping`.
- closes #957
- https://github.com/Altinn/altinn-studio-docs/pull/1045
- …
> Static query parameters for options

- src/features/devtools/components/DevHiddenFunctionality/DevHiddenFunctionality.tsx
- src/features/devtools/components/DevNavigationButtons/DevNavigationButtons.tsx
- src/features/dynamics/conditionalRenderingSagas.ts
- src/layout/Group/SummaryGroupComponent.test.tsx
- src/types/index.ts
- src/utils/layout/LayoutNode.ts
- src/utils/layout/LayoutPage.ts
- src/utils/layout/LayoutPages.ts
- src/utils/validation/validation.ts
- test/e2e/integration/app-frontend/calculate-page-order.ts
A bug was reported to me directly on Slack that seemed to cause hidden required fields to produce 'empty field' validation messages - if the pages they were in were hidden using the legacy 'tracks' functionality. I haven't bisected to verify, but I would think this might have been introduced with the recent validation refactor. There was no test for this to catch the problem when it appeared.
This should fix the issue by properly returning `true` in `node.isHidden()` for these components - although that does somewhat break the expectations for expressions - where it is expected that `component` lookups in tracks-hidden pages still work (i.e. does not always return `null`). For this reason, I'm opting to turn this behaviour off everywhere besides the validation logic.
- closes #{issue …
> Fix: Hiding required validation messages for tracks-hidden pages

- src/utils/validation/backendValidation.test.ts
- src/utils/validation/backendValidation.ts
- src/utils/validation/validationTexts.ts
- closes #1386
- backend PR: https://github.com/Altinn/app-lib-dotnet/pull/289
- Sprint board
- Labels
> Filter required and model validations from backend by source

- src/layout/Alert/Alert.module.css
- src/layout/Alert/AlertBaseComponent.tsx
- src/layout/Group/SummaryGroupComponent.module.css
Avoid page break inside the alert component in PDF. (also update `page-break-inside` to `break-inside`)
Before:
After:
> Avoid page break in alert component (PDF)

- src/features/attachments/upload/uploadAttachmentSagas.ts
- src/features/formData/submit/submitFormDataSagas.ts
- src/features/layout/repGroups/updateRepeatingGroupEditIndexSaga.ts
- src/features/layout/update/updateFormLayoutSagas.ts
- src/features/validation/singleFieldValidationSagas.test.ts
- src/features/validation/singleFieldValidationSagas.ts
- src/utils/validation/backendValidation.test.ts
- src/utils/validation/backendValidation.ts
- src/utils/validation/backendValidationSeverity.ts
- src/utils/validation/types.d.ts
- test/e2e/integration/app-frontend/validation.ts
In the same vein as #1384, this removes validation messages for components that are triggered by single-field validation, and were mapped to components on invisible layouts. The whole fix here is basically setting `{ respectTracks: true }`, and the rest is moving/renaming types and adding a regression test.
- https://altinn.slack.com/archives/C02ESDSGPN1/p1692261444104049
- #1384
- Sprint board
- Labels
> Fix: Removing validation messages for invisible components

- src/layout/Grid/GridComponent.tsx
Enable help text in grid cells to use language resource files by wrapping with lang.
Slack: https://altinn.slack.com/archives/C02ESDSC929/p1693308226424219
- Sprint board
- Labels
> Enable help text in grid cells to use language resource files

- src/utils/formattingUtils.ts
This pull request (PR) checks whether the selected language is nynorsk and if the browser supports using it with Intl.NumberFormatting. If these conditions are not met, the system defaults to using bokmål.
- closes https://github.com/Altinn/app-frontend-react/issues/1422
- Sprint board
- Labels
> Bug fix when using nynorsk in number formatting

- src/features/formData/submit/submitFormDataSagas.ts
- src/utils/validation/backendValidation.ts
This is related to the linked issue. I discovered this when I activated `RemoveHiddenDataPreview` in `frontend-test`, since this causes required validation to be run on the backend. This app uses old dynamics to hide fields, and so the required validation fails because the backend cannot take old dynamics into account when doing the validation. This caused an unknown error with the response `Cannot complete/close current task {currentElementId}. The data element(s) assigned to the task are not valid!`. This change makes it so that validationissues are not filtered out by source on submit, which should be fine since the backend validation is not called until all frontend validations are fixed so it should not cause duplicates.
- https://github.com/Altinn/app-frontend-react/pull/1416
- …
> Fix: Do not filter backend validations on submit

- src/components/presentation/OrganisationLogo/OrganisationLogo.module.css
- src/features/layout/formLayoutSlice.ts
This PR fixes an issue where some organisation logos would not take the available space (and getting width 0 and height 0)
It also fixes an issue with a flaky cypress test in `frontend/validations.ts`. The test failed because there was a race condition on validating repeating groups. Because of a `takeLatest` in the `updateRepeatingGroupsEditIndex` action. This meant that if there was an already ongoing validation that had not yet fulfilled, this would be dropped, causing the application to ignore a validation error. …
> fix: issue with organisation logo not taking the available space

- .github/workflows/codeql.yml
- .github/workflows/cypress.yml
- renovate.json
This should make renovate keep v3 updated with dependency patches, and make sure cypress tests still run on v3.
I'll merge this info both `main` and cherry-pick it into `v3`, and open a new PR to change the URLs of test-apps to v3-specific ones so that we can continue extending/changing our tests apps without affecting the (soon to be legacy) test apps for v3.
- Sprint board
- Labels
> Enabling the `v3` branch, running Cypress tests + renovate on it 

- src/utils/validation/backendValidation.test.ts
- src/utils/validation/backendValidation.ts
Assuming that v4 will require an app-lib version >= 7.14.0 we can safely remove this legacy filter for backend required-validations.
- https://github.com/Altinn/app-lib-dotnet/issues/287
- https://github.com/Altinn/app-frontend-react/issues/1386
- Sprint board
- Labels
>  Debt: Remove legacy required ValidationIssue filter

- src/layout/FileUploadWithTag/index.tsx
Quick fix that uses language to show the text-resource binding for tag-title in validation message. Previously it would just show the raw textResourceBinding.
> Fix validation message with tag title (v4)

- src/layout/FileUploadWithTag/index.tsx
Quick fix that uses language to show the text-resource binding for tag-title in validation message. Previously it would just show the raw textResourceBinding.
> Fix validation message with tag title (v3)

- src/layout/Likert/RepeatingGroupsLikertContainer.test.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
When Likert is in mobile view the leftColumnHeader text is added to the radio group label.
- closes #1456
- Sprint board
- Labels
> Show leftColumnHeader in Likert when mobile view

- schemas/json/application/application-metadata.schema.v1.json
- src/components/presentation/OrganisationLogo/OrganisationLogo.module.css
- src/components/presentation/OrganisationLogo/OrganisationLogo.tsx
- src/features/applicationMetadata/index.d.ts
- src/selectors/simpleSelectors.ts
Adds support for  a `size` option in `applicationmetadata.json` to be able to configure the size of an organisation logo.
- closes #1452 
- Sprint board
- Labels
> feat: add support for a size option in organisation logo

- .github/scripts/purge-frontdoor-cache.sh
Script to purge cache in azure front door. This needs to be integrated with the release script so that when new minor/patch versions are released the CDN cache is purged for the update major/minor folder
Releated to issue https://github.com/Altinn/altinn-studio/issues/7566
- Sprint board
- Labels
> bash script for purging front door cache

- package.json
- yarn.lock
I was reminded of this when renovate asked us to update this to the latest major version; but as it turns out, we no longer have any references to this package in our code 🥳
> Remove unused dependency `@material-ui/icons`

- src/features/attachments/map/mapAttachmentsSagas.ts
- src/features/dataLists/dataListsSlice.ts
- src/features/dynamics/formDynamicsSlice.ts
- src/features/formData/formDataSlice.ts
- src/features/formRules/rulesSlice.ts
- src/features/instanceData/instanceDataSlice.ts
- src/features/instantiate/instantiation/instantiationSlice.ts
- src/features/layout/fileUpload/watchMapFileUploaderWithTagSaga.ts
- src/features/layout/formLayoutSlice.ts
- src/features/party/partySlice.ts
- src/features/process/processSlice.ts
- src/features/profile/profileSlice.ts
- src/features/queue/queueSlice.ts
- src/features/textResources/fetch/fetchTextResourcesSagas.test.ts
- src/features/textResources/fetch/fetchTextResourcesSagas.ts
- src/features/validation/validationSlice.ts
- src/redux/sagaSlice.ts
Most of the time, I assume we're not thinking things all the way through, and we probably just pick from examples we're given. In redux sagas, I've seen a mix of `takeLatest` and `takeEvery` being used, [but we've also seen bugs that happen because of the more complex nature of `takeLatest` when it really shouldn't be used](https://github.com/Altinn/app-frontend-react/pull/1443/files). This PR renames most usages of `takeLatest` -> `takeEvery`, based on the assumption that most events should use `takeEvery`. Hopefully our current sagas will be re-implemented without any such 'taking' before v4 is released, but in case there are sagas left, I think they should prefer using `takeEvery`.
**Wait, what's `takeEvery`?**
In Redux Saga, you can choose when how a saga (effect of a redux action) is …
> Replacing most `takeLatest` with `takeEvery`

- test/e2e/fixtures/attachment.json
- test/e2e/integration/anonymous-stateless-app/anonymous.ts
- test/e2e/integration/frontend-test/all-process-steps.ts
- test/e2e/integration/frontend-test/components.ts
- test/e2e/integration/frontend-test/layout-sets.ts
- test/e2e/integration/frontend-test/message.ts
- test/e2e/integration/frontend-test/on-entry.ts
- test/e2e/integration/stateless-app/stateless.ts
- test/e2e/pageobjects/app-frontend.ts
- test/e2e/support/custom.ts
- Copied and deployed `-v3` versions of the test apps used for cypress
- I kept the app name the same (e.g. `frontend-test`) so I had to change out some places where the app-id variable (`frontend-test-v3`) was used in place of the app name.
- The update to wcag violation was due to the existing signing test app not being deployed to the latest version in main. I have deployed a new version there and updated this in `main` as well.
> Switch to `-v3` test apps

- src/features/attachments/upload/uploadAttachmentSagas.ts
This is the v4 equivalent change needed to fix the custom attachment validation messages that was broken when `app-lib` fixed their missing await. This seems to be the only change necessary to make all of the cypress tests pass on `frontend-test` on v8 🤞 🥳 
FYI: frontend-test on v8 has been deployed to tt02, so one validation test is expected to fail until this is merged.
- #1499
> Fix custom attachment validation message

- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
- Fix WCAG issue in new checkbox component - enable SR-only when rendered in table and there are only one checkBox.
- Fix the logic of hiding checkbox group when rendered in table/grid
- Added hideLegend prop to radioButtonGroup so it use the same styling of margin as checkBoxGroup.
- Sprint board
- Labels
> Fix issues in new CheckBox component + fix styling RadioButtonGroup

- test/e2e/support/custom.ts
Use `.then()` instead of setting default command timeout.
> Make PDF tests less hacky

- src/features/layout/fetch/fetchFormLayoutSagas.ts
- src/features/layout/formLayoutSlice.ts
Turns out that layout sets fetching was also already done using tanstack and the existing saga code was left unused. This PR removes the fetch layout sets saga.
- #1509
> Delete fetch layout sets saga

- src/utils/validation/backendValidation.ts
I noticed that the expression-validation tests were a bit flaky, and it turns out I forgot to exclude expression validations from the backend in the original PR 🤦 . This was not an issue in normal use since the frontend and backend seem to always agree on what is valid and what is not. But it looks like there are some subtleties when it comes to saving delay triggering single field validations and repeating group triggered validations that could cause a mismatch if the order of requests was unlucky, due to cypress being very fast. This should hopefully fix the flakyness.
- #1540  …
> Exclude expression validations from backend

- src/layout/Checkboxes/MultipleChoiceSummary.tsx
- src/layout/FileUpload/Summary/AttachmentSummaryComponent.module.css
- src/layout/FileUpload/Summary/AttachmentSummaryComponent.tsx
- src/layout/Summary/SummaryItemCompact.module.css
- src/layout/Summary/SummaryItemSimple.module.css
This fixes text overflowing the page in summary components (tested that PDF also looks right). Should also be cherry-picked and fixed in v3.
- closes #1531 
- Sprint board
- Labels
> Fix summary content overflow

- src/layout/Checkboxes/CheckboxesContainerComponent.module.css
- src/layout/Checkboxes/CheckboxesContainerComponent.test.tsx
- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
Cherry-picked from #1534 and #1551 
- closes https://altinn.slack.com/archives/C02ESDSC929/p1697099000192219
- Sprint board
- Labels
> Upgrade checkboxes (v3)

- src/components/form/Form.test.tsx
- src/features/expressions/shared-tests/functions/displayValue/summary.json
- src/hooks/usePdfPage.ts
- src/layout/Group/SummaryGroupComponent.test.tsx
- src/layout/Summary/SummaryComponent.test.tsx
- src/layout/Summary/SummaryComponent.tsx
- src/layout/Summary/config.ts
Remove `pageRef` option from `Summary` and get it from the target node instead.
- closes #1488 
- Sprint board
- Labels
> Remove pageRef property from Summary component

- src/App.tsx
- src/features/instanceData/getInstanceDataSagas.ts
- src/features/instanceData/instanceDataSlice.ts
- src/features/instantiate/instantiation/instantiationSlice.ts
- src/hooks/queries/useActiveInstancesQuery.ts
- src/layout/InstantiationButton/InstantiationButton.tsx
When a stateless app goes from being stateless to being stateful (i.e. creating an instance), the browser address bar changes to include the instance ID. If you pressed the back button at this point, `App.tsx` would just render the components it thought should render at this point, but the rest of the state would remain as before - with the full state used in the instance, including the state needed to save data. In `udir/pbu-test-anonym`, navigating here triggers saving (as page navigation triggers saving in that app), and it caused data to be truncated in the data model. As the Likert component (used heavily in that app) stores the questions in the data model, all the questions disappeared, rendering the app and instance broken and useless.
This works around the issue by refreshing the …
> Workaround for critical bug when pressing back button in browser (for stateless->stateful apps)

- package.json
- src/components/form/RadioButton.test.tsx
- src/components/molecules/DeleteWarningPopover.tsx
- src/layout/RadioButtons/RadioButtonsContainerComponent.test.tsx
- test/e2e/integration/frontend-test/components.ts
- test/e2e/integration/frontend-test/grid.ts
- test/e2e/pageobjects/app-frontend.ts
- yarn.lock
Switched `DeleteWarningPopover` to use `LegacyPopover`.
It is possible that this PR fixes the issues related to `HelpText`, as this should already use the new popover.
- closes #1616
> Upgrade design system to 0.35.0 (v3)

- package.json
- src/components/form/RadioButton.test.tsx
- src/components/molecules/DeleteWarningPopover.tsx
- src/layout/RadioButtons/RadioButtonsContainerComponent.test.tsx
- test/e2e/integration/frontend-test/components.ts
- test/e2e/integration/frontend-test/grid.ts
- test/e2e/pageobjects/app-frontend.ts
- yarn.lock
Switched `DeleteWarningPopover` to use `LegacyPopover`, for migration issue, see https://github.com/Altinn/app-frontend-react/issues/1601.
It is possible that this PR fixes the issues related to `HelpText`, as this should already use the new popover.
- closes #1615
> Upgrade design system to 0.35.0

- src/codegen/Common.ts
- src/features/options/useGetOptions.ts
- src/hooks/useSourceOptions.ts
In #1614 support for dynamic expressions in code lists based on repeating groups was added. This PR did not include an update to the properties of `IOptionSource` which is the basis for generating schema, types, and future documentation of these properties. 
This PR adds these properties.
> refactor properties of IOptionSource to have suppport for expressions.

- src/features/options/useGetOptions.ts
- test/e2e/integration/frontend-test/components.ts
- test/e2e/integration/frontend-test/sort-order.ts
Fixes an issue where `sortOrder` on selection components would sort the options according to their text resource key if this was specified. 
- closes #1634 
- Sprint board
- Labels
> fix: sort options based on their value not text resource key

- src/components/atoms/AltinnAttachment.tsx
- src/features/confirm/containers/ConfirmPage.tsx
- src/features/receipt/ReceiptContainer.test.tsx
- src/features/receipt/ReceiptContainer.tsx
- src/layout/AttachmentList/AttachmentListComponent.test.tsx
- src/layout/AttachmentList/AttachmentListComponent.tsx
- src/layout/AttachmentList/config.ts
- src/layout/FileUpload/FileUploadTable/AttachmentFileName.tsx
- src/selectors/dataTypes.ts
- src/types/shared.ts
- src/utils/attachmentsUtils.test.ts
- src/utils/attachmentsUtils.ts
- test/e2e/support/customReceipt.ts
Refactored the code by removing the includePdf property and introduced some adjustments to the `dataTypeIds` for more flexibility. The config options for dataTypeIds are now:
- To display only attachments from the "fileUpload-changename" task:
``
"dataTypeIds": ["fileUpload-changename"] 
``
- To display attachments from "fileUpload-changename" and pdf-generated attachments:
`` "dataTypeIds": ["fileUpload-changename", "ref-data-as-pdf"] ``
- If dataTypeIds is not configured, all attachments from the task are included, except pdf-generated:
`` "dataTypeIds": undefined ``
- To include all attachments from the task, including pdf-generated ones:
`` "dataTypeIds": ["include-all"] ``
Removed the `platform` parameter and corresponding logic in the AttachmentUtils file, as it was found to be …
> Attachmentlist config

- src/hooks/queries/useGetTextResourcesQuery.ts
- test/e2e/integration/frontend-test/components.ts
This PR addresses an issue related to Tanstack Query's onSuccess behavior, as discussed in [this Slack thread](https://altinndevops.slack.com/archives/C045EB3JA9X/p1699365150848939). When switching from Norwegian -> English -> Norwegian, the text elements would become stuck in English. This occurred because Tanstack Query's `onSuccess` wasn't triggered again once the data was fetched and cached.
To resolve this, the `onSuccess` logic has been replaced with a `useEffect`. This ensures that the language change is detected even when the data is already in the cache
- closes #1632  …
> Fix: Language Selector Not Updating Text Resources Correctly

- src/layout/Checkboxes/CheckboxesContainerComponent.module.css
- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
The css in the component from the designsystem somehow broke. The default label css was overriding the css given to the label component used in the checkbox component. This happened even though the css given to the label in the checkbox component was given later and should have higher priority.
I added more specific and thus more highly prioritised css to the checkboxGroup that targets the label to override the css to what had been overridden internally in the DS. …
> Fix checkbox label alignment

- src/__mocks__/getLogoMock.ts
- src/components/LandmarkShortcuts.tsx
- src/components/altinnAppHeader.test.tsx
- src/components/altinnAppHeader.tsx
- src/components/altinnError.tsx
- src/components/molecules/AltinnSubstatusPaper.tsx
- src/components/organisms/AltinnAppHeader.test.tsx
- src/components/organisms/AltinnAppHeader.tsx
- src/components/organisms/AltinnAppHeaderMenu.tsx
- src/components/presentation/Presentation.tsx
- src/core/loading/Loader.test.tsx
- src/core/loading/Loader.tsx
- src/features/instantiate/containers/InstantiationErrorPage.tsx
- src/features/instantiate/containers/UnknownError.test.tsx
- src/features/instantiate/containers/UnknownError.tsx
- src/features/language/Lang.test.tsx
- src/features/language/Lang.tsx
- src/features/language/LanguageProvider.tsx
- src/features/language/useLanguage.ts
- src/test/renderWithProviders.tsx
The `useLanguage()` hook is great and all, but it's not really idiomatic React, and we could do better. With the steady decline of Sagas and functions that take `langTools` as a bunch of functions used to _do stuff with later_, we can do the next great thing; referencing language keys using a React component instead.
Right now, this component is an error boundary, which makes it possible for us to render language keys (at least our own) very early in the app runtime, even before the `<LanguageProvider />` runs, and still produce some resemblance of a coherent output. This fixes potential problems I (and @bjosttveit) saw where errors early in the provider tree will throw new errors again when `<UnknownError />` may be rendered even before we have a language.
In time, we can also use this …
> The `<Lang />` component to replace `useLanguage()`

- src/hooks/useNavigatePage.ts
- src/layout/CustomButton/CustomButtonComponent.test.tsx
- src/layout/CustomButton/CustomButtonComponent.tsx
- src/layout/CustomButton/config.ts
- src/layout/CustomButton/typeHelpers.ts
This PR fixes an issue @RonnyB71 discovered while testing the new `CustomButton` component. It also does some minor refactoring. 
Changes: 
- Fix bug with `CustomButton` not being disabled if there are multiple actions and one of them are unauthorized. 
- Rename the `name`-property to `id`. This is the name used on the backend. The documentation is already using `id` instead of `name`.  
- Adds log warnings to the devtools console whenever a navigation fails because there is no next or previous page, or the page you try to navigate to does not exist. 
- closes #133  …
> Bug: CustomButton authorization

- src/index.css
Switch font back to `Altinn-DIN` until we can solve the issues that came up when switching to `Inter`.
- #1500
> Switch back to `Altinn-DIN` font

- src/components/presentation/NavBar.tsx
- src/features/options/useGetOptionsQuery.ts
- src/queries/queries.ts
- src/utils/network/networking.ts
This PR adds types to the `httpGet` and `httpGetRaw` functions such that they reflect the possibility of them returning `null`. I also made them generic, so that we can specify what we expect the response data to be when returning. 
This also led to fixing a unchecked instance of a nullable data response trying to be accessed in the code in `useGetOptionsQuery`
- Sprint board
- Labels
> fix: update types to httpGetRaw and httpGet 

- src/features/validation/frontend/schemaValidation.test.ts
- src/features/validation/frontend/schemaValidation.ts
Fixes error where null/undefined values where evaluated with schema validation. This probably changed with the new data storage in v4, so fields that are null/undefined no longer get their key removed from the data model.
- closes #1752 
- Sprint board
- Labels
> Fix erroneous schema validation errors for null/undefined values

- src/hooks/useIsDev.test.ts
- src/hooks/useIsDev.ts
Running localtest in podman means I cannot use port 80, so the `host` becomes `local.altinn.cloud:port`, but `hostname` remains as `local.altinn.cloud` so I think switching to check the `hostname` instead is better. Otherwise I will not see errors on components and the dev tools button is hidden when using podman.
> Make dev check not care about port

- src/features/language/useLanguage.test.tsx
- src/features/language/useLanguage.ts
- src/types/shared.ts
An app used a text resource that looked something like this:
```json
{
"id": "...",
"value": "Hvor mange {0} <p style='text-transform: lowercase;'>{1}<p> brukte gatekjøkkenet i {2}?",
"variables": [
{ "key": "enhet", "dataSource": "dataModel.default", "defaultValue": "liter" },
{ "key": "vare", "dataSource": "dataModel.default", "defaultValue": "FRITYROLJE" },
{ "key": "aar", "dataSource": "dataModel.default", "defaultValue": "2023" },
],
}
```
It failed when the react nodes are made into an array, and `langAsString()` returned empty. This should fix the problem, and adds a test for it.
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have …
> Fixing some complex text resource lookups

- webpack.config.development.js
This makes the dev server return a header that indicates the current branch you're developing on. Which in turn should soon make the branch visible in the 'pick frontend version' selector in LocalTest.
- https://github.com/Altinn/app-localtest/pull/74
- Sprint board
- Labels
> Showing the current git branch in LocalTest when picking a frontend version

- src/components/form/HelpTextContainer.module.css
- src/features/pdf/PDFView.module.css
- src/features/pdf/PDFView.tsx
- src/layout/Grid/GridSummaryComponent.tsx
- src/layout/Group/__snapshots__/SummaryGroupComponent.test.tsx.snap
- src/layout/RepeatingGroup/Summary/__snapshots__/SummaryRepeatingGroup.test.tsx.snap
- src/layout/Summary/EditButton.module.css
- src/layout/Summary/EditButton.tsx
- test/e2e/support/custom.ts
- Made Grid summary respect overrides
- Make helptext and edit buttons invisible in `@media print`
- Hide all buttons in pdfView (mostly for cypress, since print emulation is not possible without chrome-specific hacks)
- Command-timeout in PDF-tests were broken, fixed
- Cleaned up `PDFComponent`
- closes #1773 
- Sprint board
- Labels
> Make sure buttons are not visible in PDF

- src/core/contexts/zustandContext.tsx
- src/features/validation/backend/useBackendValidation.ts
- src/features/validation/hooks.ts
- src/features/validation/validationContext.tsx
- src/layout/RepeatingGroup/OpenByDefaultProvider.test.tsx
- src/layout/RepeatingGroup/OpenByDefaultProvider.tsx
- src/layout/RepeatingGroup/RepeatingGroupContainer.tsx
- src/layout/RepeatingGroup/RepeatingGroupContext.tsx
- src/layout/RepeatingGroup/RepeatingGroupTable.tsx
- src/layout/RepeatingGroup/RepeatingGroupsEditContainer.tsx
- test/e2e/integration/frontend-test/group.ts
SSB managed to use `openByDefault` together with a `hiddenRow` expression that caused newly added rows to be hidden. When we fixed `openByDefault` to respect `hiddenRow` in v4, this now caused an _infinite loop of save-requests_, as the `openByDefault` functionality tried again and again to add a new row that it could open for editing. As none of the new rows ever became visible, it got stuck in that loop.
I tried my best adding tests and fixing the issues while preserving the core functionality, but in the end I figured it's best to just make a breaking change here as well. Previously, `openByDefault` would always add a new row if none were visible in the UI, and would thus always add a row even when the user deleted the last visible one. I think this concept is flawed, and it is …
> Bugfix: Multiple issues with `openByDefault`

- src/features/validation/ComponentValidations.tsx
- src/index.css
Yet another small error when removing `tjenester3.css`. Setting this global css was a bit to aggressive when it only needed to be set in validation messages. This had the side effect of removing numbers from all lists 😅 
before:
after:
I havent tested this very thoroughly, but percy did not find any differences 🤷 
- Sprint board
- Labels
> Remove global `list-style-type: none;`

- src/layout/Grid/GridComponent.tsx
Adds missing `<Lang />` to title and description, as well as conditionally rendering `help` and `description` so we dont get empty whitespace or help-button with empty content.
- closes #1815
- Sprint board
- Labels
> Fix `labelFrom` in Grid

- test/e2e/integration/frontend-test/auto-save-behavior.ts
This merely adds the Cypress test from #1257, adjusted to the realities of v4
- closes #1257
- Sprint board
- Labels
> Adding cypress test for validation + saving `onChangePage`

- src/features/applicationMetadata/ApplicationMetadataProvider.tsx
- src/utils/versionCompare.test.ts
- src/utils/versionCompare.ts
This should allow running the backend with project reference instead of nuget packages.
- closes #1801
- Sprint board
- Labels
> Allowing project references in version numbers

- src/features/options/useAllOptions.tsx
- src/features/options/useGetOptions.ts
- test/e2e/integration/frontend-test/options.ts
- test/e2e/pageobjects/app-frontend.ts
1. `useAllOptions` will now wait until a node is added to the state through `setNodesFound` before it starts to fetch options. This makes sure that it will not think everything is loaded when the first option is loaded.
2. Clearing options did not work as expected. Since it checked the current (from the options-list) instead of the currentStringy, the value would always be undefined if the string-value was not present in the options list, and so it would not see that it needed clearing. Added a test to make sure it does not clear the value while fetching new options in case the value is still valid in the new option list.
- closes #1556 
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell- …
> Fix options loading and clearing

- src/layout/RepeatingGroup/RepeatingGroup.module.css
- src/layout/RepeatingGroup/RepeatingGroupTable.tsx
- src/layout/RepeatingGroup/config.ts
Adds a new config option to repeating groups; `stickyHeader` which makes the Tables header stick to the top of the page when scrolling below the header.
```
{
"id": "myRepeatingGroup",
"type": "RepeatingGroup",
"stickyHeader": true,
...
}
```
- closes #1492 
https://github.com/Altinn/altinn-studio-docs/pull/1413
- Sprint board
- Labels
> Sticky header for repeating groups

- src/features/formData/FormDataWrite.tsx
- src/features/options/useGetOptions.test.tsx
- src/layout/FileUpload/Summary/AttachmentWithTagSummaryComponent.test.tsx
In v3, a `mapping` from an empty field would add the queryParameter `?field=undefined` which is literally sending the value as the string `"undefined"`. If the query parameter is used for filtering on some property this sometimes worked as expected, as long as the filtered property never actually was equal the string `"undefined"`.
Up until now in v4, we have instead ignored and simply not added the query parameter if its value was empty, which is less wrong, and arguably correct. However, now you cannot separate the cases where a mapping parameter is added but empty, or if it is not added to the mapping at all. Since setting the mapping parameter is an active choice you may want a different behavior in the two cases.
This change makes sure to add all mapping parameters to the query …
> Include empty fields in mapping as empty query parameters

- src/layout/Likert/LikertComponent.module.css
- src/layout/Likert/LikertComponent.tsx
- src/layout/Likert/RepeatingGroupsLikertContainer.test.tsx
- src/layout/Likert/RepeatingGroupsLikertContainer.tsx
- src/layout/Likert/RepeatingGroupsLikertContainerTestUtils.tsx
- test/e2e/integration/frontend-test/likert.ts
- test/e2e/integration/frontend-test/mobile.ts
- test/e2e/integration/frontend-test/validation.ts
- test/e2e/pageobjects/likert.ts
This PR fixes an issue where the label of each individual radio button in the `Likert` was empty. This PR addresses that issue, and also does some other fixes.
**Changes:**
- Add text label to radio buttons which are visible for screen readers only
- Refactor the code such that the `<table>` element which encapsulates the `Likert`, does not behave like a table for screen readers. The TL;DR for why I did this, is that the component is only visually represented as a table, but is in fact just a collection of radio groups. 
- Changed the styling of the table such that each table header (except for the inital one) takes exactly 100px width. This ensures that the `Likert` options are aligned underneath each other no matter how many `Likert` components a page has. I also centered the text of …
> Change the screen reader semantics of the Likert component

- src/layout/Summary/SummaryComponent.tsx
This seems to have only affected repeating groups, which needs row context to resolve properly, which the targetNode gives. Tested manually.
- closes #1860
> Fixes #1860

- src/layout/Address/AddressComponent.test.tsx
- src/layout/Address/AddressComponent.tsx
- src/layout/Address/config.ts
- test/e2e/integration/frontend-test/all-process-steps.ts
- test/e2e/integration/frontend-test/pdf.ts
Address component now supports a custom label if you add config to ie:
```
{
"id": "adresse",
"type": "Address",
"textResourceBindings": {
"title": "Adresse"
},
"dataModelBindings": {
"address": "Adresse.Gateadresse_æøå",
"zipCode": "Adresse.Postnr",
"postPlace": "Adresse.Poststed"
},
"simplified": true,
"readOnly": false,
"required": false
},
```
- closes #{36}
- Sprint board
- Labels
> feat: added support for label for Address component

- schemas/json/layout/footer.schema.v1.json
- schemas/json/validation/validation.schema.v1.json
- src/codegen/Common.ts
Allow `$schema` property in files where it was missing.
- `Settings.json`
- `layout-sets.json`
- `*.validation.json`
> Allow `$schema` property in schemas

- src/features/validation/utils.ts
- src/layout/RepeatingGroup/OpenByDefaultProvider.test.tsx
- src/layout/RepeatingGroup/RepeatingGroupContainer.test.tsx
- src/layout/RepeatingGroup/RepeatingGroupTable.test.tsx
- test/e2e/integration/frontend-test/auto-save-behavior.ts
- test/e2e/integration/frontend-test/components.ts
- test/e2e/integration/frontend-test/footer.ts
- test/e2e/integration/frontend-test/group.ts
Make the default for `showValidations` more similar to the default in v3 to make migration easier. `showValidations` can still be empty by setting it as an empty array `[]` instead of `undefined`.
- closes https://github.com/Altinn/app-frontend-react/issues/1892
- Sprint board
- Labels
> Make AllExceptRequired validations default

- cypress.config.js
- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
- test/e2e/config/docker.json
- test/e2e/config/podman.json
- test/e2e/config/tt02.json
- test/e2e/integration/frontend-test/all-process-steps.ts
- test/e2e/integration/frontend-test/group.ts
- test/e2e/integration/frontend-test/hide-row-in-group.ts
- test/e2e/integration/frontend-test/message.ts
- test/e2e/integration/frontend-test/summary.ts
- test/e2e/integration/frontend-test/validation.ts
- test/e2e/support/custom.ts
- test/e2e/support/formFiller.ts
- test/e2e/support/start-app-instance.ts
- Adding flaky test fixes originally applied to the `fix/1696-decimal-separator-stripped` branch
- Removing debounce onBlur for checkboxes. It turns out this forces a save immediately when clicking a checkbox, which is absolutely not what we wanted to do.
- Adding different configurations for docker/podman
- Sprint board
- Labels
> Fixes for flaky tests, separate configs for docker/podman

- src/features/validation/callbacks/onAttachmentSave.ts
- src/features/validation/utils.ts
- src/layout/FileUpload/index.tsx
- src/layout/FileUploadWithTag/index.tsx
- test/e2e/integration/frontend-test/components.ts
Since https://github.com/Altinn/app-frontend-react/pull/1893 was merged it has become apparent that minimum number of attachments is essentially the same as required validation, and should therefore not be immediately visible, but rather follow the same pattern as required. This also applies to missing tags for FileUploadWithTag.
- closes #1920 
- Sprint board
- Labels
> Fix validation of minNumberOfAttachments

- src/layout/RepeatingGroup/index.tsx
- test/e2e/integration/frontend-test/group.ts
Essentially the same problem as https://github.com/Altinn/app-frontend-react/issues/1920 but for repeating groups.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1710316266683829
- https://github.com/Altinn/app-frontend-react/pull/1893
- Sprint board
- Labels
> Fix repeating group minCount validation visibility

- src/features/logging.ts
Stringify objects in axios error response to avoid getting `[Object object]`:
```
Process next failed:
Message: Request failed with status code 409
Request: PUT 'http://local.altinn.cloud/staf/rusarbeid/instances/500800/45c202cc-bb7f-44ce-8e9e-664f12c31f7a/process/next?language=nn'
Response: [object Object]
```
> Fix axios error logging

- src/features/devtools/DevTools.module.css
- src/features/devtools/components/LayoutInspector/LayoutInspector.module.css
- src/features/devtools/components/LayoutInspector/LayoutInspector.tsx
- src/features/devtools/components/NodeInspector/NodeInspector.tsx
- src/features/devtools/components/NodeInspector/ValidationInspector.module.css
- src/features/devtools/components/NodeInspector/ValidationInspector.tsx
- src/features/validation/schemaValidation/schemaValidationUtils.ts
- src/features/validation/schemaValidation/useSchemaValidation.ts
- src/features/validation/selectors/attachmentValidations.ts
- src/features/validation/selectors/bindingValidationsForNode.ts
- src/features/validation/selectors/componentValidationsForNode.ts
- src/features/validation/utils.ts
- src/layout/Datepicker/index.tsx
- src/layout/LayoutComponent.tsx
- src/layout/RepeatingGroup/index.tsx
- src/layout/index.ts
Give `minItems` errors from schema validation the same visibility as required. Make sure to filter out duplicate errors if both `minItems` is defined in schema and `minCount` is defined on the repeating group.
I added a tab in the node inspector to more easily observe the validation state of nodes. This will show validations for each dataModel binding, which type of validation it is, if it is visible and or filtered out as a duplicate. It also shows which validation types are visible for the node at the top (Schema, Component, CustomBackend,  etc.).
**A small digression**
I also explored the possibility of doing the same with required validations from the data model, as it would be nice to show these even if the component is not marked as required. Required validations in schema are …
> Give certain schema validations `Required` visibility, and filter duplicates

- src/features/validation/index.ts
- src/features/validation/nodeValidation/useNodeValidation.ts
- src/layout/LayoutComponent.tsx
- src/layout/List/index.tsx
- test/e2e/integration/frontend-test/validation.ts
This small change makes sure to check the `invalidData` object as well when checking for empty fields, so that required validation is not shown e.g. when an integer is too big. Tested manually on `ssb/ra0439-01` as well.
- closes #1890
- Sprint board
- Labels
> Do not show required validation when data is invalid

- src/layout/Checkboxes/CheckboxesContainerComponent.module.css
- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
Implements the Helptext in the same way as radiogroup, which aligns the helptext with the legend for checkboxes.
- closes #1972 
- Sprint board
- Labels
> Align helptext with legend

- src/components/form/LinkToPotentialNode.tsx
- src/components/form/LinkToPotentialPage.tsx
- src/features/expressions/index.ts
- src/features/expressions/shared-tests/functions/linkToPage/linkToPage-stateless.json
- src/features/expressions/shared-tests/functions/linkToPage/linkToPage.json
- src/language/sharedLanguage.ts
- test/e2e/integration/frontend-test/navigation.ts
When `linkToComponent` or `linkToPage` points to components or pages that are either hidden or does not exist, the functions render the link ass pure text. A warning will also be logged to the developer tools that the link pointed to a component or page that did not exist. 
- closes #1648
- Sprint board
- Labels
> Render linkToComponent and linkToPage as pure text if hidden/does not exist

- src/layout/Input/InputComponent.module.css
- src/layout/Input/InputComponent.tsx
This is in response to this comment:
https://github.com/Altinn/app-frontend-react/issues/1833#issuecomment-2012475986
The styling is now updatet as suggested in the comment:
- closes #{1833}
- Sprint board
- Labels
> fix: styled the text-only focus state to look more like the input state

- src/layout/Input/InputComponent.tsx
User reports this box being shown when there is not yet any data:
This fixes the issue by returning null when the input is null or empty string.
- [ x] I have tested these changes manually
- Sprint board
- Labels
> fix: returning null if input is null or empty string

- src/layout/Grid/GridSummaryComponent.tsx
- test/e2e/integration/frontend-test/pdf.ts
The problem was caused by the targetNode in GridSummaryComponent not overriding the existing value from overrides, causing it to refer to itself recursively, since the existing value was from the group component above.
- slack https://altinn.slack.com/archives/C02EJ9HKQA3/p1712827090911089
- Sprint board
- Labels
> Fix PDF generator crashing when having Grid inside Group

- src/utils/layout/hierarchy.ts
The Javascript type system is amazing as always, this error was due to the fact that `typeof null === 'object'` returns true, combined with the fact that `any` in Typescript does not do type-narrowing very well. Switching `any` to `unknown` made the mistake more apparent, now warning that `obj` could be either `object | null` which gave a type error in `Object.keys`.
A lesson here is that `unknown` can be more useful in cases like this instead of using `any` explicitly when you dont know the type.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1713947469018009 …
> Fix hierarchy generation crashing due to missing null check

- src/components/ReadyForPrint.tsx
- src/layout/Map/MapComponentSummary.tsx
There were a few issues with the Map component in PDF
1. The map marker from leaflet has `role=button` and would therefore get hidden in the PDF. This was solved by overriding styling in the `MapComponentSummary`
2. The map fades in from opacity 0 on load, meaning that when app-frontend thinks everything is loaded the Map is not 100% visible yet. This was also fixed by overriding styling in `MapComponentSummary`, setting tiles to always have opacity 1.
3. The waiting-for-images-to-load part of `ReadyForPrint` turned out to not be very robust, as in most cases none of the map tiles had time to load before print happened. One problem seems to be that it first looks for all of the image elements, and adds promises for the ones that have not loaded yet. But most of the time it would not find …
> Make map marker visible in PDF and readyForPrint more robust

- schemas/json/layout/expression.schema.v1.json
- src/features/expressions/index.ts
- src/features/expressions/shared-tests/functions/_experimentalSelectAndMap/_experimentalSelectAndMap-with-append-without-last-element.json
- src/features/expressions/shared-tests/functions/_experimentalSelectAndMap/_experimentalSelectAndMap-with-prepend-and-append.json
- src/features/expressions/shared-tests/functions/_experimentalSelectAndMap/_experimentalSelectAndMap.json
_This is a feature request, and I would like some feedback as to whether you think this should be implemented or not._
This PR introduces a new function `_experimentalSelectAndMap` to the dynamic expression language. The function selects string properties in objects of an array in the data model and concatenates them to a single string. The reason for this is to be able to create a list of something in a form's data model. 
Usage: 
Say you have this underlying data structure: 
```json 
{
"path": {
"to": {
"arrayOfObjects": [
{
"name": "Prop1",
"value": "Value1"
},
{
"name": "Prop2",
"value": "Value2"
},
{
"name": "Prop3",
"value": "Value3"
}
]
}
}
}
```
```json 
["_experimentalSelectAndMap", "path.to.arrayOfObjects", "name"]
``` 
Would result in the string `Prop1 Prop2 Prop3`
The function …
> Add function select to dynamic expressions

- src/core/contexts/zustandContext.tsx
- src/features/devtools/layoutValidation/useLayoutValidation.tsx
- src/features/form/layout/PageNavigationContext.tsx
- src/features/formData/FormDataWrite.tsx
- src/features/options/useAllOptions.tsx
- src/features/validation/selectors/taskErrors.ts
- src/utils/layout/NodesContext.tsx
These performance improvements were identified by testing `ssb/ra0255-01` with 250 rows in a repeating group. Specifically, by adding an artificial pagination set-up so only 10/250 rows were visible. That way, performance issues that were not directly tied to rendering many components could be found more easily.
1. **Problem**: In `useDelayedMemoSelectorProto`, checking if a selector had changed was slow due to having to call `find` on the list of selectors, which would be very large for an app with hundreds of rows. This would also have to be called for every selector when rendering.
**Solution**: Store previously accessed selectors in a `Map` instead of an array, to be able to find a selector in constant time.
2. In `useDelayedMemoSelectorProto`, when checking if a selector had changed, …
> Several performace improvements

- src/components/form/SoftValidations.tsx
- src/features/devtools/components/FeatureToggles/FeatureToggles.tsx
- src/features/devtools/components/LayoutInspector/LayoutInspector.tsx
- src/features/language/useLanguage.test.tsx
- src/features/language/useLanguage.ts
- src/language/languages.ts
- src/language/sharedLanguage.test.ts
- src/language/sharedLanguage.ts
- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/Address/AddressComponent.module.css
- src/types/shared.ts
- test/e2e/integration/frontend-test/on-entry.ts
Fikses some styling issues when validation messages are too long. Also did a minor refactoring of `useLanguage.ts` to make it a tiny bit more readable (at least for me 💁‍♀️). 
Would love feedback on both the refactoring and the fix. 
- closes #1951 
- Sprint board
- Labels
> fixes validation message formatting/styling and adds smaller changes to useLanguage hook

- src/features/language/LanguageProvider.tsx
- src/features/language/textResources/TextResourcesProvider.tsx
- src/features/party/PartiesProvider.tsx
- src/index.tsx
- src/queries/appPrefetcher.ts
- src/queries/partyPrefetcher.ts
- test/e2e/integration/frontend-test/party-selection.ts
This slightly alters the prefetching behavior for profile, parties, and currentParty. In the original implementation, it would prefetch profile, parties and currentparty immediately. This would lead to 401 errors for anonymous apps. This is not a problem in and of itself, but would create noise in the logs as every time an anonymous app is opened it would fail the same requests. To avoid app-owners getting annoyed at this, I changed it so that parties and current party gets its own prefetcher, which runs immediately after applicationmetadata and layoutsets have loaded, which is what is needed to determine if its anonymous. And since profile is next in line anyway, this is no longer prefetched.
However, all of these are still prefetched if there is an instance id in the url. So opening an …
> Avoid 401 in anonymous apps due to prefetching

- src/layout/Payment/SummaryPaymentComponent.tsx
It was noticed we did not display the correct data in for the payer name in the receipt. 
This PR fixes that issue and also formats the expirationdate of the card displayed in the receipt.
Result:
- Sprint board
- Labels
> Display name instead of paymentId in name field, and format expiration date

- src/features/payment/OrderDetailsProvider.tsx
- src/features/payment/PaymentInformationProvider.tsx
- src/features/payment/usePerformPaymentMutation.ts
- src/queries/queries.ts
- src/utils/urls/appUrlHelper.ts
- test/e2e/integration/payment-test/payment.ts
Giva current selected language as query parameter to payment endpoints in order to make use of the language functionality in backend.
Also solved an insconsistency with going directly to Nets where it would only work the first time, since the response for paymentInformation would be cached and it would seem like a payment existed even though it had been cleaned up in backend.
- Sprint board
- Labels
> Use language in Nets

- src/features/validation/ComponentValidations.tsx
- src/features/validation/selectors/deepValidationsForNode.ts
- src/features/validation/utils.ts
- src/layout/GenericComponent.tsx
- src/layout/RepeatingGroup/RepeatingGroupPagination.tsx
The culprit turned out to be checking `shouldValidateNode` inside of `getValidationsForNode`. The result of this could somehow change without the node reference updating. This may be due to reusing nodes when they supposedly have not changed? Needed to add back the filter on `shouldValidateNode` the few places that were missing it, most users of `getValdiationsForNode` were already using it anyway.
The changes in `ComponentValidations` are not related, but noticed that the key was a bit fragile.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1716540609951709 …
> Fix edge case where validations may not show up

- src/components/form/Legend.module.css
- src/components/form/Legend.tsx
- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
- src/layout/GenericComponentUtils.tsx
- src/layout/LikertItem/LikertItemComponent.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
- test/e2e/integration/frontend-test/components.ts
Apparently we are already using the new versions of checkboxes and radiobuttons from the design-system, so we may as well use the nicer readOnly state instead of the disabled state. I also added the padlock icon for readonly in our legend, which is used in the Likert component on desktop, so its more consistent with the mobile design.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1717583480896679
- Sprint board
- Labels
> Use proper readOnly state for Checkboxes, Radiobuttons, and Likert

- src/__mocks__/getHierarchyDataSourcesMock.ts
- src/core/ui/RenderStart.tsx
- src/features/expressions/ExprContext.ts
- src/features/expressions/index.ts
- src/features/expressions/shared.test.ts
- src/features/language/LangDataSourcesProvider.tsx
- src/features/language/LangToolsStore.tsx
- src/features/language/useLanguage.ts
- src/features/validation/expressionValidation/useExpressionValidation.test.ts
- src/hooks/useMapToReactNumberConfig.ts
- src/hooks/useSourceOptions.ts
- src/layout/Input/InputComponent.tsx
- src/layout/Input/config.ts
- src/layout/Input/index.tsx
- src/utils/layout/hierarchy.ts
- test/e2e/integration/frontend-test/formatting.ts
Some extensions for the `Input` component's `format` property, as well as adding support for the design-system component's prefix and suffix. https://storybook.designsystemet.no/?path=/docs/komponenter-textfield--docs
Expression support has been added to:
- `formatting.number.prefix`
- `formatting.number.suffix`
- `formatting.number.thousandSeparator`
- `formatting.number.decimalSeparator`
Expressions allow you to refer to text-resources using the `text`-expression, so #717 is solved by #2057.
An example of how to use text-resources with suffix:
```json
"formatting": {
"number": {
"suffix": ["text", "some-text-resource"],
}
}
```
The new prefix/suffix is shown like this next to the input field and is configured in `textResourceBindings`:
`textResourceBindings.prefix`: …
> Expression support for number formatting

- .github/labeler.yml
- .github/workflows/issue-labeler.yml
This PR only modifies the GitHub workflow settings of the repository, no other code changes have been made.
The [issue labeler](https://github.com/github/issue-labeler) has been configured to add the `status/triage` tag to all new (opened) issues.
Unfortunately the functionality of this patch can only be validated from the `main` branch.
> Issue labeler ported from app-lib-dotnet

- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/RadioButtons/ControlledRadioGroup.tsx
- test/e2e/integration/frontend-test/components.ts
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1718872640474839
- Sprint board
- Labels
> Fix alertOnChange for RadioButtons so it does not alert when empty

- src/layout/Grid/GridSummary.tsx
Removing the empty edit-column from the summary grid when viewed in pdf seems to resolve the issue for grid-columns not behaving properly for pdf.
- closes #2201 
- Sprint board
- Labels
> Remove edit-column for grid in pdf

- src/features/pdf/PdfView2.tsx
- src/layout/Summary2/index.tsx
Now rendering SummaryComponent2 in the PDF component so that previous tasks are resolved correctly.
- closes #2191 
- Sprint board
- Labels
> fix: we can now render previous task summaries in pdf

- schemas/json/application/application-metadata.schema.v1.json
Document allowedKeysForUserDefinedMetadata property on data type, which allows configuring which UserAllowedMetadata keys are allowed to be used.
> Document allowedKeysForUserDefinedMetadata property

- package.json
- yarn.lock
This is a fix due to the Map-component using old cache servers that are scheduled for retirement and are slow and unusable
- Sprint board
- Labels
> fix: mapcomponent URL change to use new cache server dependency bump

- src/components/label/LabelContent.tsx
Fixes label rendered as span not getting its styling from the designsystem by allowing the designsystem to set classnames on the span.
- Sprint board
- Labels
> Fix labels rendered as span not getting their styling set

- src/features/baseurlinjection.ts
- src/index.tsx
The browser I tested (Chrome) exhibited different behaviors when resolving relative URLs depending on wether or not the hash for client side routing in the URL was prefixed with a slash or not. In other words
* This worked: `https://pat.apps.tt02.altinn.no/pat/varemerke/#/instance/...`
* This did not: `https://pat.apps.tt02.altinn.no/pat/varemerke#/instance/...` - the resolved absolute URL did not include the app ID
This PR adds a `base` element to the head of the document as early as possible (one of the first imports in index).
- closes https://github.com/Altinn/app-frontend-react/issues/2257
- User …
> Add 'base' element to 'head' to normalize relative urls/references

- src/features/form/layout/LayoutsContext.tsx
In the upcoming #2244 duplicate component IDs in the same layout-set would be a hard error, and will be removed from the layout when first seen. To make sure app developers get time to fix their apps and get to know which components fail this check, I'm adding this code to log an error to DevTools.
- Sprint board
- Labels
> Logging errors when we see duplicate component IDs

- test/e2e/integration/frontend-test/group-pets.ts
Added test case and snapshot for editing component in table with innerGrid, which should be overridden.
-  https://github.com/Altinn/app-frontend-react/pull/2289
- Sprint board
- Labels
> Add test for component in table with innerGrid

- src/layout/Accordion/Accordion.test.tsx
- src/layout/Accordion/Accordion.tsx
- src/layout/Accordion/AccordionItem.tsx
- src/layout/Accordion/config.ts
Added openByDefault property to Accordion, that accepts boolean true/false and expressions
closes https://github.com/Altinn/app-frontend-react/issues/2238
- Sprint board
- Labels
> Added OpenByDefault property to Accordion 2.0 with test

- src/layout/PaymentDetails/PaymentDetailsComponent.tsx
Because the order details are prefetched when the form loads we have to refetch the data when mounting the component in order to not use the stale cached data the was prefetched.
- closes #2277 
- Sprint board
- Labels
> Fix payment information component not fetching latest data on first render

- src/layout/PaymentDetails/PaymentDetailsComponent.tsx
- test/e2e/integration/payment-test/payment.ts
Adding a cypress test make sure orderlines are fetched and displayed for PaymentDetails component.
- Sprint board
- Labels
> Add regression test for PaymentDetails component

- eslint.config.mjs
- src/codegen/run.ts
Generated TS files use eslint to run prettier and to look good, so that the code generator does not have to deal with indentations and whatnot. This fell out recently when the generated files were ignored (in order to not have to deal with `any`s in those files). This adds back support for running eslint, but just ignores anys.
- Sprint board
- Labels
> Adding back `eslint` automatic formatting in generated files

- src/layout/Header/index.tsx
Remove summary2 for the header component because rendering it by default often causes the summary to look disorganized. The old summary concept did also not render a summary for header components.
- Sprint board
- Labels
> remove header summary2

- src/layout/Link/LinkComponent.test.tsx
- src/layout/Link/LinkComponent.tsx
- src/layout/Link/config.ts
Added a download option to the Link component. This is useful in scenarios where users should be able to download a resource instead of navigating to it.
Example: PDF document fetched from service owner as a base64 encoded string. Using Link component with download option, this can be presented to user as a link or button which downloads the file when clicked. 
- Sprint board
- Labels
> Added download option for Link component

- src/features/expressions/expression-functions.ts
- src/features/options/useGetOptions.ts
- src/features/validation/callbacks/onFormSubmitValidation.ts
- src/layout/RepeatingGroup/RepeatingGroup.module.css
- src/layout/RepeatingGroup/Table/RepeatingGroupTable.tsx
- src/utils/layout/generator/LayoutSetGenerator.tsx
- src/utils/layout/types.ts
- src/utils/layout/useExpressionDataSources.ts
- src/utils/layout/useNodeTraversal.ts
Found and fixed a few bugs:
1. Components that were set to be hidden using expressions like `["equals", ["component", ...], "something"]` would not get hidden until after all the nodes had been loaded, because the traversal selector could not traverse the hierarchy until it was ready. In practice, all the node traversal in expressions look up another component ID, so I made a simpler function for that (which always works as long as the nodes have been added first), and then set nodes earlier in the hierarchy generation process.
2. 'Remove stale values' in option components correctly wait until nodes are ready, but they were eager to start working even when there are awaiting commits to the node state. Fixing this makes the removal slower, but safer.
3. The caption title in a nested …
> Fixing problems with removal of stale options

- src/__mocks__/getDataListMock.ts
- src/__mocks__/getInstanceDataMock.ts
- src/features/validation/callbacks/onFormSubmitValidation.ts
- src/layout/Group/SummaryGroupComponent.tsx
- src/layout/Summary/ValidateSummary.tsx
- src/layout/Summary/index.tsx
- src/test/allApps.ts
- src/test/renderWithProviders.tsx
- src/utils/layout/NodesContext.tsx
- src/utils/layout/all.test.tsx
When a `Summary` component pointed to another component that was missing from the layout, that would fail hard, reach the error boundary and make the entire app break in some cases. This should make the error more graceful (and not show up in prod).
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1726216138773189
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1726214776378099
- Sprint board
- Labels
> Fixing hard fail on missing `componentRef` in Summary

- test/e2e/support/custom.ts
- test/e2e/support/global.ts
In #2283, snapshots were added to PDF testing in order to catch visual bugs in PDF. Additionally, print media emulation was added to PDF testing so that css using `@media print` will be applied. This is sometimes used to hide elements, and so it then became possible to test that elements that should be hidden actually are hidden in PDF.
However, the combination of print media emulation and snapshots was not working in this version. This is due to how Percy takes snapshots. Percy does not take screenshots of the browser window directly, but rather, it stores a snapshot of the DOM, uploads this to its own servers, puts this DOM snapshot into its own browser, and takes screenshots at different viewport sizes there. Because of this, we loose the context of our own browser which uses print …
> Direct Percy snapshot method to capture PDF with emulated print media

- src/features/formData/jsonPatch/createPatch.test.ts
- src/features/formData/jsonPatch/createPatch.ts
- test/e2e/integration/frontend-test/all-process-steps.ts
- test/e2e/integration/frontend-test/auto-save-behavior.ts
When the backend responds after a PATCH save operation, we grab the new/latest model from the backend and produce a JsonPatch by diffing our internal models with the backend model. That patch is then applied to our current model. This is all done to make it possible for the user to continue mutating the data model _while the saving request is still in flight_.
However, a somewhat broken assumption/simplified logic in that patch generation caused us to overwrite a list of strings we got from the backend. In the affected app, this list was then re-populated in `ProcessDataWrite`, again triggering the bug on the next save. This caused runaway infinite PATCH requests to be triggered.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1726561518407919
- Automated …
> Fixing a bug causing infinite PATCH requests

- test/e2e/integration/frontend-test/components.ts
- test/e2e/integration/frontend-test/pdf.ts
- test/e2e/support/custom.ts
- test/e2e/support/global.ts
The snapshots for Map and PDF have been a little inconsistent. This is due to a couple of reasons:
1. Percy loaded the real map tiles, because it does not care if I intercept the url in cypress.
2. The location when clicking the map in cypress was not 100% consistent and could be slightly off
3. PDF snapshots used cypress's `blackout` option when taking a screenshot, this does not make fonts monospace, so it would lead to slightly different sized blacked out areas.
To fix these, I did the following:
1. Intercept the component config to rewrite the url of the map layers, so percy should now use the mock tiles as well
2. Before taking a snapshot, overwrite the location to an exact lat/long string
3. Inject the same css we use for percy before taking a screenshot instead of using the …
> Fix flaky Map and PDF snapshots

- src/features/options/useGetOptions.ts
- src/layout/Dropdown/DropdownComponent.tsx
- test/e2e/integration/component-library/dropdown.ts
- test/e2e/support/custom.ts
- test/e2e/support/global.ts
This PR removes the use of a dynamic key prop that was introduced to solve clearing the dropdown when using dynamic options and the source value for the options has changed. This does no longer seem to fix the previous issue.
Removing this workaround no longer causes the dropdown to completely re-render and lose focus after its value has updated.
- closes #2486 
- Sprint board
- Labels
> Fix tab navigation for dropdown

- .github/scripts/purge-frontdoor-cache.sh
- .github/scripts/release.sh
- .github/workflows/release.yml
Purge Azure Front Door cache on release.
- Purging `index.json` should make pre-releases show up in localtest immediately
- For actual releases also purging `/major/` and `/major.minor/` so that e.g. `/4/` or `/4.8/` points to the new version immediately
> Purge azure front door cache on deploy

- src/layout/LikertItem/LikertItemComponent.tsx
- test/e2e/integration/frontend-test/validation.ts
When a question in a likert gets to a certain size, the required indicator (*) rendered on the next line. Moved it inside the label to avoid this happening.
Before:
After: 
- Sprint board
- Labels
> Avoid line break for required indicator in likert

- src/features/datamodel/notations.test.ts
- src/features/devtools/utils/layoutSchemaValidation.ts
- src/features/validation/schemaValidation/SchemaValidation.tsx
- src/features/validation/schemaValidation/schemaValidationUtils.ts
- src/utils/layout/all.test.tsx
- src/utils/schemaUtils.ts
This removes the annoying console warnings that `jsPropertySyntax` is deprecated in AJV, and also fixes a bug in the `processInstancePath` function by deleting it entirely 😄 
- closes #166
- closes #1918
- Sprint board
- Labels
> Switch from using `jsPropertySyntax` to `jsonPointer` in AJV

- src/layout/Datepicker/DatePickerInput.tsx
- src/layout/Datepicker/DatepickerComponent.tsx
Excludes format helper string in datepicker component from percy validation
- closes #2566 
- Sprint board
- Labels
> Add "no-visual-testing" to example date string

- src/layout/List/ListComponent.test.tsx
- src/layout/List/ListComponent.tsx
- src/layout/List/index.tsx
- Removes dataModelBinding validation that asserts that you can only use bindings from table headers. This check was broken when initially added, but fixed in #2108. It turns out that several apps in prod used dataModelBindings for mapping columns that were not shown in tableHeaders, so fixing this dataModelBinding validation was a breaking change.
- Removing `filteredRows` from `ListComponent`. This would filter out values that should not be shown in mobile view if `tableHeadersMobile` was set. The only problem is that the filteredRows object was also used for setting formData, so if you scaled down your browser window, some fields may no longer get saved when you click the row. Added unit tests for this.
- Table was using the raw data-list row when mapping cells in the table body. This …
> Fix bugs in List component

- src/features/validation/nodeValidation/emptyFieldValidation.ts
- src/layout/Checkboxes/CheckboxesContainerComponent.test.tsx
- src/layout/Checkboxes/index.tsx
- src/layout/Dropdown/DropdownComponent.test.tsx
- src/layout/Dropdown/index.tsx
- src/layout/LayoutComponent.tsx
- src/layout/LikertItem/index.tsx
- src/layout/MultipleSelect/MultipleSelectComponent.test.tsx
- src/layout/MultipleSelect/index.tsx
- src/layout/RadioButtons/ControlledRadioGroup.test.tsx
- src/layout/RadioButtons/index.tsx
- src/layout/layout.ts
Makes sure to only validate `required` against `simpleBinding` where the other bindings are just for adding additional data that the user has no control over.
- closes #2599 
- Sprint board
- Labels
> Fix duplicate required validation for options-based components

- src/features/datamodel/DataModelsProvider.tsx
It was somehow possible for language to be used with DatamodelsProvider provided (not `ContextNotProvided`) but still before they had finished loading (value was `null`). So adding a null coalecence to return empty array in those cases for the public hooks. But this means they cannot be used to determine loading, but the LoadingBlocker uses the state directly so it should still work as before.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1729515603349109?thread_ts=1729512254.943649&cid=C02EJ9HKQA3
- Support in …
> Fix/null error in useLanguage

- src/utils/dateHelpers.ts
The date picker save format with timestamp no longer matched the actual save format which comes from `formatISO` with `representation: 'complete'`
- Sprint board
- Labels
> Fixed incorrect datepicker save format

- src/features/options/StoreOptionsInNode.tsx
The logic for removing stale option values was mistakenly also applied to removing the simpleBinding (which cointains the attachment id) of FileUploadWithTag. This components has options after all, but the value is stored on the attachment data element instead of in the data model at the location of simpleBinding as the rest of them do. This caused it to remove the form data value immediately, and if it is inside of a repeating group, the attachment disappears, because it no longer knows which attachment to map.
This was not covered in any cypress test cases, since in `changeName` layout the fileuploadwithtag does not use datamodelbindings, and in `repeating` the filuploadwithtag used `list` instead of `simpleBinding` and so did not experience this issue.
We should definitely add tests …
> Quickfix: Broken FileUploadWithTag and simpleBinding

- src/layout/Address/AddressSummary/AddressSummary.tsx
- src/layout/Checkboxes/CheckboxesSummary.tsx
- src/layout/Datepicker/DatepickerSummary.tsx
- src/layout/Dropdown/DropdownSummary.tsx
- src/layout/Grid/GridSummary.tsx
- src/layout/Group/GroupSummary.tsx
- src/layout/Header/HeaderComponent.tsx
- src/layout/Input/InputSummary.tsx
- src/layout/Likert/Summary2/LikertSummary.tsx
- src/layout/List/ListSummary.tsx
- src/layout/Map/Summary2/MapSummary.tsx
- src/layout/MultipleSelect/MultipleSelectSummary.tsx
- src/layout/Paragraph/ParagraphComponent.tsx
- src/layout/RadioButtons/RadioButtonsSummary.tsx
- src/layout/RepeatingGroup/Summary2/RepeatingGroupSummary.tsx
- src/layout/Tabs/TabsSummary.tsx
- src/layout/TextArea/TextAreaSummary.tsx
Assigns node context to the use of text resource bindings for summary2 components. This allows the summary2 components to use text resource bindings that use row-specific variables based on which row the component exists.
- closes #2606
- Sprint board
- Labels
> Fix text resource bindings for summary2

- src/features/expressions/shared-functions.test.tsx
- src/features/instance/ProcessContext.tsx
- src/features/processEnd/confirm/containers/ConfirmPage.test.tsx
- src/features/receipt/ReceiptContainer.test.tsx
- src/layout/CustomButton/CustomButtonComponent.test.tsx
- src/queries/appPrefetcher.ts
- src/queries/types.ts
- src/setupTests.ts
- src/test/allApps.ts
- src/test/renderWithProviders.tsx
- src/utils/layout/all.test.tsx
Removes `fetchProcessState` from `AppQueriesProvider` to support efforts towards removing `AppQueriesProvider` altogether (because all queries are static and therefore do not need to be in a context + contexts = tight coupling). Also supports further work with parallel signing. 
- Sprint board
- Labels
> removes fetchProcessState from AppQueriesProvider and mocks with jest

- src/components/ReadyForPrint.tsx
- src/components/form/Form.tsx
- src/features/instantiate/containers/InstantiationContainer.tsx
- src/features/instantiate/selection/InstanceSelection.tsx
- src/features/pdf/PDFWrapper.tsx
- src/features/pdf/PdfView2.tsx
- src/features/processEnd/confirm/containers/ConfirmPage.tsx
- src/features/processEnd/feedback/Feedback.tsx
- src/features/receipt/ReceiptContainer.tsx
- test/e2e/integration/frontend-test/pdf.ts
- test/e2e/integration/frontend-test/summary.ts
- test/e2e/manual/page-load.ts
- test/e2e/support/custom.ts
Since we use `#readyForPrint` in our cypress tests to check if the page has finished loading, I added a new id for this use case in the `ReadyForPrint` component. Now only the PDF page will show `#readyForPrint` and the others show `#finishedLoading` instead.
- closes #970
- Sprint board
- Labels
> Prevent PDF generator from printing "Unknown error" page

- src/layout/Datepicker/DatePickerCalendar.tsx
- src/layout/Datepicker/DatePickerInput.tsx
- src/layout/Datepicker/DatepickerComponent.test.tsx
- src/layout/Datepicker/DatepickerComponent.tsx
- src/layout/Datepicker/DatepickerDialog.tsx
- src/layout/Datepicker/DropdownCaption.tsx
- src/layout/Datepicker/index.tsx
- src/utils/dateHelpers.test.ts
- src/utils/dateHelpers.ts
- src/utils/formatDateLocale.ts
- DateInput is able to parse any ISO string, not just the particular format we save
- DateInput automatically fills inn separator characters
- This is similar to how the old one worked
- Now you can only type numbers, and no more than required
- To achieve this, I used the `PatternFormat` which is also used for number-formatting in the `Input`-component. I modify the raw format to have fixed length for day, month, and year to make this work. This also makes the error message less confusing, see: https://altinn.slack.com/archives/C02EJ9HKQA3/p1729692095041289?thread_ts=1729512493.045959&cid=C02EJ9HKQA3
Now it looks like this instead with the default format for `nb`:
- DayPicker: changing month using arrows or dropdowns now works
- DayPicker: clicking the small arrows (chevron) in dropdown …
> Fixing several issues with the new Datepicker and making behavior closer to the old one

- .github/workflows/check-label-added.yml
I noticed an uncategorized change that was caused by the label `kind/feature-request`, which is not used for release notes grouping but was allowed by the label-check. I changed it to only allow the specific labels we use in `release.yml`. Additionally I removed some triggers that are probably not necessary.
- Sprint board
- Labels
> stricter label check

- src/layout/Grid/GridSummary.tsx
Added a missing return statement in order to render the component itself in the summary if the component does not have a title to show or has any relevant display data to show.
- Sprint board
- Labels
> Grid summary did not render components as desired

- src/features/datamodel/DataModelsProvider.tsx
- src/features/datamodel/useBindingSchema.tsx
- src/features/instance/InstanceContext.tsx
- src/features/validation/index.ts
- src/features/validation/nodeValidation/useNodeValidation.ts
- src/layout/AttachmentList/AttachmentListComponent.tsx
- src/layout/Subform/index.tsx
In the latest `app-lib-dotnet`, the backend sends us updated instance data after saving form data. Great stuff, which will fix some issues we've had, but this made some of our greedy selectors re-render components too often, which also at some point caused duplicate components to show up in a repeating group (because the node hierarchy got forcefully re-rendered). This fixes the root cause, but later I'll also open a PR with a fix that makes sure that exact thing cannot happen again even despite re-rendering.
- #2662 …
> Fixing frequent re-renders with latest `app-lib-dotnet`

- src/core/contexts/zustandContext.tsx
- src/utils/layout/NodesContext.tsx
- src/utils/layout/generator/CommitQueue.tsx
- src/utils/layout/generator/GeneratorContext.tsx
- src/utils/layout/plugins/RepeatingChildrenStorePlugin.tsx
Subscribing to a store seems to be a bit expensive, and in some cases it can be avoided. Static functions inside of the store used for updating data will never change, and so does not need to be subscribed to for changes. This makes the node data commit queue significantly cheaper.
- Sprint board
- Labels
> Performance: Make node data commit queue cheaper

- src/features/validation/ValidationStorePlugin.tsx
- src/utils/layout/LayoutPage.ts
- src/utils/layout/LayoutPages.ts
- src/utils/splitDashedKey.ts
`splitDashedKey` showed up during profiling, this is used when searching for nodes using `findById`. The case where this caused a problem was when getting validations for nodes, but in this case we can just use nodes directly instead of using nodeData and searching around. I also added a slightly slimmer funciton for `findById` that only returns the baseComponentId, but I am not sure it makes that much of a difference.
- Sprint board
- Labels
> Performance: Use node directly in getValidations instead of searching by id

- src/utils/layout/LayoutPage.ts
- src/utils/layout/LayoutPages.ts
- src/utils/layout/NodesContext.tsx
- src/utils/layout/useNodeTraversal.ts
This should make node-lookups faster. Previously, every page would be iterated to look for a node object, but as node-ids can no longer be duplicated/re-used across pages, we can just create a Map to look them up directly. This also has the advantage of running `getBaseComponentId()` 0 or 1 times, instead of once-per-page for pages that don't have the node in them. 
I also removed some unused code in node traversal.
- #2699
- #2688
- Sprint board
- Labels
> Making node-lookups faster

- src/utils/layout/NodesContext.tsx
- src/utils/layout/generator/CommitQueue.tsx
- src/utils/layout/generator/GeneratorStages.tsx
- src/utils/layout/generator/NodeGenerator.tsx
Reported by SSB. When submitting a form with a large amount of rows in a repeating group, the submit button could end up stalling the main thread and prompting the user with a 'page is stuck, do you want to leave it?' warning. It turns out this happened because of sequential state updates removing nodes from the hierarchy when unmounting the data task.
This should optimize the situation by collecting all the removal requests and iterating them all more closely in the zustand action function. …
> Queue for removing nodes

- src/components/form/Form.tsx
- src/components/form/LinkToPotentialNode.tsx
- src/components/wrappers/ProcessWrapper.tsx
- src/features/datamodel/DataModelsProvider.tsx
- src/features/expressions/expression-functions.ts
- src/features/instance/ProcessNavigationContext.tsx
- src/features/routing/AppRoutingContext.tsx
- src/hooks/useIsPdf.ts
- src/hooks/useNavigatePage.ts
- src/layout/CustomButton/CustomButtonComponent.tsx
- src/layout/FileUpload/FileUploadComponent.tsx
- src/layout/Subform/SubformComponent.tsx
- src/layout/Subform/Summary/SubformSummaryTable.tsx
When loading app-frontend, the would be a moment where `AppRoutingContext` would be out-of-sync with the real URL, causing the wrong thing to be rendered. For example, for a brief moment the 'you're on the wrong task' screen would be visible while progressing to the next task, only to be corrected a short moment later.
This was all caused by our `AppRoutingContext`. While it did solve re-rendering issues when irrelevant parts of the URL changed (such as the equivalent of `useNavigationParam('instanceGuid')` would re-render your component when the page key in the URL changed), the current (pre this PR) `AppRoutingContext` also has to wait until a `useEffect()` is triggered to update the store, which at _that_ point can run selectors again and cause re-renders that corrects the UI.
This fix …
> Rewriting `AppRoutingContext` to avoid late URL state problems

- src/features/alertOnChange/AlertOnChangePlugin.tsx
- src/features/attachments/AttachmentsPlugin.tsx
- src/features/options/OptionsPlugin.tsx
- src/features/validation/ValidationPlugin.tsx
- src/layout/Cards/CardsPlugin.tsx
- src/layout/Grid/GridRowsPlugin.tsx
- src/layout/Likert/Generator/LikertRowsPlugin.tsx
- src/layout/Tabs/TabsPlugin.tsx
- src/utils/layout/plugins/NodeDefPlugin.tsx
- src/utils/layout/plugins/NonRepeatingChildrenPlugin.tsx
- src/utils/layout/plugins/RepeatingChildrenPlugin.tsx
When we generated plugin lists in generated def files, this runs without code minification. However, after code minification these keys would change into minified class names like `c` (instead of `RepeatingChildrenPlugin`). Reverting to something that's not as 'smart' fixes the problem.
This causes lots of tests to break in #2690, where I used the plugin-keys more run-time.
- Sprint board
- Labels
> Fixing plugin code broken by minification

- src/features/alertOnChange/DeleteWarningPopover.tsx
- src/features/datamodel/DataModelsProvider.tsx
- src/utils/layout/generator/GeneratorStages.tsx
A few minor fixes to make the upcoming `ssb/ra0692-01` more tolerable. This form has very many components, possibly with dynamic behaviour, and simply setting data in the `NodesContext` is noticably slow (presumably because all selectors have to re-run).
1. Removed an undefined class in `src/features/alertOnChange/DeleteWarningPopover.tsx`
2. Making `useLookupBinding()` static. This didn't really need to re-render when DataModelsProvider changes(?). I didn't really look into the root cause for this, but I observed that `<DataModelValidation />` re-rendered for all nodes when clicking a checkbox (which in turn added a row to a repeating group).
3. When multiple new components were discovered in the node generator, these would all call the `restart()` function. This only caused `{}` to be …
> Performance fixes that improved ra0692-01

- src/core/contexts/zustandContext.tsx
- src/hooks/useShallowObjectMemo.ts
useShallow was more expensive than expected, this is due to it constructing a `Map` and iterating its entries to compare two objects. I made a more strict version that can compare objects or arrays but not `Map`s. This avoids allocating any `Map`s or arrays and appears to take roughly 1/6th of the time and use 1/20th of the memory.
This problem was discovered when adding / removing rows in `RA-0692`. useShallow took over 1 second for adding and almost 2 seconds for removig a row, now it takes less than 250ms. Still a bit expensive, but should make a very noticable impact. The next step could be analysing what has to run useShallow so many times, and trying to cut that down. …
> Cheaper version of zustand's useShallow

- src/layout/Likert/Generator/LikertGeneratorChildren.tsx
- src/utils/layout/NodesContext.tsx
- src/utils/layout/generator/CommitQueue.tsx
- src/utils/layout/generator/GeneratorStages.tsx
- src/utils/layout/generator/NodeRepeatingChildren.tsx
- src/utils/layout/plugins/RepeatingChildrenStorePlugin.tsx
In `ssb/ra0255-02`, when generating a PDF at the end of the data task, app-frontend spent a long time cleaning up rows when exiting the data task. This could lock up frontend for a while, and even trigger a 'this page is unresponsive' message for the user. Using a queue to remove rows fixes this problem.
- #2704
- https://altinn.studio/repos/ssb/ra0255-02/issues/12
- Sprint board
- Labels
> Queue for removing rows

- src/features/devtools/utils/layoutSchemaValidation.ts
- src/layout/RepeatingGroup/config.ts
Setting `maxCount` on a `RepeatingGroup` component to `1` gave you a cryptic JSON-serialized error message straight from AJV in development environments. Implementing a prettier error message for that, and allowing you to set `maxCount: 1` in a RepeatingGroup.
The reason this was required to be a minimum of 2 earlier is historical; that's the way we used to differentiate between non-repeating groups and repeating groups (when the `Group` component implemented everything). It should now be possible to have a RepeatingGroup including either 0 or 1 rows, if you so wish. 
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1732545299300419
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utfor …
> Allowing `maxCount: 1` in RepeatingGroup

- cypress.config.js
- src/features/propagateTraceWhenPdf/index.ts
- src/features/routing/AppRoutingContext.tsx
- src/index.tsx
- test/e2e/integration/frontend-test/pdf.ts
- test/e2e/integration/subform-test/subform.ts
- test/e2e/support/custom.ts
- test/e2e/support/global.ts
- test/e2e/support/navigation.ts
- test/e2e/support/start-app-instance.ts
When rendering PDF, get W3C `traceparent` propagated by the app and pass it back to the app when making subsequent requests.
Backend PR: https://github.com/Altinn/app-lib-dotnet/pull/924
Tested locally using Application Insights both with  OTel and the classic App Insights SDK
I don't know what the best place for this code is, but at least it needs to be pretty far upstream so that the interceptor is added before any downstream requests are made.
- N/A
- Sprint board
- Labels
> Pass tracecontext from PDF generator cookies back to app

- benchmarks/splitDashedKey.ts
- benchmarks/tsconfig.json
- package.json
- src/utils/splitDashedKey.ts
- yarn.lock
A benchmarking harness using `tinybench` as a suggestion to start tracking perf numbers. Using benchmarking provides us a paper trail - when we discover slow code that affect real usecases, we can provide benchmarks to show improvements in isolation. Upon future changes we can verify change in perf characteristics (for a variety of inputs) such as 
* Throughput
* Latency 
* Std deviation (I'm not sure if it's possible to see the whole distribution, e.g. to rule out bimodal distributions)
Memory allocations is missing, I couldn't find a way to correctly correlate heap changes to benchmark runs, as there might be GCs occurring in the middle of runs.
The included benchmark is a microbenchmark comparing some implementations of `splitDashedKey` that did pop up in some profiling (although this …
> Tiny benchmarking harness

- src/codegen/Common.ts
- src/layout/Likert/Generator/LikertGeneratorChildren.tsx
- src/layout/Likert/LikertComponent.tsx
- src/layout/Likert/config.ts
- src/layout/LikertItem/LikertItemComponent.module.css
- src/layout/LikertItem/LikertItemComponent.tsx
- src/layout/LikertItem/config.ts
- Adds the option to have a divider between the answer columns of the Likert component.
- closes #2671
- Sprint board
- Labels
> Add divider to Likert

- src/components/presentation/Presentation.tsx
- src/components/wrappers/ProcessWrapper.tsx
- src/core/loading/Loader.tsx
- src/features/devtools/DevTools.module.css
- src/features/devtools/DevTools.tsx
- src/features/devtools/DevToolsPanel.tsx
- src/features/devtools/components/DevNavigationButtons/DevNavigationButtons.tsx
- src/features/pdf/PdfView2.tsx
- src/layout/Subform/SubformWrapper.tsx
Fixes dev-tools crashing in subform. Also makes the subform-loading look a bit better by not showing an empty form container.
Added an error boundary inside of the dev tools panel as well, so errors like this are less annoying in the future
Cleaned up dev tools component by removing `{children}` since we no longer wrap the application in it.
- closes #2818 
- Sprint board
- Labels
> Fix DevTools in subform

- .github/scripts/release.sh
- .github/workflows/pr-actions.yml
Workflows for doing stuff in response to PR comments.
Works similarly in app-lib, with the exeception of using MinVer there. Here I opted for using a local tag prior to running the release script, so the hope is that the only required change there is to update the version regex. With this change I expect PR releases to be published to the CDN repo (and Azure Storage), though it has to be tested from main since that's where the workflow has to be for `issue_comment` triggers
- https://github.com/Altinn/app-frontend-react/issues/2822 …
> Actions (publish) based on PR comments

- src/app-components/Label/Label.module.css
- src/app-components/Label/Label.tsx
- src/layout/ComponentStructureWrapper.tsx
- src/layout/OrganisationLookup/OrganisationLookupComponent.module.css
- src/layout/OrganisationLookup/OrganisationLookupComponent.tsx
- src/layout/PersonLookup/PersonLookupComponent.module.css
- src/layout/PersonLookup/PersonLookupComponent.tsx
Spacings were a bit off.
- Sprint board
- Labels
> Fixes label, input and error message spacings in org and person lookup

- src/components/PDFGeneratorPreview/PDFGeneratorPreview.tsx
- src/features/devtools/DevTools.tsx
- src/features/devtools/components/PDFPreviewButton/PDFPreviewButton.tsx
- src/features/instantiate/containers/InvalidSubformLayoutError.tsx
- src/features/instantiate/containers/UnknownError.tsx
- src/hooks/delayedSelectors.test.tsx
- src/hooks/delayedSelectors.ts
- src/hooks/useIsDev.test.ts
- src/layout/GenericComponent.tsx
- src/utils/isDev.test.ts
- src/utils/isDev.ts
- src/utils/layout/generator/validation/GenerationValidationContext.tsx
- test/e2e/integration/frontend-test/all-process-steps.ts
- test/e2e/integration/frontend-test/dynamics.ts
Multiple apps had problems with `["component", ...]` expressions after the performance-related fixed in the release on the 27th of november. This problem was caused by the new multiple-delayed-selectors functionality, specifically the code that tried to reduce the amount of re-renders triggered when state changes. Unit-testing uncovers that React _marks the component for re-rendering_, so we don't have to worry about multiple re-renders being triggered after all. Removing that code fixes the problem.
Also:
- Adding a unit-test to test simple functionality for multiple delayed selectors
- Adding a cypress test more closely resembling the actual use-case that triggered this problem. 10 components are chained visible via `["component", ...]` expressions, and without this fix the third one …
> Fixing failing `component` lookups when deeply linked

- src/layout/Datepicker/DropdownCaption.tsx
`onValueChange` returns an array of values, for single select this is either one value or an empty array, therefore `values[0]` can be either `string | undefined` even though typescript says it's `string`.
- closes #2841
- Sprint board
- Labels
> Fix Datepicker crashing when deleting year or month from picker

- src/App.test.tsx
- src/components/organisms/AltinnAppHeader.test.tsx
- src/components/presentation/OrganisationLogo/OrganisationLogo.test.tsx
- src/components/presentation/Presentation.test.tsx
- src/core/texts/appTexts.test.tsx
- src/features/expressions/shared-context.test.tsx
- src/features/expressions/shared-functions.test.tsx
- src/features/formData/FormData.test.tsx
- src/features/formData/FormDataReaders.test.tsx
- src/features/processEnd/confirm/containers/ConfirmPage.test.tsx
- src/features/receipt/ReceiptContainer.test.tsx
- src/features/stateless/getAllowAnonymous.test.tsx
- src/layout/AttachmentList/AttachmentListComponent.test.tsx
- src/layout/CustomButton/CustomButtonComponent.test.tsx
- src/layout/FileUpload/FileUploadComponent.test.tsx
- src/layout/FileUpload/Summary/AttachmentWithTagSummaryComponent.test.tsx
- src/layout/InstantiationButton/InstantiationButton.test.tsx
- src/setupTests.ts
- src/utils/layout/all.test.tsx
Bare litt forbedret formatering for enklere lesing 💁‍♀️ 
- Sprint board
- Labels
> Minor test formatting fixes

- test/e2e/integration/frontend-test/group.ts
- test/e2e/support/custom.ts
For a while now, a few percy snapshots have been showing up as 'usual suspects' where the navigation buttons disabled state will toggle all the time. This seems to happen because of 'bad timing' as the snapshot code tries to wait until form data is saved, but it fails to catch the navigation buttons being disabled. I suspect this happens because the saving starts _after_ the snapshot code has 'waited until data is saved', but I'm not entirely sure. For that reason I'm applying multiple band-aids here, in hopes that at least one will prevent this issue. …
> Fixing the flaky percy snapshots (disabled nav-buttons)

- src/core/contexts/queryContext.tsx
- src/utils/layout/LayoutPage.ts
These are some fixes that for things that are not actually problems right now, but could become problems in the near future.
In `feat/navigation` I added some ui settings to the `layout-sets` file that needed some post-processing. It turned out that adding a `process`-function that changed the results somewhat (creates a new object) would cause problems when the query cache became stale after 10 minutes. It would trigger it to re-render with the same data, but because of the processing it would return a new object which caused the nodes to be re-created. (this is a known weakness and gets logged to the browser console). To deal with this I added a `useMemo` so that the same data should not create a new object if it runs multiple times.
A consequence of this issue was that nodes got added …
> Fix future issues with processing layout-sets

- src/features/validation/ValidationStorePlugin.tsx
- src/features/validation/selectors/deepValidationsForNode.ts
- src/layout/RepeatingGroup/Table/RepeatingGroupTableRow.tsx
- test/e2e/integration/frontend-test/validation.ts
- test/e2e/pageobjects/app-frontend.ts
This bug was introduced because I didn't understand the concept in `useDeepValidationsForNode()` when refactoring, so I turned `onlyChildren = true` into "stop at depth 1" (i.e. only immediate children, not nested children) instead of the correct interpretation of "don't include validations on the node itself" (i.e. only get validations for children).
Added a cypress test for this as well, so that we don't end up doing the same mistake again. I removed the `describe('Falsy values', () => {` grouping in this test, because it's wrapping lots of tests that doesn't have to do with falsy values - ignore all the indent-changes in the cypress test.
- closes #2702
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikli …
> Broken deep validations in nested repeating groups

- src/features/options/useGetOptions.ts
- test/e2e/integration/frontend-test/group-pets.ts
When working on the new `Option` component, I wanted to use (and improve) the `pets` page in `ttd/frontend-test`. When fixing that page, using some of the newer functionality, I found a bug which caused the `optionFilter` expression to break when running on options from `source`. As `rowNode` and `dataModelLocation` are removed, they would mutate the objects received from `useSourceOptions()`, breaking future updates.
- Sprint board
- Labels
> Fixing mutation of options causing broken `optionFilter` when used along with `source` options

- src/layout/RepeatingGroup/Summary2/RepeatingGroupTableSummary/RepeatingGroupTableSummary.module.css
- src/layout/RepeatingGroup/Summary2/RepeatingGroupTableSummary/RepeatingGroupTableSummary.tsx
Propagerer `columnSettings` også ned til `<td>`-elementer.
Gjør også knappekolonnen "så liten som mulig".
Eksempel med og uten for 
```
{
alignText: "right",
width: "auto"
}
```
- Sprint board
- Labels
> Fixes to RepeatingGroup Table Summary2 CSS

- src/__mocks__/getPartyMock.ts
- src/features/instantiate/containers/InstantiateContainer.tsx
- src/features/language/LanguageProvider.tsx
- src/features/pdf/PDFWrapper.test.tsx
- src/features/profile/ProfileProvider.tsx
- src/test/renderWithProviders.tsx
Handles missing profile without breaking the UI. Required to be able to process/next an instance in the context of a service owner token when the current step is datautfylling
- https://github.com/Altinn/app-lib-dotnet/issues/908
- Related PR: https://github.com/Altinn/app-lib-dotnet/pull/880
- To make testing easier locally: https://github.com/Altinn/app-localtest/pull/133
- Sprint board
- Labels
> Handle missing profile when the logged in client in not a user (e.g. service owner)

- src/app-components/Label/Label.module.css
Helptext is wrapped with label on every form element with label. If the label is too large the space for the helptext icon is shrinking to a size that minifies the helptext icon. 
- closes [#2470](https://github.com/Altinn/app-frontend-react/issues/2470)
- Sprint board
- Labels
> Help text bubble size affected by component title length

- src/layout/Datepicker/index.tsx
Warn the app developer when there is a mismatch between `timeStamp` on the datepicker (the save-format) and the `format` in the data model (which validates the save-format). In the future we should consider removing the option of saving a timestamp (since you can't even pick that) or at least change the default (#2659). I suspect that #2812 is due to this kind of mismatch.
- closes #1994
- Sprint board
- Labels
> Validate and warn mismatch between `format` and `timeStamp`

- src/test/allApps.ts
- src/utils/layout/all.test.tsx
I added some code to extract the frontend/backend versions from apps, when using the toolbox I've been using for (for example) `all.test.tsx`. To get a list of frontend/backend version combinations, I ran the following:
```typescript
describe('Count all apps', () => {
it('should count all apps', () => {
const dir = ensureAppsDirIsSet();
if (!dir) {
return;
}
function makeKey(frontendMajor: number, backendMajor: number) {
return `v${frontendMajor}/v${backendMajor}`;
}
const counts = new Map<string, { count: number; apps: string[] }>();
const all = getAllApps(dir)
.filter((app) => app.getFrontendVersion())
.filter((app) => app.getBackendVersion());
for (const app of all) {
const key = makeKey(app.getFrontendMajorVersion()!, app.getBackendMajorVersion()!);
const orgApp = app.getOrgApp(); …
```
> Adding code for finding app frontend/backend versions

- src/layout/Custom/CustomWebComponent.tsx
Allowing not including field when using simple binding, fixed bug when generating passThroughProps
- According to docs you should not have to pass a field in the custom event when using simplebinding, this is now fixed and giving you an error if you are not using simpleBinding _and_ not passing field in the event.
- Fixed an issue where you get a JSON circular dependency error when generating passThroughProps because we tried to include the div ref.
- closes https://github.com/Altinn/app-frontend-react/issues/2027
- …
> Issues in Custom component

- src/components/ReadyForPrint.tsx
- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/SigneeList/SigneeListSummary.tsx
> Render signe state for signee list summary, await fetching queries before #readyforprint

- src/features/expressions/expression-functions.ts
- src/features/expressions/index.test.ts
- src/features/expressions/index.ts
- src/features/expressions/schema.test.ts
- src/features/expressions/shared-functions-exist.test.ts
- src/features/expressions/shared-functions.test.tsx
- src/features/expressions/shared-tests/functions/if/fail-else-as-expr.json
- src/features/expressions/types.ts
- src/features/expressions/validation.ts
- test/e2e/integration/frontend-test/all-process-steps.ts
This is the first PR in a series. When implementing the new `compare` function, date comparison functions, etc, I saw a few problems and common mistakes in `expression-functions.ts` that I'll clean up here.
1. Before an expression function is called, the expression engine will evaluate arguments (if they are function calls) and cast values to the data type you've said the function accepts. So when typescript tells you an argument is a `string | null` there's no need to both check it for null and if it's another type than string. Validation happens automatically, and before the function is called, so I removed some attempts to validate incoming arguments inside expression functions.
2. For some reason, the typing for the big object fell apart when I introduced multiple new functions. As …
> Reworking how expression functions are defined

- src/features/options/OptionsPlugin.tsx
- test/e2e/integration/frontend-test/pdf.ts
- test/e2e/support/custom.ts
- test/e2e/support/index.ts
Option plugin now implements `stateIsReady` to make sure all options have loaded before getting marked as ready. This causes the loading screen to appear while options are loading initially, but not when changing dynamically later. This means that #readyForPrint cannot be shown before options are finished loading.
Additionally, I discovered that the PDF testing was not working as intended. Even though the cypress runner appeared to use the new `defaultCommandTimeout` it did not actually work, and it would still wait up to 20 seconds. To actually test that the callback checks pass immediately, I use a `setTimeout` with 0 milliseconds that throws an exception unless the callbacks finish and clear the timer first.
- closes #2947 
- UU/WCAG …
> Make sure options are loaded in PDF

- src/layout/Audio/Audio.tsx
- src/layout/ComponentStructureWrapper.tsx
- src/layout/Video/Video.tsx
Removed unnecessary `ComponentStructureWrapper` around `Video` and `Audio` components in order to remove white space under them when inside cards. `Image` did not have this wrapper.
Before: 
Now: 
- [] Has been added/updated
- [] Issue(s) created for support in Studio
- Sprint board
- Labels
> Removes empty space under video and audio in cards on position bottom

- test/e2e/integration/frontend-test/pdf.ts
- test/e2e/integration/subform-test/subform.ts
- test/e2e/support/custom.ts
- test/e2e/support/global.ts
- test/e2e/support/index.ts
- test/e2e/support/start-app-instance.ts
This is a follow-up of #2958, the changes here makes the test I added in the previous PR redundant as this makes random failure much more likely if the `#readyForPrint` logic is insufficient. Even though I could safely remove that test here, it's important to keep in mind that everything is not covered automatically now. For example, the `changeName` test with the map component will probably not fail for any other reason than the map since the tiles almost always load last and gives a lot of time for other things to load while waiting on those.
Changes:
- Added (optional) response fuzzing while loading the PDF layout. This delays all requests by a different random amount. If tests suddenly become flaky, that could be a sign that PDFs don't always load completely.
- You cannot really …
> Better fuzz testing for PDF generation

- src/app-components/Pagination/Pagination.module.css
- src/app-components/Pagination/Pagination.tsx
- src/features/instantiate/selection/InstanceSelection.tsx
- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/List/ListComponent.module.css
- src/layout/List/ListComponent.tsx
- test/e2e/integration/frontend-test/list-component.ts
- test/e2e/pageobjects/datalist.ts
Use Designsystemet instead of altinn/designsystem for Pagination on InstanceSelection and ListComponent.
Made a component in app-components for pagination that wraps the Designsystemet Pagination component, used this on the InstanceSelectionComponent and ListComponent
- #2788
- Sprint board
- Labels
> Use Designsystemet instead of altinn/designsystem for Pagination

- src/features/attachments/StoreAttachmentsInNode.tsx
- src/hooks/useShallowObjectMemo.ts
- src/language/texts/en.ts
- src/language/texts/nb.ts
- src/language/texts/nn.ts
- src/layout/FileUpload/FileUploadComponent.test.tsx
- src/layout/FileUpload/FileUploadLayoutValidator.tsx
- src/layout/FileUpload/index.tsx
- src/layout/FileUploadWithTag/index.tsx
- src/utils/layout/NodesContext.tsx
When binding multiple `FileUpload` or `FileUploadWithTag` components to the same path in the data model, you'd end up with components fighting over which one manages the binding, and they'd make infinite loops that crash app-frontend. Throwing errors about this instead.
- https://altinn.slack.com/archives/C02EJ9HKQA3/p1738582214908209
- https://altinn.slack.com/archives/C02FK32SFA4/p1738759699145159
- Sprint board
- Labels
> Warning about `FileUpload` components with duplicate bindings

- src/features/formData/FormData.test.tsx
- src/features/formData/FormDataWrite.tsx
- src/hooks/useIsProcessing.ts
- src/hooks/useNavigatePage.ts
- src/layout/NavigationBar/NavigationBarComponent.module.css
- src/layout/NavigationBar/NavigationBarComponent.tsx
- src/layout/NavigationButtons/NavigationButtonsComponent.tsx
- src/utils/layout/NodesContext.tsx
- test/e2e/integration/component-library/summary-of-previous-task.ts
- test/e2e/integration/frontend-test/summary.ts
- test/e2e/support/custom.ts
The problem in the linked issue stemmed from how we figured out the next page when using `navigateToNextPage`. It would look at the raw url and split on `?` and take the first part, assuming those only appear in the end of the hash part. But, when using a returnUrl, that is a "real" queryParameter before the hash even begins, so it would effectively remove all of the information in the hash and the next page could not be determined.
I cleaned up the logic surrounding this, and also made some other changes. I tried to address the issues that caused us to add the hotfix where we disable the navigation buttons while saving. Instead, I now wait for saving after the button is clicked, showing a spinner on the one you clicked (next / previous) and disabling the other. Another issue I noticed …
> Fix page navigation when using returnUrl

- src/components/presentation/NavBar.tsx
- src/features/formData/FormDataWrite.tsx
- src/hooks/useNavigatePage.ts
- test/e2e/integration/frontend-test/auto-save-behavior.ts
Cypress test for auto-save-behavior became a bit flaky after #2970. The reason was that when checking the box that show the repeating group in the test app, that repeating group contains a dropdown component with a preselectedOption index. This will run an effect that updates the data model with the default selected option, which sometimes caused two saves to happen when the test only expected one. I would argue the behavior now is better, as it would previously leave that change unsaved when changing page fast enough, whereas now additional changes like this are more likely to get saved. To get a consistent number of saves I added a wait for the repeating group to show up + 100ms so that the effect has time to fire so that the preselected option gets included in the save call. …
> Fix flaky auto save test and add spinner to back button

- src/features/instantiate/InstantiationContext.tsx
Bug report from service desk: https://github.com/Altinn/altinn-support-private/issues/4002
Slack thread: https://digdir.slack.com/archives/C076GU2QHCG/p1738842092707849
This is a process that doesn't actually exist for us at the moment, but when this fix eventually gets _deployed_, we need to communicate this issue back to service desk/interested parties.
- Sprint board
- Labels
> Allow instantiation retry after failed attempt

- sonar-project.properties
Ignore files that don't need to be scanned by sonarcloud to avoid an artificially low score. 
- Sprint board
- Labels
> Ignore more when running sonar project scan

- .github/workflows/unit-tests.yml
- src/features/instantiate/InstantiationContext.tsx
- src/features/instantiate/containers/InstantiateContainer.tsx
- test/e2e/integration/frontend-test/party-selection.ts
- test/e2e/integration/stateless-app/party-selection.ts
- test/e2e/pageobjects/party-mocks.ts
Adding automated tests for re-instantiation. Also removing ref-states and trying to simplify how this works, and making sure to clear an ongoing/failed instantiation when the user leaves the page (such as navigating back to party selection manually) which previously made the app display the loading-spinner indefintely.
- closes #2862
- closes #2997
- tests functionality implemented in #2985
- Sprint board
- Labels
> Adding tests for re-instantiation, fixing rare eternal loading 

- src/components/PDFGeneratorPreview/PDFGeneratorPreview.tsx
- src/features/instance/InstanceContext.tsx
- src/features/instance/ProcessContext.tsx
- src/features/instantiate/containers/InstantiateContainer.tsx
- test/e2e/integration/frontend-test/party-selection.ts
When cleaning up node traversal in #3009, I saw that in some test-runs the `DataModelsProvider` would try to load data elements that wasn't present in the current instance. The URLs were always different, with new UUIDs for each data element each time, but I couldn't figure out where they came from. After debugging I found that `InstantiateContainer` cleaned up the instantiation and re-mounted again right after, causing it to instantiate twice. In addition to that, `InstanceContext` only stores the instance id from the first instantiation, causing a mismatch when loading the data models (it used the instance id from the first one, but the data from the last one).
- Bug was introduced in #2999 …
> Fix for rare duplicate instantiation

- test/e2e/integration/frontend-test/components.ts
The part that waited for the map tiles to fade in was apparently not sufficient. It used to just check that all tiles have `opacity: 1`. However, it turns out that tiles have `opacity: 1` before they are loaded, and then they start fading from 0 after loading. Leaflet sets a class `leaflet-tile-loaded` when they have loaded so I now check that both have to be true at the same time. Even though percy did not report a diff in this test, I suspect it works better as you can still tell that the tiles are slightly faded in the before snapshot. The gray color of the tiles in the before snapshot has a hex value of `c6c6c6`, and in the after snapshot they are `c0c0c0` which is exactly what the actual image has. Maybe its random, but I hope its less flaky now.
> try to fix map loading before snapshot

- src/core/loading/LoadingRegistry.tsx
- src/features/form/FormContext.tsx
- src/index.tsx
- src/test/renderWithProviders.tsx
- test/e2e/integration/subform-test/subform.ts
When loading a full task Summary2 component, it will add new `FormProvider` contexts for subforms. However, this failed badly when loading static options from inside those subforms, as the new `LoadingRegistry` was shared among all `FormProvider` instances. Adding this provider to every `FormProvider` instead fixes the infinite loading problem that was introduced in this case.
- closes #3019
- Sprint board
- Labels
> Fixing Summary2 + Subform with option-components

- src/layout/Map/Map.tsx
- src/layout/Map/MapComponent.module.css
- test/e2e/support/custom.ts
In the PDF, the map component has been rendering with its bounds off center for some time, and it appears that the problem was introduced in https://github.com/Altinn/app-frontend-react/pull/2487. This change scaled down the global font-size when using `@media print`, and since the map component's height was defined in `rem` this caused the height to get much smaller when the browser calls print, which results in the bottom part getting cut off like this (the pin should be roughly in the center of the map):
In general we cannot change the bounds of the map at this point since we cannot load new tiles or do anything else asynchronously in the `beforePrint` event, so we have to make sure that the bounds are fit correctly before the browser prints. Changing the size to use `px` instead …
> Fix map not centered in PDF

- test/e2e/integration/component-library/date-formatDate.ts
Now that all of this is out in a preview-release on backend, I can add the end-to-end test I made to compare and make sure dates and `formatDate` expressions work as expected (even when changing the browser timezone, which can't be done on the fly in our unit tests).
- #2961
- https://github.com/Altinn/app-lib-dotnet/pull/1067
- Sprint board
- Labels
> Cypress test for end-to-end testing dates and `formatDate`

- src/features/devtools/components/ExpressionPlayground/ExpressionPlayground.tsx
- src/features/expressions/errors.ts
- src/features/expressions/expression-functions.ts
- src/features/expressions/index.test.ts
- src/features/expressions/index.ts
- src/features/expressions/shared-functions.test.tsx
- src/features/expressions/types.ts
- src/features/form/dynamics/HiddenComponentsProvider.tsx
- src/features/language/useLanguage.ts
- src/features/options/evalQueryParameters.ts
- src/features/options/useGetOptions.ts
- src/features/options/useGetOptionsQuery.ts
- src/features/options/useSourceOptions.ts
- src/features/validation/expressionValidation/ExpressionValidation.tsx
- src/utils/layout/all.test.tsx
- src/utils/layout/generator/LayoutSetGenerator.tsx
- src/utils/layout/generator/NodeGenerator.tsx
- src/utils/layout/generator/useEvalExpression.ts
- src/utils/layout/useDataModelBindingTranspose.ts
- src/utils/layout/useExpressionDataSources.ts
- src/utils/layout/useNodeTraversal.ts
In #3009 I removed most simple usages of node traversal. This removes a few larger ones, in:
- `ExpressionValidation`
- `ExpressionPlayground` (devtools)
- `HiddenComponentsProvider`
To make some of these work, I had to introduce something else to refer to nodes (so that I could pass strings instead of `LayoutNode`/`LayoutPage` objects to functions that could take both). I introduced a `LayoutReference` object as a stop-gap solution that's leaner than `LayoutNode`/`LayoutPage`, although it might not get all the way where we want.
- #3009 …
> Removing more node traversal usages

- src/layout/SigneeList/SigneeListComponent.test.tsx
- src/layout/SigneeList/SigneeListSummary.tsx
- src/layout/SigneeList/SigneeStateTag.test.tsx
- src/layout/SigneeList/SigneeStateTag.tsx
- src/layout/SigneeList/api.test.ts
- src/layout/SigneeList/api.ts
- src/layout/SigningStatusPanel/SigningStatusPanelComponent.test.tsx
> Updates signee notification status from backend

- .gitignore
- package.json
- scripts/cypress-run-all.ts
- template.env
I reviewed old issues and came across #214. Then I remembed I had this script laying around somewhere, so I dug it out. Opening a PR for it here if more people want it.
I usually run it something like this:
```sh
yarn cy:all --env environment=docker,host=localhost:8080 --config retries=1
```
- closes #214
- Sprint board
- Labels
> Script to run all test apps and cypress tests locally

- src/features/options/CodeListsProvider.tsx
- test/e2e/integration/frontend-test/attachments-in-group.ts
I was trying to reproduce and find a solution for #2117 when I stumbled upon a bug with the `CodeListsProvider` I made for the `optionLabel` expression function, and to at the same time replace the former option prefetcher. The problem here was that a component used the same option list without a mapping, and would come in later to overwrite the entry in `CodeListsProvider` with a `storeInZustand: false` flag, making sure the option list was not available to the `optionLabel` function after all. 
- #2117
- Support …
> Fixing missing codelists for `optionLabel` function

- src/layout/List/ListComponent.tsx
- src/layout/List/ListSummary.tsx
- src/layout/List/config.ts
- src/layout/List/index.tsx
- src/layout/List/useValidateListIsEmpty.ts
- test/e2e/integration/component-library/list.ts
With this change, the data model binding in `List` matches that used for `object[]` types in `RepeatingGroup` (which also adds/removes rows). This should make the setting less confusing when we port this over to `Checkboxes` and `MultipleSelect` later, which hopefully should also get a `list` binding in the future (ref #273). Having both `list` and `saveToList` at that point would be confusing, so we should fix this before releasing #3007.
Also fixing a few minor issues I found:
- `useDisplayData()` for the `List` component now works with the `group` binding (it returns comma-separated strings, using `summaryBinding` when set).
- Data model binding validation didn't account for deeply nested properties in the data model, and also assumed the binding key was the same as the property name …
> Renaming new binding in `List` from `saveToList` to `group`

- src/components/presentation/Header.tsx
- src/components/presentation/OrganisationLogo/OrganisationLogo.module.css
- src/features/pdf/PDFView.module.css
- src/features/pdf/PdfView2.tsx
- src/hooks/useAppLogo.ts
- test/e2e/integration/component-library/pdf.ts
- After talking with @Edavda , we decided on some minor tweaks to the sizing of organization logo, as well as increasing the size of `large` in PDF, which previously defaulted to the same size as `medium`, since the breakpoint only applied to `screen` and not to `print`.
- We also decided to move the default position of the logo in PDF to be above the app title and org, as this will be in line with the rules for the norwegian coat of arms, as well as several other requests for moving the logo in PDF. If a need for more custom positioning comes up, we can consider that in a new issue.
- Finally, `displayAppOwnerNameInHeader` no longer affects whether or not the org name is shown above the app title. Now this is always shown instead of being shown only when you also show the org name next …
> Fixes for organization logo

- src/features/validation/expressionValidation/ExpressionValidation.tsx
When looking up relative paths in the data model in expression validation, this no longer worked now that the node data is no longer being used to resolve that relative path. This did not fail any tests because the `ttd/expression-validation-test` app used `["argv", 0]` for looking up in the data model, but it was also possible to use the full path manually (which I broke in the latest release).
Updating the test app to look these up with a full path when this fix has been merged, so that we get regression test coverage. 
- closes #3165
- reverts #3077 (at least the bug that was introduced there)
- User …
> Adding current data model path to expression validation

- src/features/expressions/expression-functions.ts
- src/features/expressions/shared-tests/functions/stringReplace/replace-with-null.json
This should have been the behaviour when this was released, but that was not the case. [When searching](https://altinn.studio/repos/explore/code?q=replace&l=JSON&fuzzy=false), it seems this expression is still only used in the app developed by Ronny (who reported the issue).
- closes #3151
- https://github.com/Altinn/app-lib-dotnet/pull/1214
- Sprint board
- Labels
> Treating null as empty string in `stringReplace`

- .github/pull_request_template.md
- .github/workflows/check-label-added.yml
This should make github check for backporting labels, just like in `app-lib-dotnet`.
- Sprint board
- Labels
> Checking for backport labels

- src/layout/Dropdown/DropdownComponent.test.tsx
- src/layout/Dropdown/DropdownComponent.tsx
- src/layout/Dropdown/config.ts
- src/layout/MultipleSelect/MultipleSelectComponent.test.tsx
- src/layout/MultipleSelect/MultipleSelectComponent.tsx
- src/layout/MultipleSelect/config.ts
It is not recommended by the Designsystem to use autocomplete with select and multi-select type components, as the autocomplete list will interfere with the option list. 
Also it might not make sense to use autocomplete with these components because the value saved in the browser for a given autocomplete category might not exist within the possible options.
Currently only one deployed app (in TT02) is using the autocomplete property for dropdown, setting it to `"off"`.
No deployed apps are using the autocomplete property with the mulitpleselect component. …
> Remove autocomplete from dropdown and multiselect

- src/app-components/Button/Button.tsx
- src/layout/Button/ButtonComponent.tsx
- src/layout/Button/config.ts
- src/layout/Link/LinkComponent.tsx
- src/layout/Link/config.ts
- src/layout/NavigationButtons/NavigationButtonsComponent.module.css
- src/layout/NavigationButtons/NavigationButtonsComponent.tsx
- src/layout/PrintButton/PrintButtonComponent.tsx
- test/e2e/integration/component-library/button.ts
- test/e2e/integration/component-library/link.ts
Buttons now support:
- Expanding to full width:
- Size: small, medium and large
- Text align: left, center and right
- Sprint board
- Labels
> added size, textAlign and fullWidth to button components

- src/components/PDFGeneratorPreview/PDFGeneratorPreview.tsx
I'm not sure why the `PDFPreviewButton` was limited in this way, but it seems it was intentional that the button should not work in non-data tasks and in a production environment. I tested this in prod(!) myself, and the button works with this limitation removed.
- closes #3256
- closes #3251
- Sprint board
- Labels
> Removing limitations for PDFPreviewButton

- .github/pull_request_template.md
- src/layout/Summary/ValidateSummary.tsx
- src/utils/layout/NodesContext.tsx
Nodes may come and go, but the layout will always remain. Fixing the linked issue by checking that a component exists via `layoutLookups` instead of the nodes context.
- https://altinn.slack.com/archives/CCQEQKGJD/p1743763779154339
- #3219
- Sprint board
- Labels
> Fixing rare error message when nodes are rebuilt

- test/e2e/integration/component-library/pdf.ts
#3223 added a check in `ReadyForPrint` for pending queries. This seems to have solved the issue at least for external api. I tried adding this test-case before this change and it would fail frequently, but it now seems to work consistently so we can include this test now.
- closes #3158
> Test external-api in pdf

- src/features/formData/useFormDataQuery.tsx
- src/features/instance/ProcessContext.tsx
- src/features/instance/useProcessNext.tsx
- src/hooks/useNavigatePage.ts
- test/e2e/integration/signing-test/double-signing.ts
- test/e2e/integration/signing-test/reject.ts
- test/e2e/pageobjects/app-frontend.ts
- test/e2e/support/apps/signing-test/signing-login.ts
As described in #3245, when rejecting and going back to the previous task, repeating group form data could be stale in a way that doesn't let you delete a row (that would cause a `409 conflict` as the data model on the backend had cleaned its `altinnRowId` fields). Invalidating the query cache when moving between process steps solves the issue.
- closes #3245
- Sprint board
- Labels
> Fixing broken form data when going back via signing rejection

- .github/scripts/release.sh
- .github/scripts/revert.sh
- .github/scripts/sync-index.sh
- .github/workflows/pr-actions.yml
- .github/workflows/release.yml
- .github/workflows/revert.yml
Remove everything related to syncing with Altinn-CDN repo:
- Removed checkout Altinn-CDN
- Removed commit to Altinn-CDN from release / revert scripts
- Removed push Altinn-CDN
- Revert script now works by directly calling `azcopy sync` between two virtual directories in azure
- Making the `index.json` file was previously done by listing the directories in the Altinn-CDN repo. I considered fetching the existing file and appending to it, but if there are race-conditions (multiple releases at the same time) things will not necessarily be eventually consistent. So I instead optet for moving it into a separate script / workflow step, and using `azcopy ls` to list the versions and generate the index file _after_ we are done with pushing the files. I tested generating the index file this way on …
> Sync with azure cdn directly

- src/features/formData/FormDataWriteStateMachine.tsx
- src/features/formData/convertData.ts
- src/features/formData/useDataModelBindings.ts
- src/features/validation/invalidDataValidation/InvalidDataValidation.tsx
- src/layout/Input/InputComponent.test.tsx
- src/layout/Input/InputComponent.tsx
- test/e2e/integration/frontend-test/components.ts
When combining number formatting with storing data in a `decimal` field in the data model, we have to convert the typed number to an actual number when storing it. To make sure we don't trick the user into thinking we can store numbers that cannot be stored, we _compare the typed number with the stringified number we stored in the data model_ and mark it as invalid if they aren't equal. This caused some unexpected friction for some use-cases:
- Typing `1` is fine
- Typing `1.` shows up as an error (if you stop typing at that point). We cannot store just the decimal point without any numbers after it.
- Typing `1.0` used to show an error (because we cannot tell a numeric type to store extra zeroes after the comma, this value is essentially equal to `1`). Now it stores the number (`1`) but …
> Fix: '1.00' marked as invalid data in an Input field

- src/app-components/Datepicker/utils/dateHelpers.ts
- src/features/receipt/ReceiptContainer.tsx
- src/layout/InstanceInformation/InstanceInformationComponent.tsx
I don't think showing the exact second is necessary in PDF, I think its more important to use the same format as in the receipt. We also don't need to use the `getDateFormat` function here, that is only intended for use on the DatePicker component's `format`-property, which is nullable. Using the function with a constant has no effect.
- closes #2476
- Sprint board
- Labels
> Use the same date format in instance information as in receipt

- src/components/presentation/AppHeader/AppHeaderMenu.tsx
- src/components/presentation/BackNavigationButton.tsx
- src/features/entrypoint/Entrypoint.tsx
- src/features/formData/FormDataWrite.tsx
- src/features/formData/useFormDataQuery.tsx
- src/features/instantiate/containers/InstantiateContainer.tsx
- src/features/instantiate/containers/MissingRolesError.tsx
- src/features/instantiate/containers/PartySelection.test.tsx
- src/features/instantiate/containers/PartySelection.tsx
- src/features/instantiate/selection/ActiveInstancesProvider.tsx
- src/features/instantiate/selection/InstanceSelection.tsx
- src/features/party/PartiesProvider.tsx
- src/layout/InstantiationButton/InstantiationButton.tsx
- src/layout/SigningActions/PanelAwaitingCurrentUserSignature.tsx
- src/layout/SigningActions/PanelNoActionRequired.tsx
- src/layout/SigningActions/SigningActionsComponent.test.tsx
- src/layout/SigningActions/SigningActionsComponent.tsx
- src/layout/SigningActions/api.ts
- src/layout/SigningActions/utils.test.ts
- src/layout/SigningActions/utils.ts
- src/queries/appPrefetcher.ts
- src/queries/partyPrefetcher.ts
- src/queries/queries.ts
- src/test/renderWithProviders.tsx
- src/utils/urls/appUrlHelper.test.ts
- src/utils/urls/appUrlHelper.ts
- test/e2e/integration/frontend-test/party-selection.ts
- test/e2e/pageobjects/party-mocks.ts
Was using `useCurrentParty` even though I've been the one that has dealt with that and seen that it should not be used inside of an instance. Was causing some bugs, but they should be fixed now after using `useProfile` instead.
- Sprint board
- Labels
> Fix current user bug

- src/features/navigation/components/SubformsForPage.tsx
- src/hooks/useNavigatePage.ts
- src/layout/Subform/SubformComponent.tsx
I will try to describe the issue. When entering a subform, the subform gets its own formcontext including validation state, this is initially populated by the initialValidations from tanstack. When making changes in the main form, we update the validation state with the partial validations from the patch responses. When you then enter a subform, and a new validation context gets created all of the incremental changes to the validation state are "lost" as it only gets the initial validations from the tanstack cache. Validation state is kind of global (as opposed to formdatawrite), we don't techincally need to have a separate state between subforms and the main form besides that our current architecture kind of forces us to.
This is a quick fix, as I was told this was important to fix. We …
> Validate when entering subform

- src/features/instantiate/InstantiationContext.tsx
- src/features/instantiate/containers/InstantiateContainer.tsx
- src/features/instantiate/selection/InstanceSelection.tsx
- src/layout/InstantiationButton/InstantiationButton.tsx
When running the cypress tests in the signing branch (specifically `frontend-test/message.ts`), sometimes the instantiation would be cleared early, and thus a later render of `InstantiateContainer` would trigger another instantiation before the first one had a chance to finish. The result would be that the user got two instances, and frontend crashed when it noticed the mismatch.
This should fix the issue by removing the timing part of this effect. The instantiation is only cleared when the URL changes (i.e. when the user navigates away).
- #3259 (bug presumably introduced here)
- https://digdir.slack.com/archives/C076GU2QHCG/p1746781299912699
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=unive …
> Fixing repeated instantiation bug

- .github/scripts/release.sh
Preview version were matched by `azcopy sync` regex when releasing a new prod version. I highly suspect that this is due to a missing `.` in the regex. The regex has been like this for a long time. But previously, we pulled the whole altinn-cdn repo, so even if some more versions matched, sync would find the files and not delete them. But now we don't do this any more, so when sync matches these versions and they don't appear locally, they are deleted.
To demonstrate:
https://github.com/user-attachments/assets/af7b1cc5-950c-4a27-8f46-4ae7a902ab67
- https://digdir.slack.com/archives/C076GU2QHCG/p1747226866975369
- #3201
> Fix release include-regex

- src/features/formData/jsonPatch/createPatch.test.ts
- src/features/formData/jsonPatch/createPatch.ts
- test/e2e/integration/component-library/checkboxes.ts
- test/e2e/integration/component-library/multiple-select.ts
I noticed in a test-run that the new group-binding tests for `Checkboxes` and `MultipleSelect` does something we haven't seen much of before; multiple rows are removed (and potentially added) in the same PATCH request. When doing so, it turns out our `createPatch()` function can end up removing indexes that doesn't exist in the data model.
As we can see in [this Cypress run](https://cloud.cypress.io/projects/y2jhp6/runs/8966/overview/998c0da3-6ce7-4f4b-9cc1-e0ef22352c2e/replay?att=2&pc=1895.609__network-calls&roarHideRunsWithDiffGroupsAndTags=1&ts=1747898874378.273), the patch is broken:
```json
[
{
"op": "test",
"path": "/MultiselectGroupExample",
"value": [
{
"altinnRowId": "49e1ac48-a940-4b9c-9c55-44e78cc0430a",
"age": null,
"profession": null,
"surname": null,
"Internal": null, …
```
> Fixing rare broken row-removal in PATCH

- src/app-components/Datepicker/DatePickerCalendar.tsx
- src/app-components/Datepicker/DatePickerInput.tsx
- src/app-components/Datepicker/Datepicker.tsx
- src/app-components/DynamicForm/DynamicForm.tsx
- src/layout/Datepicker/DatepickerComponent.tsx
Tested Datepicker component with VoiceOver on Mac, in both Safari and Chrome. Fixed two issues:
- The dialog now brings focus back to the input field when the dialog is closed.
- Always using the 'autofucus' property makes the current date focussed when the dialog opens, or the selected date (if a date was already selected).
This should fix the remaining accessibility issues for Datepicker. The one thing I found to be problematic is when tabbing outside the dialog when it is open. I can't seem to get back in by using tab alone (and I'm not confined to the dialog in any way), but it's solvable by closing the dialog using the button next to the input and then open the dialog again. I'm not sure if we can confine the user to the dialog (and how that can be done), and trying to cheat the user …
> Accessibility fixes for Datepicker

- src/layout/SimpleTable/ApiTableSummary.tsx
- src/layout/SimpleTable/index.tsx
Summary2 support was missing for tables with API data.
- Sprint board
- Labels
> add ApiTable summary mode support

- src/components/atoms/AltinnAttachment.module.css
- src/components/atoms/AltinnAttachments.test.tsx
- src/components/atoms/AltinnAttachments.tsx
- src/components/molecules/AltinnCollapsibleAttachments.tsx
- src/components/organisms/AttachmentGroupings.tsx
- src/features/applicationMetadata/types.ts
- src/features/language/LanguageProvider.tsx
- src/features/language/useLanguage.ts
- src/layout/AttachmentList/AttachmentListComponent.test.tsx
- src/layout/AttachmentList/AttachmentListComponent.tsx
- src/layout/AttachmentList/config.ts
- src/layout/Datepicker/DatepickerComponent.test.tsx
- src/layout/Group/__snapshots__/SummaryGroupComponent.test.tsx.snap
- src/layout/RepeatingGroup/Summary/__snapshots__/SummaryRepeatingGroup.test.tsx.snap
- src/layout/SigningActions/SigningActionsComponent.test.tsx
- src/queries/queries.ts
- src/types/index.ts
- src/types/shared.ts
- src/utils/attachmentsUtils.test.ts
- src/utils/attachmentsUtils.ts
- test/e2e/support/global.ts
Shows corresponding data type description for each attachment in attachment list.
- closes #3350
- Sprint board
- Labels
> Adds support for showing data type description in attachment list

- src/components/presentation/LanguageSelector.tsx
Uses "RovingFocus" components from the design system to add arrow navigation to language selector.
- closes #3500 
- Sprint board
- Labels
> Add arrow navigation to language selector

- src/components/atoms/AltinnAttachments.test.tsx
- src/components/atoms/AltinnAttachments.tsx
- src/components/atoms/AttachmentHeader.tsx
- src/components/molecules/AltinnCollapsibleAttachments.test.tsx
- src/components/molecules/AltinnCollapsibleAttachments.tsx
- src/components/organisms/AltinnReceipt.test.tsx
- src/components/organisms/AltinnReceipt.tsx
- src/components/organisms/AttachmentGroupings.module.css
- src/components/organisms/AttachmentGroupings.test.tsx
- src/components/organisms/AttachmentGroupings.tsx
- src/layout/AttachmentList/AttachmentListComponent.tsx
Fixes title set on attachment list disappearing if `groupByDataTypeGrouping` is `true` and all attachments have a corresponding data type grouping. 
- Sprint board
- Labels
> Fixes attachment list title disappearing

- src/features/entrypoint/Entrypoint.tsx
- src/features/expressions/shared-functions.test.tsx
- src/features/form/layoutSets/LayoutSetsProvider.tsx
- src/features/instantiate/instantiateHeader/InstantiateHeader.tsx
- src/features/language/Lang.test.tsx
- src/features/language/LanguageProvider.tsx
- src/features/profile/ProfileProvider.tsx
- src/features/stateless/getAllowAnonymous.ts
- src/layout/FileUpload/DropZone/DropzoneComponent.test.tsx
- src/queries/appPrefetcher.ts
- src/queries/types.ts
- src/setupTests.ts
- src/test/renderWithProviders.tsx
> Using profile directly from query instead of complex provider chains

- test/e2e/integration/component-library/date-picker.ts
> Fixes datepicker cy test relying on specific current date

- src/components/presentation/Progress.tsx
When going from a stateless to a statefull step, this flashes for a second before the correct page is shown:
then the correct progress is shown:
This PR hides the progress bar until the data is loaded properly.
- closes #2177
- Sprint board
- Labels
> hiding progress bar before pages is properly loaded

- src/layout/Checkboxes/CheckboxesContainerComponent.tsx
- src/layout/Input/InputComponent.tsx
- src/layout/RadioButtons/ControlledRadioGroup.tsx
Resolves broken aria reference by not adding it when using tables. 
Note: Descriptions could maybe be made usable in tables for both regular users and screenreaders later, but would be a breaking change for apps that contain components with descripitons that are displayed in a table today, since text and components would have to be pushed around to fit new content.
- closes #1629
- Sprint board
- Labels
> Fix broken aria references in table

- cypress.config.js
- package.json
- scripts/debug-flaky-cypress.sh
- test/e2e/support/index.ts
- yarn.lock
What the title says ☝️ 
- Sprint board
- Labels
> Adds script for running specified cypress tests until failure and save logs (for flaky tests)

- src/layout/ImageUpload/ImageUpload.tsx
- src/layout/ImageUpload/imageUploadUtils.ts
Målet med denne PR'en var å forsøke å gjenbruke deler av logikken til funksjonene `draw` og `handleCrop` slik at de blir enklere å håndtere og forhåpentligvis enklere å lese. 
Jeg flyttet til utils logikk som å kalkulere posisjonen til viewport og tegne innholdet til viewport.
Jeg husker ikke konkret årsaken til at jeg også kom over viewport størrelser i denne PR'en, men tenker vi kan beholde disse endringene for nå, hvis du ikke har noen innvendelser, Magnus. Viewport er nå en variabel som kan styres med konfig gitt de ulike størrelsene '1:1', '4:3' og '16:9' som er vilkårlig px størrelser som copilot foreslo. Dette antar jeg vi endrer på senere, også annen logikk som at den ikke kalles hvis det er satt `cropAsCircel` til `true`.
- …
> feat: add common utils for draw and handlecrop functions + variable viewport

- src/layout/ImageUpload/ImageUpload.module.css
- src/layout/ImageUpload/ImageUpload.tsx
Tanken bak denne PR-en var å redusere antall event-håndteringer og tilhørende state.
Tidligere håndterte vi separat `onMouseDown`, `onMouseMove`, `onMouseUp` og `onMouseLeave` og måtte ha 2 stater for å styre viewport-bevegelse knyttet til disse eventene. Med `onPointerDown` samler den eventene og styrer logikken videre.
Dette resulterer i at vi kan fjerne statene `isDragging` og `startDrag`, som forbedrer ytelsen ved å redusere re-renders og statehåndtering. 
Den håndterer også touch-screens. For å sikre forventet oppførsel der, settes `touch-action: none` i css for å hindre uønsket standard touch-adferd som påvirker canvas eventene når jeg har testet. 
Docs: https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event
`onPointerDown` støtter safari 13 og nyere. Jeg …
> Feat/unifiy events (reduce amount of states) and support touch

- .github/workflows/pr-actions.yml
Adding environment `test` to pr-actions workflow.
Vemund informed me that they will stop using SAS token for altinn-cdn, these changes will come soon, but the new authentication method will require a specific environment to have access.
> Chore: Add environment to pr-actions workflow

- src/layout/ImageUpload/ImageCanvas.tsx
- src/layout/ImageUpload/ImageUpload.tsx
- src/layout/ImageUpload/imageUploadUtils.ts
- Moves the canvas element into its own component along with its relevant useEffects and handlers. 
- Added a `handleZoomChange` that is used by both the scrollwheel on the canvas and the slider in imagecontrolls to update the zoom value
- Added a `handlePositionChange` that is used to update the images position state when the user moves the image with mouse or keyboard
For further development, maybe we could move the handlePositionChange into the canvas component. Or we could try to merge it with the handlePositionChange, seeing that the two handlers are fairly similar.
- User …
> Extract canvas and effects into its own component

- src/layout/ImageUpload/ImageUpload.tsx
Removes useMemo because it prevented minAllowedZoom from updating when the image loaded after moving cropArea calculations outside the component.
- Sprint board
- Labels
> fix: zooming limits

- src/features/expressions/shared-tests/functions/displayValue/type-ImageUpload.json
- src/layout/ImageUpload/index.tsx
Adds displaydata implementation and expression test for displaydata.
- Sprint board
- Labels
> Add displaydata expression test

- src/layout/FileUpload/FileUploadTable/FileTable.tsx
- src/layout/ImageUpload/ImageDropzone.tsx
- src/layout/ImageUpload/ImageUploadComponent.tsx
- src/layout/ImageUpload/ImageUploadSummary2.tsx
- src/layout/ImageUpload/imageUploadUtils.ts
- src/layout/ImageUpload/index.tsx
This PR utilize the logic for file upload in summary 2 so that image upload can also be presented in the summary.
Also changed the default size of cropper to 250.
- Sprint board
- Labels
> support summary2

- .github/scripts/release.sh
- .github/scripts/revert.sh
- .github/scripts/sync-index.sh
- .github/workflows/pr-actions.yml
- .github/workflows/release.yml
- .github/workflows/revert.yml
Release with SAS-token no longer works as the token is expired. To continue releasing patches in v4.21 we need to update the workflow
> [Backport] release workflow changes
